### ISSUE TITLE
Had this error popping up 

### ISSUE THREAD

**Issue by smalicious** [Tercioo/Details-Damage-Meter#10]
Message: ...\Details\Libs\DF\Details-Framework-Classic\panel.lua:8198: attempt to index field 'unitFrame' (a nil value)
Time: Sat Aug 31 12:14:55 2019
Count: 1
Stack: ...\Details\Libs\DF\Details-Framework-Classic\panel.lua:8198: attempt to index field 'unitFrame' (a nil value)
...\Details\Libs\DF\Details-Framework-Classic\panel.lua:8198: in function <...\Details\Libs\DF\Details-Framework-Classic\panel.lua:8192>
...\Details\Libs\DF\Details-Framework-Classic\panel.lua:8210: in function <...\Details\Libs\DF\Details-Framework-Classic\panel.lua:8209>
[C]: ?
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:535: in function <...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:516>
...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:102: in function <...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:77>
...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:139: in function <...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:124>
(tail call): ?

Locals: <none>

**Comment by Tercioo** [comment]
old report, fixed already.
