### ISSUE TITLE
Details! doesn't stay hidden

### ISSUE THREAD

**Issue by mrCamelCode** [Tercioo/Details-Damage-Meter#126]
I have confirmed it does this even when it's the only addon running.

**Game and Details! version**
R7927/v9.0.1

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):

1. Show the details panels by doing /details show.
2. Hide the details panels by doing /details hide.
3. Wait a few seconds.

- Result (what happens when you follow the steps above):

The panels reappear on their own without being told to show.

- Expected (what you think the expected behavior would be when following the steps):

The panels should remain hidden until they are explicitly shown (I've checked the Details settings and disabled anything that would make them appear on their own).

- When the bug started (a date, wow path release, details update, etc)?

I noticed this bug after I updated to the latest version available during the Shadowlands pre-patch.

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*

Even after running /console scriptErrors 1, no errors appear.

**Other Information**
If necessary, add more info here.

These are my settings:
![image](https://user-images.githubusercontent.com/29714304/96525238-72ecd100-1248-11eb-8e42-b827d25f83c0.png)

**Comment by Vashidu** [comment]
i'm having the encounter breakdown show anytime i go into a load screen, unsure if related.

**Comment by mrCamelCode** [comment]
This no longer seems to occur in details version R7933
