### ISSUE TITLE
Tiny threat

### ISSUE THREAD

**Issue by Dr-Tesla** [Tercioo/Details-Damage-Meter#13]
This is a cross post from classic threat meter, as it has the same issues because it uses the same threat library I think.

What spell(s) are affected? Please provide any relevant spell IDs/spell names.
Every paladin Seal/Buff up to at least level 33, and Hammer of Justice
If reporting your findings, please describe your methodology. If you've observed behavior that you feel is not in line with current values, please describe it.
Every Buff, including seals: Training level x1
Multipliers: HoJ (Rank one and two) x2 (Personally, I think all debuffs have this multiplier but its not been tested yet.
Blessing of Wisom x0
I started with Blessing of Might rank 1. I tested many things with ret aura, healing, and blessing of might while dual boxing. I came to the conclusion that , Blessing of Might rank 1. Most importantly, you don't do any threat when you aren't in combat. That means your first heal(when cast on someone who is in combat but you are not) puts you into combat but does no threat, as well as buffs cast out of combat also do no threat. Also, buffs (the ones I tested at least) do not put you in combat.
Then I found a blue post on the beta forums regarding battle shout rank 2 for warriors. Their findings were that it gave 12 threat per target buffed, split between mobs in combat, not 55, and they thought that was a bug. The blue post said it was the expected value and not a bug.
Please provide any data you have gathered and/or evidence of any observed behavior below. If pertinent, please provide any sources that may back up your research / observations.
https://docs.google.com/spreadsheets/d/1yKSKAdzeVl9byCuQX4PIME1t7S8xMpJk-4CKx03YlxQ/edit?usp=sharing
https://docs.google.com/document/d/1mwWh5tVF45kaqczEhd6_MtA1K7QutdVPSdQPF97PtCo/edit?usp=sharing
https://us.forums.blizzard.com/en/wow/t/new-bug-battle-shout/249633
Any additional information?
I have a theory that threat tables and combat tables are not tied together by default. By that I mean, you can have two people in combat with two mobs right next to each, but not be in combat with both until they do something that puts them in combat, such as casting a heal on each other. Mobs that are tied together (i.e. you pull one, they all pull) may be an exception (as they are already tied together). Mobs that have been connected by aoe effects .

Edit:
New hotfix:
In addition, we’ve also identified a fix for a separate issue that was causing Battle Shout and most healing spells, effects, and buffs to incorrectly split the threat they generate between enemies that had members of the buffed party on their threat list.

**Comment by Tercioo** [comment]
All new versions of details! always has the newest version of the lib.
