### ISSUE TITLE
Custom Displays not working

### ISSUE THREAD

**Issue by Diablolock** [Tercioo/Details-Damage-Meter#130]
The new uptaded, DetailsRetail.9.0.1.7932.143, broke custom displays.

Can't get any of them to work (CC done and received, dinamic damage, etc.)

**Comment by Tercioo** [comment]
I need errors, use: /console scriptErrors 1
The command will enable to show errors so you can report addon problems 
to authors

------ Original Message ------

**Comment by Diablolock** [comment]
There is no error associated to this problem. At least I can not see them. Have typied "/console scriptErrors 1" and also have BugGrabber and BugSack.

Here's how you can reproduce it: set 2 windows - 1 for damage done, 1 for Dinamic Damage from Custom Display

When you hit a mob or a dummy it will show the damage done on 1st window but never on dinamic damage from custom display. This also happens with every window of any custom display.

Here's an S/S of my Details: [https://imgur.com/a/njCqyJk](url)

Also tried to delete Details addon and perform a clean installation.

**Comment by utopianu** [comment]
Yep, I' having the same issue. None of the custom display works for me now.
