### ISSUE TITLE
TinyThreat not displaying any data

### ISSUE THREAD

**Issue by Daeymien** [Tercioo/Details-Damage-Meter#135]
**Details! version:** 7935 and 7938
**Game version:** 9.0.1

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
1. Load TinyThreat
2. Attack something with a threat table

- Result (what happens when you follow the steps above):

TinyThreat shows no data/bars

- Expected (what you think the expected behavior would be when following the steps):

Data/bars

- When the bug started (a date, wow path release, details update, etc)?

Starting with Details! r7935

**Comment by cadetklenk** [comment]
Every login, If you go into details option panel (under plugins) and uncheck the box by TinyThreat followed by re-checking it Then TinyThreat will load properly. You will then have to goto your TinyThreat window and tell it to display TinyThreat again.

It seems like on initialization Details isn't loading TinyThreat properly, after toggling it in the options panel it then loads it for use.

**Comment by Tercioo** [comment]
I confirmed the bug.
Below version 7935, tiny threat is working correctly?

------ Original Message ------

**Comment by cadetklenk** [comment]
Once it is loaded, Yes, It does appear to function correctly.

**Comment by Daeymien** [comment]
Appears to be working properly again as of r7950
