### ISSUE TITLE
Weakauras creator "Details!: feature disabled due to 9.0 changes"

### ISSUE THREAD

**Issue by Kortex49** [Tercioo/Details-Damage-Meter#141]
Hi team,

With Details! v9.0.1.1795.144 and WeakAuras v3.0.6 (both retails versions at the time of typing), I'm getting the error message "Details!: feature disabled due to 9.0 changes" when trying to generate weakauras via the WeakAuras creator.

Is it something that is being looked at? I can't manage to find much information on this issue from the www.

Thanks

**Comment by Tercioo** [comment]
it's been disable due to changes on weakauras, I do not have resources 
to fix this feature any time soon, sorry.

------ Original Message ------

**Comment by Kortex49** [comment]
Thank you Tercioo, appreciate the prompt update.
With SL raiding starting next month, you might see that the re-activation of this feature will climb up the priority list. Until then, I'm fine using some alternative.
