### ISSUE TITLE
[Request] Option to modify list of spells shown under 'crowd control done'

### ISSUE THREAD

**Issue by gobacktogo** [Tercioo/Details-Damage-Meter#153]
### **Before Start!**
not reporting a bug, rather asking for a feature.

**Game and Details! version**
game version: v9.0.1
details versions: R8002

**Describe the bug**

i hope this is the right place to request a feature:
my request is to allow users to modify the spells shown in tabs like 'crowd control done' or 'crowd control received'.

currently, the 'crowd control done' tab of details is missing some spells. for example, the druid stun rake (only is a stun when used from stealth), does not show up. spells like a priests silence dont show as crowd control either, though when used against a healer or caster in arena it basically is equivalent to CC. 

thanks for all your work!

**Comment by Tercioo** [comment]
Hello, I added into the Faq how to add spells, it's kinda simple 
actually.

Here is a copy/paste from there:

How to add a spell to Crowd Control? [-spell -add -cc - crowd -control 
-crowdcontrol]

On Run Code section in the options panel (far left list of options), 
paste this DetailsFramework.CrowdControlSpells[SPELLID] = "PRIEST"
Replace the SPELLID with the spellId of the spell you want, use /details 
spells to get it, if you add to another class change the class name, 
always in English and caps.


------ Original Message ------

**Comment by gobacktogo** [comment]
oh, sorry i missed that. thanks man!
