### ISSUE TITLE
Error when casting Incapacitating Roar.

### ISSUE THREAD

**Issue by heejae-kwon** [Tercioo/Details-Damage-Meter#160]
I got these messages when I casted Incapacitating Roar. My version is 9.0.2.8093.144

Message: ...\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:877: attempt to concatenate local 'charges' (a nil value)
Time: Sun Dec 20 18:31:56 2020
Count: 4
Stack: ...\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:877: attempt to concatenate local 'charges' (a nil value)
[string "@Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua"]:877: in function `SendCooldownUpdate'
[string "@Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua"]:760: in function `?'
[string "@Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua"]:469: in function `TriggerEvent'
[string "@Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua"]:509: in function <...\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:508>

Locals: spellId = 99
cooldownTimeLeft = nil
charges = nil
(*temporary) = "U"
(*temporary) = ","
(*temporary) = 99
(*temporary) = ","
(*temporary) = nil
(*temporary) = ","
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'charges' (a nil value)"
CONST_COMM_COOLDOWNUPDATE_PREFIX = "U"
raidStatusLib = <table> {
 GetPlayerSpecId = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:54
 GetPlayerTalents = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:87
 commHandler = <table> {
 }
 IsInGroup = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:182
 IsCommAllowed = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:139
 gearManager = <table> {
 }
 specAttribute = <table> {
 }
 UnpackTable = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:149
 TCopy = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:104
 playerAlive = true
 playerInfoManager = <table> {
 }
 cooldownManager = <table> {
 }
 publicCallback = <table> {
 }
 PackTable = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:112
 RegisterCallback = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:409
 internalCallback = <table> {
 }
 CanReceiveComms = false
 UnregisterCallback = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:421
 inGroup = false
 UpdatePlayerAliveStatus = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:64
 mainControl = <table> {
 }
 Schedules = <table> {
 }
 isNearlyEqual = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:133
}
diagnosticComm = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:47

**Comment by stgross22** [comment]
Spell IDs don't seem to match. It's the same for Stampeding Roar. To fix it go to 
...\Details\Libs\LibRaidStatus\TingsToMaintain.lua
 - line 431 change the ID 77764 to 288826
 - line 433 change the ID 99 to 236748 (this is the ID of Intimidating Roar, no idea why the wrong ID is called by the game)

**Comment by heejae-kwon** [comment]
Fixed
