### ISSUE TITLE
Hit/Miss Rate?

### ISSUE THREAD

**Issue by byeuji** [Tercioo/Details-Damage-Meter#17]
Hi, 

Apologies this isn't strictly an issue, so much as a support or feature request.

I'm using this mod in classic and it appears to work very will with little issue. 
One stat that I seem unable to find is my hit or miss rate in a given combat session or on a given target. 

I was able to find stats on my defensive performance (how many times I dodged, parried, blocked, etc.), but not my offensive hit rate on a target.

I see that custom displays are available, but I haven't the foggiest idea how to set one up for this, if it's even possible.

Can you assist me with this?

Regards,

Byeuji

**Comment by Tercioo** [comment]
fixed on recent versions.
