### ISSUE TITLE
Github release is missing assets

### ISSUE THREAD

**Issue by nonolai** [Tercioo/Details-Damage-Meter#172]
I was attempting to install Details from this repo using [AcidWeb/CurseBreaker](https://github.com/AcidWeb/CurseBreaker). It failed saying that it only supports projects with packaged releases. You _do_ have packaged releases so this seemed to be a bug on their side.

When you dive in, however, the actual issue is:

1. CurseBreaker [grabs the releases](https://github.com/AcidWeb/CurseBreaker/blob/master/CB/GitHub.py#L18) from `api.github.com`
2. CurseBreaker inspects the returned JSON looking for `assets`
3. The [JSON returned by the API](https://api.github.com/repos/Tercioo/Details-Damage-Meter/releases) has an empty list of assets
4. This is in direct disagreement with your release page that clearly shows the 2 expected assets:

![image](https://user-images.githubusercontent.com/6914695/103505794-f95c8c00-4e0f-11eb-9c33-3d51d7c57da9.png)

Is there a misconfiguration on your side making the two out of sync?

**Comment by Nuadh** [comment]
On the two other wow-addon release pages I checked, there's a release.json + another file in addition to the source code files. Probably something to do with how he does the releases. Too bad it's not fixed yet, as cf support in cursebreaker might break in the near future.

**Comment by nonolai** [comment]
This project is currently avoiding providing GitHub releases. (See #599)

Closing this as "Won't Fix"
