### ISSUE TITLE
Add Feast Food 

### ISSUE THREAD

**Issue by stevietv** [Tercioo/Details-Damage-Meter#179]
currently all foods from cooking are considered Tier 1, however the feast food is not added.

Can we add the following buffs to the list? 327706 (strength +20), 327707 (stamina +20), 327708 (intellect +20), 327709 (agility +20)

https://github.com/Tercioo/Details-Damage-Meter/blob/d93fa5248f17230ceb6ef99df9fbe3f20a54feaa/Libs/DF/spells.lua#L930-L951

**Comment by Tercioo** [comment]
Added, thank you!

------ Original Message ------

**Comment by stevietv** [comment]
thanks :D
