### ISSUE TITLE
Simple Request

### ISSUE THREAD

**Issue by Vectraat69** [Tercioo/Details-Damage-Meter#18]
I don't know if this is possible, but can we put a button on the windows that will lock the gear cog / overall data etc., and all of the other icons you mouse over to see more information? Meaning, once locked, you don't get these data pop-ups. Too often I am playing the game and I accidentally mouse-over the details windows and I get stuck in these menus for a brief second because I'm trying to manually reach for something on my action bars that isn't currently hot-keyed. I think this would be a great quality of life change if It isn't already implemented.

**Comment by Tercioo** [comment]
not a bug.

**Comment by Stealthmate** [comment]
> not a bug.

@Tercioo It may not be a bug, but it is a really bad feature. People move their mouse all the time, popping up menus every time someone mouses over your addon is annoying *at best* and infuriating otherwise. I would be happy to work on a PR to fix this if you want, otherwise I'll just fork it.
