### ISSUE TITLE
Lua error, Immersion trying to call UseQuestLogSpecialItem() which is protected

### ISSUE THREAD

**Issue by brittyazel** [Tercioo/Details-Damage-Meter#185]
**Game and Details! version**
R8156
v9.0.2

**Describe the bug**
If I am in combat when trying to use a quest item directly from the on-screen quest list (underneath the minimap), I will often times be presented with the bug below. It seems like Immersion has trying to call the protected function UseQuestLogSpecialItem(). I'm unsure why Immersion would be trying to call this function, but (having fixed a lot of these issues in the past) I think it's probably more likely that this bug is due to Immersion taking ownership of a frame that calls this function.

**Lua Error**
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Immersion' tried to call the protected function 'UseQuestLogSpecialItem()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `UseQuestLogSpecialItem'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTrackerShared.lua"]:95: in function <...ObjectiveTracker\Blizzard_ObjectiveTrackerShared.lua:88>

**Comment by Tercioo** [comment]
You're on Details! Damage Meter, would be better post on Immersion addon 
page?

------ Original Message ------

**Comment by brittyazel** [comment]
oh shit so sorry. I clicked the wrong bookmark, pardon me
