### ISSUE TITLE
Feature Request: Include Damage Prevented in the computation for the default Healing view

### ISSUE THREAD

**Issue by dzrw** [Tercioo/Details-Damage-Meter#188]
In 9.0.2, nearly half of disc priest healing contribution is captured in the form of absorbs.  However, since absorbs are not counted in the default healing view, discipline is perceived to be underperforming by the vast majority of players who do not look at more specialized meters.

Computing the effective contribution towards healing as heals + absorbs would go a long way towards fixing this bias in the player base.

**Comment by Tercioo** [comment]
absorbs are tracked, use a power word shield, get some punches, see the 
power word shield heal.

------ Original Message ------

**Comment by dzrw** [comment]
Can you clarify that the computation in the default healing view includes the numbers in the more specialized Damage Prevented view?
