### ISSUE TITLE
[classic] Percent showing higher than 100

### ISSUE THREAD

**Issue by chrisblossom** [Tercioo/Details-Damage-Meter#19]
I am sure I have a setting incorrect somewhere, but when enabling show percentage, the percents are well above 100. I am not sure what is going on and would like some direction how to fix this! Thank you!!

![wow classic details damage meter percent](https://user-images.githubusercontent.com/1595871/67320034-8b55ce80-f4c2-11e9-8e47-dbab97ad10d1.jpg)

**Comment by doadin** [comment]
Not on Classic but been seeing something similar on retail for a long time now. Not nearly as crazy but...
[https://imgur.com/VOA2I6X](url)

just not sure how with 1 out of 1 person can be over 100%. Similar things happen with other things too like interrupts. There will be 1 person with 1 kick and it will say like 99.4%. last I checked 1 of 1 was 100%. What am I missing?

**Comment by chrisblossom** [comment]
The issue was not having a default separator on when enabling percent and DPS at the same time.

@Tercioo IMO a space should separate them when set to none.

Thanks for the great work!!
