### ISSUE TITLE
Chat Message (Debug Messages?) With latest update D! DBM_Announce...

### ISSUE THREAD

**Issue by chrisafl** [Tercioo/Details-Damage-Meter#190]
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**
This requires the combination of Details AND DBM addons as details is outputting everything DBM is doing to the chat frame. I have disabled all other addons.

**Game and Details! version**
Use /details to grab these two.

Details 9.0.2.8192.144
WoW Shadowlands Retail

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
- Disable all addons except Details! and DBM (and enough mandatory modules to get it to run)
- Open dbm (/dbm)
- Go to Core & GUI
- Click "Start test bars"
- Look at your chat frames

- Result (what happens when you follow the steps above):
- Messages like this were entered into my chat box, one for every test bar that was created in DBM:
D! DBM_Announce Test-mode started... 136116 nil nil TestMod false 
D! DBM_Announce Test bar expired! 136116 nil nil TestMod false 
D! DBM_Announce Pew Pew Laser Owl nil nil nil TestMod true 
D! DBM_Announce Pew Pew Laser Owl! 135826 nil nil TestMod false

- Expected (what you think the expected behavior would be when following the steps):
- My chat box to not get those messages created

- When the bug started (a date, wow path release, details update, etc)?
- When today's version of Details! was released

- Additional information:
- I love you

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*

**Screenshots**
Post images of the bug if necessary.

**Combat Log**
Include a link to a combatlog file if the error is about not detecting a skill, usable item or item proc.
The log can be as simple as hitting a mob with white damage and using the item/skill.

**Other Information**
If necessary, add more info here.

**Comment by Tercioo** [comment]
update the addon

------ Original Message ------
