### ISSUE TITLE
Feature Request : Forgeborne Reveries Death Log

### ISSUE THREAD

**Issue by Zolsten** [Tercioo/Details-Damage-Meter#193]
A Necrolord using the Bonesmith Heirmir Soulbind will keep 'living' for 10 seconds after they 'die' due to the Forgeborne Reveries ability. This means that the useful information of what actually killed the character is overwritten by the activity in the 10 seconds after they die but aren't really dead yet.

Please consider (if reasonably implementable) modifying the functionality so that the combat information leading up to the proccing of Forgeborne Reveries is what is shown when inspecting a death.

Thank you.

**Comment by Tercioo** [comment]
got you, thanks.

------ Original Message ------

**Comment by Zolsten** [comment]
Tested new version and seems to be working. Thank you very much!
