### ISSUE TITLE
LUA error on arena entry

### ISSUE THREAD

**Issue by JRVinson87** [Tercioo/Details-Damage-Meter#194]
78x Details\core\control.lua:951: table index is nil
[string "@Details\core\control.lua"]:951: in function `GetPlayersInArena'
[string "@Details\core\control.lua"]:1057: in function `EnteredInArena'
[string "@Details\core\parser.lua"]:4480: in function `?'
[string "@Details\Libs\AceTimer-3.0\AceTimer-3.0-17.lua"]:55: in function <...ceDetails\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:
self = <table> {
 SetBarSpecIconSettings = <function> defined @Details\frames\window_main.lua:4245
 APITopics = <table> {
 }
 InitializeRunCodeWindow = <function> defined @Details\frames\window_runcode.lua:8
 EntrarEmCombate = <function> defined @Details\core\control.lua:316
 hex = <function> defined @Details\core\util.lua:654
 BuildSpellList = <function> defined @Details\functions\spellcache.lua:322
 opened_windows = 2
 RefreshAttributeTextSize = <function> defined @Details\frames\window_main.lua:7549
 PotionList = <table> {
 }
 EndRefresh = <function> defined @Details\core\control.lua:1722
 FechaJanelaInfo = <function> defined @Details\frames\window_playerbreakdown.lua:396
 GetMode = <function> defined @Details\classes\class_instance.lua:173
 SetMode = <function> defined @Details\classes\class_instance.lua:2724
 RestoreState_CurrentMythicDungeonRun = <function> defined @Details\functions\profiles.lua:1474
 APIVersion = 144
 IsPluginEnabled = <function> defined @Details\core\plugins.lua:58
 ImportProfile = <function> defined @Details\functions\profiles.lua:1633
 show_totalhitdamage_on_overkill = false
 SetNickname = <function> defined @Details\Libs\NickTag-1.0\NickTag-1.0.lua:573
 color_by_arena_team = true
 SortKeyGroupHeal = <function> defined @Details\classes\class_heal.lua:125
 SortKeyGroup = <function> defined @Details\classes\class_damage.lua:134
 IsInEncounter = <function> defined @Details\core\parser.lua:5624
 Check_ZONE_CHANGED_NEW_AREA = <function> defined @Details\core\parser.lua:4385
 plugin_window_pos = <table> {
 }
 gump = <table> {
 }
 CaptureRefresh = <function> defined @Details\core\parser.lua:4038
 NewModule = <function> defined @BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 InstancesToStoreData = <table> {
 }
 name_space_info = <function> defined @Details\core\util.lua:1359
 ShowDelayMsg = <function> defined @Details\boot.lua:751
 Resize = <function> defined @Details\classes\class_instance.lua:1899
 GetEncounterActorsName = <function> defined @Details\functions\boss.lua:306
 RequestCloudData = <function> defined @Details\core\network.lua:773
 RestauraJanela = <function> defined @Details\classes\class_instance.lua:1458
 default_skin_to_use = "Minimalistic"
 GetOpenedWindowsAmount = <function> defined @Details\classes\class_instance.lua:281
 GetInstanceGroup = <function> defined @Details\frames\window_main.lua:8033
 deadlog_events = 32
 Dump = <function> defined @Details\frames\window_dump.lua:14
 OpenNewsWindow = <function> defined @Details\frames\window_news.lua:7
 last_instance_id = 2289
 Disable = <function> defined @BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
 atributo_energy = <table> {
 }
 UnitDamageOnUnit = <function> defined @Details\functions\api2.lua:1123
 name_space_generic = <function> defined @Details\core\util.lua:1369
 storage = <table> {
 }
 AdjustAlphaByContext = <function> defined @Details\frames\window_main.lua:7371
 AddOnStartTime = 423379.543000
 ContainerSortEnemies = <function> defined @Details\classes\class_damage.lua:254
 ToolBar = <table> {
 }
 GetTitleBarText = <function> defined @Details\frames\window_main.lua:7644
 FixToolbarMenu = <function> defined @Details\classes\class_instance.lua:1446
 UseWestNumericalSystem = <function> defined @Details\core\util.lua:292
 FazerAnimacao_Esquerda = <function> defined @Details\core\windows.lua:234
 Desagrupar = <function> defined @Details\classes\class_insta

**Comment by Tercioo** [comment]
got it, thanks

------ Original Message ------

**Comment by EirikFladby** [comment]
Still getting 2 errors like these upon arena entry:
`Message: Interface\AddOns\Details\core\control.lua:951: table index is nil Time: Thu Mar  4 09:11:21 2021 Count: 2 Stack: Interface\AddOns\Details\core\control.lua:951: table index is nil [string "@Interface\AddOns\Details\core\control.lua"]:951: in function `GetPlayersInArena' [string "@Interface\AddOns\Details\core\control.lua"]:1009: in function `?' [string "@Interface\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua"]:55: in function <...ce\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:50> Locals: self = <table> { SetBarSpecIconSettings = <function> defined @Interface\AddOns\Details\frames\window_main.lua:4245 APITopics = <table> { } InitializeRunCodeWindow = <function> defined @Interface\AddOns\Details\frames\window_runcode.lua:8 EntrarEmCombate = <function> defined @Interface\AddOns\Details\core\control.lua:316 hex = <function> defined @Interface\AddOns\Details\core\util.lua:654 BuildSpellList = <function> defined @Interface\AddOns\Details\functions\spellcache.lua:322 opened_windows = 1 RefreshAttributeTextSize = <function> defined @Interface\AddOns\Details\frames\window_main.lua:7549 PotionList = <table> { } EndRefresh = <function> defined @Interface\AddOns\Details\core\control.lua:1722 FechaJanelaInfo = <function> defined @Interface\AddOns\Details\frames\window_playerbreakdown.lua:396 GetMode = <function> defined @Interface\AddOns\Details\classes\class_instance.lua:173 SetMode = <function> defined @Interface\AddOns\Details\classes\class_instance.lua:2724 RestoreState_CurrentMythicDungeonRun = <function> defined @Interface\AddOns\Details\functions\profiles.lua:1474 APIVersion = 144 IsPluginEnabled = <function> defined @Interface\AddOns\Details\core\plugins.lua:58 ImportProfile = <function> defined @Interface\AddOns\Details\functions\profiles.lua:1633 show_totalhitdamage_on_overkill = false SetNickname = <function> defined @Interface\AddOns\Details\Libs\NickTag-1.0\NickTag-1.0.lua:573 color_by_arena_team = true SortKeyGroupHeal = <function> defined @Interface\AddOns\Details\classes\class_heal.lua:125 SortKeyGroup = <function> defined @Interface\AddOns\Details\classes\class_damage.lua:134 IsInEncounter = <function> defined @Interface\AddOns\Details\core\parser.lua:5624 Check_ZONE_CHANGED_NEW_AREA = <function> defined @Interface\AddOns\Details\core\parser.lua:4385 plugin_window_pos = <table> { } gump = <table> { } CaptureRefresh = <function> defined @Interface\AddOns\Details\core\parser.lua:4038 NewModule = <function> defined @Interface\AddOns\AutoVendor\libs\AceAddon-3.0\AceAddon-3.0.lua:235 InstancesToStoreData = <table> { } name_space_info = <function> defined @Interface\AddOns\Details\core\util.lua:1359 ShowDelayMsg = <function> defined @Interface\AddOns\Details\boot.lua:751 Resize = <function> defined @Interface\AddOns\Details\classes\class_instance.lua:1899 GetEncounterActorsName = <function> defined @Interface\AddOns\Details\functions\boss.lua:306 RequestCloudData = <function> defined @Interface\AddOns\Details\core\network.lua:773 RestauraJanela = <function> defined @Interface\AddOns\Details\classes\class_instance.lua:1458 default_skin_to_use = "Minimalistic" GetOpenedWindowsAmount = <function> defined @Interface\AddOns\Details\classes\class_instance.lua:281 GetInstanceGroup = <function> defined @Interface\AddOns\Details\frames\window_main.lua:8033 deadlog_events = 32 Dump = <function> defined @Interface\AddOns\Details\frames\window_dump.lua:14 OpenNewsWindow = <function> defined @Interface\AddOns\Details\frames\window_news.lua:7 last_instance_id = 2286 Disable = <function> defined @Interface\AddOns\AutoVendor\libs\AceAddon-3.0\AceAddon-3.0.lua:314 atributo_energy = <table> { } UnitDamageOnUnit = <function> defined @Interface\AddOns\Details\functions\api2.lua:1123 name_space_generic = <function> defined @Interface\AddOns\Details\core\util.lua:1369 storage = <table> { } AdjustAlphaByContext = <function> defined @Interface\AddOns\Details\frames\window_main.l`

and

`Message: Interface\AddOns\Details\core\control.lua:951: table index is nil Time: Thu Mar  4 09:03:37 2021 Count: 2 Stack: Interface\AddOns\Details\core\control.lua:951: table index is nil [string "@Interface\AddOns\Details\core\control.lua"]:951: in function `GetPlayersInArena' [string "@Interface\AddOns\Details\core\control.lua"]:1057: in function `EnteredInArena' [string "@Interface\AddOns\Details\core\parser.lua"]:4480: in function `?' [string "@Interface\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua"]:55: in function <...ce\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:50> Locals: self = <table> { SetBarSpecIconSettings = <function> defined @Interface\AddOns\Details\frames\window_main.lua:4245 APITopics = <table> { } InitializeRunCodeWindow = <function> defined @Interface\AddOns\Details\frames\window_runcode.lua:8 EntrarEmCombate = <function> defined @Interface\AddOns\Details\core\control.lua:316 hex = <function> defined @Interface\AddOns\Details\core\util.lua:654 BuildSpellList = <function> defined @Interface\AddOns\Details\functions\spellcache.lua:322 opened_windows = 1 RefreshAttributeTextSize = <function> defined @Interface\AddOns\Details\frames\window_main.lua:7549 PotionList = <table> { } EndRefresh = <function> defined @Interface\AddOns\Details\core\control.lua:1722 FechaJanelaInfo = <function> defined @Interface\AddOns\Details\frames\window_playerbreakdown.lua:396 GetMode = <function> defined @Interface\AddOns\Details\classes\class_instance.lua:173 SetMode = <function> defined @Interface\AddOns\Details\classes\class_instance.lua:2724 RestoreState_CurrentMythicDungeonRun = <function> defined @Interface\AddOns\Details\functions\profiles.lua:1474 APIVersion = 144 IsPluginEnabled = <function> defined @Interface\AddOns\Details\core\plugins.lua:58 ImportProfile = <function> defined @Interface\AddOns\Details\functions\profiles.lua:1633 show_totalhitdamage_on_overkill = false SetNickname = <function> defined @Interface\AddOns\Details\Libs\NickTag-1.0\NickTag-1.0.lua:573 color_by_arena_team = true SortKeyGroupHeal = <function> defined @Interface\AddOns\Details\classes\class_heal.lua:125 SortKeyGroup = <function> defined @Interface\AddOns\Details\classes\class_damage.lua:134 IsInEncounter = <function> defined @Interface\AddOns\Details\core\parser.lua:5624 Check_ZONE_CHANGED_NEW_AREA = <function> defined @Interface\AddOns\Details\core\parser.lua:4385 plugin_window_pos = <table> { } gump = <table> { } CaptureRefresh = <function> defined @Interface\AddOns\Details\core\parser.lua:4038 NewModule = <function> defined @Interface\AddOns\AutoVendor\libs\AceAddon-3.0\AceAddon-3.0.lua:235 InstancesToStoreData = <table> { } name_space_info = <function> defined @Interface\AddOns\Details\core\util.lua:1359 ShowDelayMsg = <function> defined @Interface\AddOns\Details\boot.lua:751 Resize = <function> defined @Interface\AddOns\Details\classes\class_instance.lua:1899 GetEncounterActorsName = <function> defined @Interface\AddOns\Details\functions\boss.lua:306 RequestCloudData = <function> defined @Interface\AddOns\Details\core\network.lua:773 RestauraJanela = <function> defined @Interface\AddOns\Details\classes\class_instance.lua:1458 default_skin_to_use = "Minimalistic" GetOpenedWindowsAmount = <function> defined @Interface\AddOns\Details\classes\class_instance.lua:281 GetInstanceGroup = <function> defined @Interface\AddOns\Details\frames\window_main.lua:8033 deadlog_events = 32 Dump = <function> defined @Interface\AddOns\Details\frames\window_dump.lua:14 OpenNewsWindow = <function> defined @Interface\AddOns\Details\frames\window_news.lua:7 last_instance_id = 2286 Disable = <function> defined @Interface\AddOns\AutoVendor\libs\AceAddon-3.0\AceAddon-3.0.lua:314 atributo_energy = <table> { } UnitDamageOnUnit = <function> defined @Interface\AddOns\Details\functions\api2.lua:1123 name_space_generic = <function> defined @Interface\AddOns\Details\core\util.lua:1369 storage = <table> { }`
