### ISSUE TITLE
Missing two localized translations

### ISSUE THREAD

**Issue by BlueNightSky** [Tercioo/Details-Damage-Meter#20]
L["STRING_OPTIONS_TEXT_LTRANSLIT"]
L["STRING_OPTIONS_TEXT_LTRANSLIT_DESC"]

**Comment by raysmith59** [comment]
Confirmed, I got this when opening the options panel:

1x AceLocale-3.0-6: Details: Missing entry for 'STRING_OPTIONS_TEXT_LTRANSLIT_DESC'
Details\gumps\janela_options.lua:6799: in function `?'
Details\gumps\janela_options.lua:11290: in function `OpenOptionsWindow'
Details\gumps\janela_principal.lua:9420: in function <Details\gumps\janela_principal.lua:9410>
[C]: in function `pcall'
Details\Libs\DF\fw.lua:2665: in function `CoreDispatch'
Details\Libs\DF\button.lua:887: in function <Details\Libs\DF\button.lua:800>

**Comment by Tercioo** [comment]
fixed, thanks.
