### ISSUE TITLE
Title bar encounter timer not working

### ISSUE THREAD

**Issue by Fujiwarahub** [Tercioo/Details-Damage-Meter#204]
Game version: 9.0.5
Details! version: R8406

A few days ago I wanted to try out the "Encounter Timer" feature, found within the title bar options.
I opened up the options panel, went into the title bar settings and ticked the encounter timer feature but without any change whatsoever in how to title bar is displayed during combat.
I thought the problem could have been the text colour alpha so I checked it but it was set on "100".
I even tried to disable all of my addons except for details! but nothing really happened.

**Comment by Tercioo** [comment]
Hello, please export your profile and paste it here

------ Original Message ------
From: "Fujiwarahub" ***@***.***>
To: "Tercioo/Details-Damage-Meter" 
***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 03-May-21 12:49:01 PM
Subject: [Tercioo/Details-Damage-Meter] Title bar encounter timer not 
working (#204)

**Comment by Fujiwarahub** [comment]
Hi, here's my profile:

T33AZTnsw79BjvQu7mvT2bnUJSv(aLfLT2rIYrqEMDQYLGajHerzqcUaGwwtYQ)x5Z5pwEoNUBCJau0Zo78ozJDnJKizF9C95CA0hER42BUnCBr(9Pzj0FwUk)XO4IKnXrf5zjrPlY3C78BdxeVTAxrsursCg1Uv0VpbTFBsw2I4Yk6fRtlxSmUkM(74Df8Vt2Ku8Wt0FTmED8dj4VQUnSaZY9XlX4VbJ2mXTH4pMzE7mJxBsFEzfMO1jfry6Vp9bAgVhtcEJDBXmKusRP)(U0fFkAzsvYIQu5YSiPmPkclQfrlIxSkHEVn5rXzjfvCF2vMefVjDDm1JO4fls4TXY0Y45y7U(PQvPlIwUBZdj8iI1YMDyHKUiolQ8jSewZlxACOnr9yvsdtrY28IQiI4eLLU5tLY1068plPCRJUViFD0gS1K0l07DRJWhxeNLHn765XvrvP4JNjmWYkjUAvuvEEwv62OhtxwT62zwog1ZuvE0JRYVnemOS4YsENxIXjVyzjryDnLKxIU6icCSeMok6SLh(ll6V43Zw2gSHN5Av3jUrCZhRXMy1OATQLClS4xBRFn3qr9W2SkgRTTx39xW9BBZY1xTCfd3q7XwPdSRCoWIDFkM7HADDJPDap4E1nx3y3d0A)6w7Az63mbEJ3LG6UuZa9hV5UgJrb3RToEEhGZ8ADRDvKXwYFdqy4(zl7hn2(Idi4T3qBFGg3BKnDDoafFVg3WnD3NyVxR9oeTEVw7FOXEpXq3Gr5m71wpJdTq638wTECld95(cdZXj6D128eJUY7rtegwJZC6nOMJQb3t8qyyFacDVr16qcP7j3zDifG92BohGP0Z(KRy0DxFXih3di83NR1i8V34UxtTpGEsprOQAGdrLXWb32C2hOYBLcKWs4YUSkUAx584IM1SMUP3EQX1hgbGlZzU0p8Un8NYlYwgIUN88DHlYlsOj9(8nvlYZYlIksFyvLAqfAwClsRGAo8dNapYCtNj8QxGrRJ)suvCXdjaza6Bib1jQm9xyCq)KSTVJ)vv3oTv3J4nlwrlJKmab4ZjuR2I3D(8IKpNYOcA1SKLWBnJDqIXAD(Unve(afvQk5lvr8(Q3okq452Ftr0aEPYWeMhV4tpuGXBzJGCGRMzh4Q5F0FPOZegRDZxNSzx0Ja6X24Tjfe3tpWaesvMA4zcZCaPqUkz0fen6eE1zki55WlOxy4XUNcVP9lUUvZW0cqoRJ3WWt6rxJNNMLwLcWDqaGxj3hVau1Zks)LNV7)XU4LfaC5Z3DdMB1YPn9sjD3Nu1SWjaS3gEAsvCAw5Z3DsCXj8N98Dw18Y87Vhii7nIyuW6lDnrxwNuTkFjZhzA1Q4L5psSr18O4k2OlG4wgn)HMP(8nablTN(y47NEXfNC1v)Whdja0ZZZ)0REpqh)kr9kPCrrsYgwRsUACm8iPBSIEfGaYgc0TDBE6gERwvLVU1m3aeuC7zoo(g2oMw(Mg(Mw223E)RaIimEN5BzcpKMM2((qgXYG(ew18mpxpBHLTWZZYXveyrFcBe4mhdaBq4z7eyyAz5fihT2QNDeJL2(fnSLwRXwSqYcGP63wQFBRJkGm4ug1v9cCUhjJeASZPLrvfXLRioY2pVnkUmI0m2sY2evEDCXNKQAkgftW1Xda4ZqnfWYXy8zezaMyBibJxHansb2)OSKplJy4X0nGXxEWOys3atFBwKugXkAlYO4vaK98TjC0k14(ZsIlI2K84Iv4LjB4OKcPWaIQEABcBeHIRIB4MDBJYYFiFhB8Ozk0HWa7SrRG1Um2I3CE1xUIcKAbSJUb)phphBaD(tQy9Qq0wCuBDjfG(A1eCefuw1IvYyyifxYK(8MpplhBpe5erVJMVdYIB4aGwJaGkEkQatb5GPU9ssOK)u2DZuUB7welNMzoZOZhM8aONvL8eIfjw35B5yWudjhilcylrjRThdo(lAgSfhK1sqqraBRtjxeUTNle8yw6C1WoxkDhrQWKwLuig6138MNVBYNJ3u98DVngMbWVYPajF(UltwMUBnB3JzYkYJCvZ805f5FszFIJJBxb4ivrl3ssnWEbnpGfbc2Y6fWrOFj5R6oQSShPmxfo7Qzt1VLupWh7Mob)2UVLXR3scaCtDArfg2489fuaU6Sji9KmNdQNsoq4fx9tsFwllY3(cMWvAskon7Tu6jhGAcvbeBAYMOLzga6IGO954mjUIAjd9AQQJIPCEXknszOnCtEXAzkoE62ZELhSt6z5A4AgyzeW2mXpc)cSmA5BdZMMwbUMEuWi4tiJr4tceU2(wc8FcxtFF6tWID1TNHrX3WWsyB45j8TnKFc5kg0a5usQ6FHnL8iOcggu)MzAyix3m9SbofPht2uQwbzQhwf1iMY2BKoh0Ijk8ayqsxYMuihgpevGLfCu7himnGn(axEbd8LHRq7IGzg4tuzDTLHdL29bfbvMi4CifXjyQLhWjlxE1MYpQ8g)Xuk3qLFSDxkPeKSOiNSSTnl(P267SR3QI0npu2KweIl(im4tMxvYTpMsgSiBSu2SkHWr7TsBANAMLt8CzgQs3CpZwiDZRjsbHLuL1Rfh5oIBkpQrkrlE4UO9W1z8JkrJYAEBMNZzvJj2ZjA9jePMtKgGTTGmxi9tqGss)cH0CyWK7XIk3skXylkHstIhzj3l)J5jvpceiAMPeetudwZizkNKZY8EBl5U4yWNvBlzickiBFmCfSLTKmKgJ3jLuNJZoJea(ilg8Xx087RZRUVXItpdQnWOpc61brrAwVDAabkjkWW3MsGTvALFEd1CXUsGyBVDEtdEzAYhRTh8XlbuY0gtKMqCyD(YKm2Wg8Oc3m8RVnKrDw(XjlsxEsbNKr85jfVLGC(6lnjdUp20AomSpo9V9(jZcp)QzgMF80RU60jNg(X3KNTmUOi(JV5QloDY1xp5IREZhcF9At98fNTDvSmCs1y2I0lFJ6Mi0DQPjvQOpooDnwGKaiWAqYE(qbSCWybQfrveDPh3)NKQL4F86NVJ)lR)b)lZ)HmfVnAVnkKYvxNrzyPF2qvT6iZUhvDOspcS6(MDRNNuSVGcbqq)ony8ArxG34eeB1zKZUp(HZFL61xKww9Q310b5gzi6WZ39DkcWFUMI8F57Bj4RKX6UVABu4L14hOx)AeZvBIgJqLAc21F9wHusgdmyDxP1eaLuRGpFb9PKWsCJfcj2afvrX3tNIb3Ht6aK6Lbr2im0EzEIEXpSCjDSjralPeDudfQmzBmGJb6s4)l97nNIZblDj8WQA)NaR0NytL9DNk3mpMUnPg0HuzH38N0Yvfi0NqqhprMChLJNzVYKa1OcHUIWIxcUmwxekDmCutJ3HqMyWi87CJYf1CTtlUJQyjQr9lrVOjZAyfsOpcg4ZdJc8PzF0X8f6Z8r7tnC299q8wLGtlPqe9SVRnbb001ZJs4mpkuS4J8jwJ(j2kXljCncFZgM3Rr22YEB6geWzjZRaa5DSBpdoFIhBdTo2gAFSn05yBO7X2qVJTH(hBddo2gkmo6wE08gXrZCehn3rC0ShXXYFiRfFkDdSpshQzCg84KUGmWLbV8aNEVHH0ghhVLYG8bBrJ5j64wLElBhwanaM6yGOJ7OTEndq7mpxhxHiWXxy6rzftM3R(rDOJxkmK9abaFHXFoHZakb9gZC4PtVzY5xegfEZKB(q4jtUo69x8H3E(SO3a8q)G2q14n79N((W6qvPb(WTufsYpFPkrKQeICJoxr0hEg7uzYcGWdFuC2Z39(IeARSzXtC6mdLNA(5llLr)tPB6gDue0imbGfKzyJEvynmz6vV5fHkFWTB403E50z3877gr8B)grYE)DDxy(RDxuP8BEeSLkw)KIwg66vn5DQTQLvTQff4ToHkQed0n1dVY0tTMWatwp0zUT)yAxpMguS8nH7ltNb7lURzK8nsnqo3RKMn80tDaKQ8IeAtiBvwcuzRtlbO)rYJJQ7yL9eLGG68fZOhAbk983C1SWpE(SFmcJFAw0nyPMU(qXnYu9OOYnXBFhJ6HZFd466vwNuI1jFePBKjQGwv0Irok0SyRsEdzUTvCbsap68BuJCP2kP8XVHntcKmnFCt6nL58Y2122YkW01Y0iW2ZKssLhNuQx596GGaphhFNa68cdvh7WjxDZnxD51N)231lVR1q2RZKsZ0s5(gMx)nhpetYJRGufeftIuqH0zICT8uUuqoprNmmXl6VPoqHUbnrpjp)dvNpAy8DvoeYJ8WQ2PxtczhgrFtEzRfU(rAR0r8Pi)XYEjcmcB5nDZg4RSQro2i5uNkje68CcrjDQMZ75TTBM044EAHDVg2UkB28PVqwukPhAPLPfQNyl2AzhXZUJBR4p6(bDxY8H9KxMUio)p8PWLjdpqzxSlzO1XMVP9jHArVoztYA1ROyDQpW2UgWAD2SnHE29rHIpl7oQEJE(bsH0qotkQmkDMVHPJbOhcpFBqjivoB3gT6xxNt(ZSd8GvcHVNWlWX0qr1vpzFepv5OOw)tAXoAn)uSbLvIdZ81SDpaVldrYOe0SEhOArTCKOZDR8q21h8dB7zdzS(SymUTGAjDnkJaAKdbWg2zmTCnbp0b)Z8FojiFFxxBpBxhHPVNA08(2Ha8Tdb43S86D4tm4Gjl6BhEWihEWxvMJ)dWzaSFYR)2jb0(Kag5WGEHZ35yoIO6ZtQA40Qoqk9pWH49R)udo0bvm6Hn(pZrcmu(T)nmv)7ND(MuWFG80)B6PeCSP6)FMth53YJey)JJ6OonGwhG43oeGVDiaF7qa(2Ha8B3Ha8Iz(VN74VDiaJEiadK24V(Cp3j11)h0Ha873g5FLhcWVF7IVDia9sCVo9(9s8F7JeO1rf8VbhcGMs(VOdbWx4A655yf4Bbeh260x9)JFiaTFIM)d6ja09CkgpcUMtj4BhcWrCia)blfU)wFiahvg9p2JhOL1W))RdbOQ(A1tbnxY30bA4HWvvwIkc(YKcqSJq4YLs7OCM2awrqIMpm8xI7uqYQCXsiDz7sfq5IvjRLjXGaAIrEPmKXHUklm256yld)0tCUJvZ50Sp)HZ1hVtNBvecR)HvQs0aEP(E3OVQJ13nsh)6RuHLm)v6cuqNctGtDG2lYIxVvBfZVv6mmLIDVsylV5l57wgPQGenvccOr)PeiwJLlDXtq0be9JPK6BFKzRCP26c3OYU2Iv0AcMNswpxcfVLO7t6KZq(z(s7xq9GRadHKX)npuFtK0zFqEDGW6AdDppTmBiP3Nf)G8gcH9eX3xLMKTSuEocYeWOUWDHV7dZUz619U4T7FVB5Zo8NMC91NF1ynU9DUnm8DtUCYS9VbY2bUgbdCXT5oD5K3o9L6sNz59tV5fNc1nsMnTC61F48tBUOZ2Yl7P66R67RkAb7nnxE1SFyV7Bmmi3Q91x)A5Lh90PtU5D)WmgLXElWH7cMKWdWjAVn(WSFygWGT3kAO2((RpFAyZIOH4y2Hema346RE7hMEuDSdXAcmDqORpUPS9sfIxQquEz(tV16Ptb5RROSMb525o93LM)okJ5h381HMo5IjNE(SXyvDNJpm7TxF1hE)7VyYp3AXDqE20ztV8NpcbHQExVt6UwkVFN0F16cEQVjJW2qDMcAo)ver3tWap7rlPSKoyI2wk4u1UNLIx76PVcS6BhV9qgjETN(QY6Q5b2w9fVQVc56RaUTyp7b2IEx52a2O9KRNoBs0pp9IlQ1ie9RmiJYfS1Mm0tBFJeIABkQwyy33GqxXRGX0(98QlQb6fMvZ6)TxpD6SEllr7fvpvEZAURAS2tvFV0v1tO911x8ENAjlR(2uT6rFCgsn1rZGD0RyVGX0jDTRVT)DABDG2q2D20pCZ1tUyiM5(Ew0lq9k03BpfiiOieETpeJxBOlXakTi5vpMdcqwfKg4oghbiBpaq)6BKRJ(QYIip2IOMOUSkVcQrBORjB(wobg3iH)lDzxFHG5zcUQlLWL039t5nsgXEjJbPipE5cz1KQfGbgRdhCDy(g5v1(rgGr(szzBOigbVrGpCvjCPjijvFFFEj9eczyhauVchtlpQu)id1qgGifucNbD5Q)KU3sCvnHGibu9qyeCA2u9FsHtZ23qIz5(yGbU560t8cWEu5ZGUi83xelXf3)2ClXGZyVQjJ86GUP6LCEvSn0jmzVABbT0xIGCJyqOThKTGpVGp3yUiC1RiAHFTEEEwPmerocJija4s6kPRY)Y8wvkSrncZa1I47O)V6BlD3IeIR6n6wAc02SQlap6sNsZ1(B0BxTXVQ7m9jh1DM(1I6s9rDL(qxOpKHLU)TNMJivF9PDmQjb7FWvHji290QNg5MuVxWgZZlLpUbYl9F1QIeSJYwQY1xXc4TerV9zmKC8eKWj1E1T3wc8)mptdhph)aaDiGE09K1DIEZwtvqqltll)Bns0stnTJpt68vL)F5dhWx5ZsqpTeP2rlfW2XbxxchIYHrU0n0TsNLzFilFE8PYhrhvvEdb1gVDVSur6)QjSo3HzP3dYM8zgqwG5Ys(mN4vzaAmpxfJLkEk2WOUStKUET0TaxjBOK7q5TGv)4HBhLsfg)wO0i9ceP1MhWsk85)6RE1Z3Hw88DpUkb)SAvYZ3jvCF(ozZGqtAf(b1rEe(L8nj9gHd1zQ5)z6dtXlOfcAEAwgpT84bJTv6bs(5v5Dwukg4)jSqqttrG4i8rmKB3v98DRGaD94c)lRE(oYizRjHEJfjYXxUkIZkZ70GQwRFznqcZvPEtS85)k1Bs3hJ19QgYS5NVdsT0cMt0dTavF6P0NIrqHJ857(oLm1Z3z5y89p)xvBQxpqnb857(VZT6ViNxjrGgzUiqGLaiVTtIXFMwmAsujw8BQicGmrBsQPwhfVcYuy18qoXBilqYgWlAOxJULuvHWOjQg2DjXFgVGNb1YVQyxsR1)i2a49a1u1MGne0I6npgBIMQTyh6JvRHVh6cjPXsnO1wJu7bjYdSfYYFusMOhqcw0L6AZuqGWhFsAQym80rnwnHWHxMCUK236Sf0d3)TRtUNwxt0F0z72Wj4Q87(E14a4aK8hHhG4y)cPGSK5ifj)9DPKen4Z)xHLaGTroHpMx8P2Bbav457WOy3rAQhoJx3ipH2)xgVDshjYgwl4TRmrXTucEuzLH01YisBCP6dzdQ1V93nMGYaLOM(cjnti9OOaz(f5BAPtPnTWYoATckzJeBOEr2SaUh65Txbdvmu5La3q1AyfXswVJvCyvfEQ1S7hJl2WkhK1bA820EcfTzfkpGQEWkg57KKyHXFHT8XOIK2y0gaBBMeMMkh02kFYxsbC(OYyPfjelAy53tLf9VMHvnw6EY1mgmr)kgjUFLswNQ7C2yPsMA5tB4Ga0vgNKVSnQioDjMSfKh4eom6zM2iyKt4F7R(TP83g8tCKPLVL61UYxheOETQFgMQ33xcmxIeJW9UkTs5pLEOVaiKpLQs3RmJUrYexVuwtZ2SDr)3sLT3hjNpuiJxFZpZj8vvFFOnkBiKQ6pTGV259vqjn792Q0g3CGwd9PJnM6oxp0Dsn7iZ4y4PB9qS1P91N2fDUig85Iu)eO3gRIAsR3iDE7xCqgAFDeR0otYx7otnnFDBWr5V6nEL6CZi8AeK66CkXvIPpNS8n85bkFYD1pIxQ1l4vt2rM)PyMzm3dD01)us8wijFcKVn80p7xQ9kgHPB(CAr(gc1jSwDg8HbdsF)GJgViIUm(beR3zeYKKcQ96htmUU15yeyixzLLy)MtydGxXZYanjldV87E)QNOdUl77LRalphR6hGmvyA7TSofrgUz011e(WZEkkC393Ntf(m9JzgVIgCxwL(a8)CGD5KIfXigPlbZ4so9bpPFK0Ob1DObfEM)(r5cH7iG4NLuwfrnmCBArAL(HxJgsVbgYlI)C8H3YxV6PC8hRI(X8mSGZ1pLB0i6pWiIi)wNC4H8n0tgo9yM((80si4yyQFI4yYzGRLCGpnUyjXEtF(U3MWC2ltlki3oNtkas2RWYX32T(jLJ5VbcFjp(S8moKy090LKZ5lJjFc3W1PZM(Bzv)8ZX9322LL)dpHCE88D)ykLuac3k8wKLtb7OLTCLLlm5JuhR145BkF4ucdxSkbicL7G3al2i0NuAvCtr6Mp1SaSTTcQFy74XW1piqsdyuCpF3Kflsk3RRUocJaR6N(o2otGBGmnAHxSBrIs54Y4Ikgw33DAChsxGLF9JKh3Dtdp1E)cyhkvr(ViMrT)2S4uYf9)zt9ayAjvTeUnBFFH0YXBlI)fA7YRGlsqCy9x)2U2cBz)9Q7VHVI892K1RLDp7pPidYndFqOs9EcM2njz7nYqP32sWJSwy1uy6b6mlXUfgtxNoMaHRHRuGkOErf4kZjA4jCWzNVPeOM2HqWRgGF6AOmdQfiXQX13yyjYj5t7liAwBbwaLH9wYT6HELA2s6dmvUhxTuZ9cP1AY(RttHQIDB10BHJ0C27ZR4iBFpfBpSoXI)0G93IZ(L40VShb3XMQoX0OzxpAcHqoAxMkL8jowmjo(GMXE(dBs)L0bKnqFdcSK0rN6rKo7F5iMSm(HmzhzPciBUmLEMZ3xwWXKkR2CnrwBk0W)LCIeY(p77cXSro13WrzrTuztiPl5(CktSZt3x40XY3qk2B63AN5lPvNsI3Bq8S5V4oJez8T5bQwu1031wsIEtCMubMOZxvcaVXKnA2djczcAYQLJNTJuqWYO2mGaAMVOzarFZawAj3aB6UEROoPXAo8c4sQXZmV8zgJLzB6GISUg4AQv6perGl)SvC1fT1OiTIDwrYdPhdLeXDY2lSSBzjZvzjJ9(Om3C9UndkI5jPanYQcBv3pjMson5hz3Y)p)VjbJff50dYwSKScRZmjU3sYt46lLBTASUAeyQuPqO)3dN9AA7Y)0Kf)9D7BnYnW3tTZAKDfgEsYZBYbyZuOiX0zs4DxzjImc)flXKU34zh47lfET8BVvD(nARQfKTS8KNjjCcdJh5zkzWFmLn5EswE(6AENPbBg0wl)67dVis7yXSfhQNNTlFXbariyui2I2a2PR9tsY4qUEmVyzeFyJZSBBc2xI89MK1BjwKKoKuUnwIIORSJWWY3Kbay3ialCvCi45pNHb9M4f53NVH981ZnQJTHn7h3wl8g4Byk7)7OGcw98Dt)IksFTbnFjjZPMEh4OWDrl7S4I)eIG(htkwMUGW11(nbKvOfxvddcWL8DLqS1sQK(KP0eB4N2L9joRfVhrWsQFdrcc4Rh0mBTqQGWbOib0XwKrbHKEF)Oqu33REjzNF4bJ5Urpvn3REES4KDspno0dCiwrORju22KzLHKFOVluOKbOUVR6IyB73tgspDLHYPmmxD7zEEiOFdtNa8dOD4RoJokQ(skAJWQINIwbZ65fp1kaRZCCbwRaVaOocVDggnLqBhllBQEylcCSdc0pGHnrwHUAfiCD9HBxdttzL0w11a4bWpW3gwKmRpWWMaOoZXhbqb38ct3a0zQbshzJSpAf4eZppZ11030fwqmDGEJLBDZ68fdWzEo0SyBd342c6blr3m3UJg0ZTSTSON9pagSzs960mhhFVaFqTCeogypQBg)WvSnPuEoBZPOFa1wEi0WzONBhoLRPRLra2FUW4UVRL6HWuXPmgLt5bdme1gRpQwM0QyNdXClx3GaS4f2eKtvfCOMtr8y4LZNSkyi8dA6kvb0TbF2XWG((YOU4p0SLSBTJgzGyyMbMD2LoMyzA4zd0JwMbmhU1U0CSDP6y6LWMn7s9hCeBfvUIx6i8itxW9cWlzYKx)o7iV95rg8xbgT4rqDaKtpxlBpa)1x9aHQw9(hE1FMBGNPJJNLVdbD20x)W02Bdn8KS)gka6LqvXWs456jFKt92xJWdZMnKdaNKKqe1nZPNmSRJRHn8wIgAOFux3tJWoaah8dSW63xR87UVgHRdAe(FtO)BsNCVEs97oPUbg(ehjG9twtqAP4mGEJVDxlCykaExAtAbZvwD5jIxGNmCVBVemgsSiORyHJnSaGWO8HRrBthPSLEj49sIfd279el8mrO)W4hmX4Zi6qZcgqSaqG898cSmaYtG0TUzDfl894VjC8n9DGEEqZO1ZqjI6YialkxG6g2mRBwpdLqEnWWM8wq3xIMjTNHsyAZMmvyiCnGKRUzhMy71vh021crh6J1nIdOwe8yj2d37bi2o8xIeE2qBK(A7rZt6sS9cOhNEB4ScqpTK6G(d4vIygqg31jW2bOpgthuy77aTkwz1t68YBaDqkcnyVdTsyyBv)m5VhXoWa0ziDjGXelN9n4niX2PRYfCY7AA5a5jiPim7cFWBCNsuv1Is(f6mwSbQVnnyklmo44cBwqMbUO7dFOMYo0eVpdWcMOfUuv8c6e(oJala8qBGc0bTWOJ)(Es72qfeaTCbtcEmngbwGNjKCGbCyd0YdoEhbwanPeqhha41Y1Ub9GFFVcWsEaf(eGU44Up6bZ95t2IEW8Sava4Q8e0guyDSW8G4TPpa4ybiEwbSCUJLEzbYoyHKoaeY3d8aHJdGeOvnC9lenGh8aOb8UoyaH)e)r9id7fqNXg2(ajVf1UhVBWT2(kpUcRaA4aRPd1UlVdXraiF(WsLjq15na1wmaoabh6vBumaNMhfNIhji7(15Zz4E)cAMc7EAMqY32bJddxqi6cKsCaooaZsynHbgyxQne7bhX90m9zCwgwgc6lrhjEl3x0PTxxci0iCG1xyLfkAa1yx5vJdT6jKh2emf4gPvSfdpIJPgnYaXeARUeAsm20MCgyy4dr1Ul1xKxpyVFrRWDH4ayB22a1Lfc(Xag()6WxmCV3NVILhbgZ1Y3fbl4pc(cpejwarYC5WXmgbFb4ewqXfwa9fKNQ6j1Phmexp4t0bKikVp(JGVWhysnORHfnT(sJrbdb70ccbWqbqSyH4Eok8f2C(97IVaUk8bilyRWZ7yfn9iefG2bWaaFSzBtPWng52hXq656A43hZbqvBXosaf1grh410vW28GznBcUKRVRz)ybOgyr2rnPV3QcyMBDW22ikoBqW479xDiCAgfy4y2G9BtlG2WmOLbCeoPdCcsQ3ySLb060I5Dg8LI(5BkG5u0uNoboITjMriEyj4pPxGJc6lAPgfXHhkjk7UAbK)c4zXwqSmvS9FfOShS3denjHAwq8jp32kl90ceEy35twmHFsl)rrzJWYTCiLaqmDhfLTdG2dLapwoXtmIwaepOieGldkVkEJIYMGragouxcqRTpkTaHzpafbi0DFSjb70sbfY7iCV4halQWCNLVLjCW43slWZdWcqaFqIccQnR((a)gAIFXyc7yZEgcP71uQGL)Z8yTwVx)Er70gDDva7ua8HfD3BTmT97s0EXqtC8G6iewe0H05ow6bgEs2tcfgub0FsAHevKjByGqtqmGwaDfS7d7iEMJzNg8usIhHwArrQ20SE2PXabTm4HWhcPo(JzNoiaGqGrjyXuqX3DusOw298lBcy1yyeuIn(QXGnyVFXLq3u2baqwiorxxHJJhD20hhgS644gQ3VOixVSg6yHWgHPdHhhQuxrUxmJuiuSa49WcgEnvx87HmkIy7bLcA0bW4IKFnGih2kW8Qbba3H6Wyrdp4sEprox4iMs2JaRmeuSyeroheom2du4bwuYLRBwpJIimhyLWc25CruXM1nRxgPeu6sPKJazyHP4OcAwy3vY0MkuwaNeqs5rFnw)vkwmyVFjqmg9sZkzJLIndaH8LXF3ceZbsZQ8UFCgmfavD)aW5benPBWGb9wccgIAWKFcgCgjk9HxnDSPpKOUF39KRLTvGWNQv3qi0Phz19Le1hS377(Hemb8aiOZIZJK8vaQfHiz6azjhdvEXChW)pPmyBcB6UUokJWUdjQ7aOeMUaXeLcB)rs(kc8cGGru3urzZsyUVnRHYuGr3WzGXEopuaIMnfT8XcVnWGsIbN5gqbDBHr1bOGG9CtGhYrO0NBlRqDfYjc6QX6r6ZT7ki3qUarddeSwU9J5Gkc12ww8tdcfYAl4eW1waDHzOmLrpLa7bVLCoIySbgoewOlVr1ZQWcyOGOOawEvl4oWBjO6Wig8orjpNtsynigaeN(uppYJztxDRX)q5nbOFHwJTP868yRD6HrZhUUHiHkN4oTmub7IiawSDjFsagDlq1GCJEt54cXaOsAHtlJxqaclge2oIEhOO9B)fElgicmwGfNixR6UgOdBHaz5dN1yd7BWzqtLPoW28O0HHX0d81M04OFy2O856aqgWPef9bNRzvFbJf4DDa3Jq8z3CsFI6WLaBfQpoatlLKvJMsGZWsOTfZDBFCAJmsvQNd6E5mXe(uGIlc9x4BFKHYdPqtbTpG)pbfvBlPWadkBk2epfR5boInsRWgQiWIkIbWTLuiIj3W2Ip(QHYsgu3bm5abDERqYXRTAtavCxGebmeGWSD3x2hiO9Pustgl8DmQ76m1JvLttHiYWf0j6Xqcrz2sjXdUCbN30JewnDC2tshKAc8IpiLabPOLscPoJWhrWNeg1wIREn8EhkR60zirBWwbTkazY0W0pGIdt40pNPKReVasMZ232rMLcT(Lbc5XLIEWJYXBZr)g0pJXdid0w6YAOdc0VB4robY41Tq0D0Pz81Died3799fbzAx8pigyARYDK)qExHNdBiKjmnb)myeyxEKqSnIUWoGQ2v2JDieUa9ghJHnP(7pcSlpi1AbaC(Gt5OohLbGDblPuITTaCcWASdoc8uYRt9oq5sLv1ODB4VULv31rkz2RJt3eTkjBB9BAsN0v4KBU56Zp5d3mnkC6ftFZnr38HBU66ZNCbvCwdVKQGDxD5jtW7F(Lt5lArvrM6lRAzzoPEENFB4PNho5KlMgD1m(24h9(jZMEb1RWBUE6KlNwxi5o78RXB9Hz0NnD2BUIVW6rNGg9dNE1pnl69VBs40WUFQUQ0DYKlU4QzDxON9HlUan4IPyJ8tNpdJXyJm)LR(KpC9eE0LTnIltbrxo5hoF2B5XtpxNp7SR6otuPTQsEnxlBvc1NtIyZjs9Cs8yUSi2c2YzxD9BNwpeTMt668h9Hz0V4b(QFC61yND6KBMe9ttUEgVuOhbOWRE)nNF1Sqj1m6Q3pD20tPEOU)(rXB2KVJk(hKKX7opet1plBB7PT5l482mSH2NMsWL0nODtPsqP5Rq5ExbjzBv3Zr6czX3SZ23RLMVK6fnLMUKVSnWOkHRqqHltYsWiRUie38MRorErhQlBgDgw(lgBwvGUTpu)PRQtOGi9Hcl(NM8pf8pnufi86l2knuy)hTBtAvzR7sI66Ws1jmvfHs(DOlFX8PBqRAxkR)MYViS7DLY7CrLj3JX7kI5B8CA5c(joIkybjXC9wMkoufTRbvLYVbxskEGVRTYLLKuCDC6YZs3SCVlX()YMXtADNq3RgV(V095VFZ2L8Zd2VxZ2e(Xs73rcPLX)riSy)71Ss1LaQKLlFsiPheq5DsdOYnBRVt651k91FLhm2tpiVc1Fn3REib55sEFU03lFTrx5xP8f72wv2BB)iaZqLGVqUyKTzd)fQWKFwxJiP3FJ871)Qwd3wYQ5EJvZam9IZilR6sSCLUUjWvqc93yiHkkZY4NUn0WIkaPXlw1F9LKTiNUF1XyKvwPRjPu7LfcnPXtzT3Bdv)iJFqwOwulyvzzmzHS6b2Ucf0Dvtxc0flhPwCOV)MlYZZOQqPAX07L8LUemq53vhLYIqaxtwlLL7rzXsrwrx7wRw19wxx)KfesnVTz3W30(EloMKSICwmtx1uUpTOuwmwKxBtPxnUgxs3aFUo0FcxCnizU6I4cw73N(qDLxFnx(yOkLYU5r1LKuz1Ph(O)LCQeahsv11562WnjpIwshOQLq3InDX0LFe95bHQyTLxuxZC7)DgxQ8lgh(JKLvcgrbxLwOfz3f4GFBi9hRVpT01T()yqM1qF(kiZMJqM)Jvflvx1))QiZDOyZBrXM3qHMxt8Q(vYx(vlhtpMoiyslpqmTd8QjWZO0IXKtejNRHJTRLRNHNVBn5KUblFDep7)nJ45qPGK0)fEUMcVM6dnDQ92U0fPXJscK85WtkDsj8XHoczddtpHLMGVIEmBDcewgMowq(1PjDCFfeyN)TIatLVlddHjDwQwuTsKR8279M)lMOwvFBk0yLsb4oOP04lTTZBfcIL9DW3bcGgwunUHRNC(PDCpZUDHN4xcOb7XUUKZtRm(aV79(YkIeSgcZOct((o2UO4vD7T)F)d

**Comment by Fujiwarahub** [comment]
The encounter timer is indeed working. I thought that it was inteded to be displayed everytime I entered any kind of combat and not just for boss fights. I'm really sorry for wasting anyone's time.
