### ISSUE TITLE
Details! windows don't load with DetailsTBC.2.5.1.0015.144

### ISSUE THREAD

**Issue by oezi** [Tercioo/Details-Damage-Meter#215]
**Game and Details! version**
DETAILS! VERSION: BCC8514
GAME VERSION: 2.5.1

**Describe the bug**
After the latest Update (DetailsTBC.2.5.1.0015.144, installed on 25.05.2021 at 21:30 CEST), Details! windows don't load, instead the following Error-Message is shown:

```
Failed to load a Details! window.
/reload or reboot the game client may fix the problem.
If the problem persists, try /details reinstall
Error: Interface\Addons\Details\frames\window_main.lua:4018. CreateFrame(): Couldn't find the inherited node "DFNamePlateFullBorderTemplate, BackdropTemplate"
```

**Screenshot**
![image](https://user-images.githubusercontent.com/6586929/119566411-6797f000-bdab-11eb-96e1-8b1981e8919c.png)

**Additional info**
The suggested fixes didn't work.

**Comment by Tercioo** [comment]
Sound silly, but could you close and reopen the game?

------ Original Message ------
From: "Udo Gerdes" ***@***.***>
To: "Tercioo/Details-Damage-Meter" 
***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 25-May-21 5:50:22 PM
Subject: [Tercioo/Details-Damage-Meter] Details! windows don't load with 
DetailsTBC.2.5.1.0015.144 (#215)
