### ISSUE TITLE
TBC Classic - LUA error on entering combat

### ISSUE THREAD

**Issue by jmallette** [Tercioo/Details-Damage-Meter#224]
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**
- [x] Confirmed occurs when only addon enabled.

**Game and Details! version**
Use /details to grab these two.
Details! version: BCC20
Game version: 2.5.1

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
Enter combat, happens every time as far as I can tell.

- Result (what happens when you follow the steps above):
LUA error as seen below.

- Expected (what you think the expected behavior would be when following the steps):
No LUA error. 

- When the bug started (a date, wow path release, details update, etc)?
Latest update a couple days ago.

- Additional information:

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*
[16:26:14] Details!: error on scheduler:  [string "@Interface\AddOns\Details\functions\schedules.lua"]:32: in function `NewTicker'
[string "@Interface\AddOns\Details\core\gears.lua"]:496: in function `RefreshUpdater'
[string "@Interface\AddOns\Details\core\gears.lua"]:512: in function `SetWindowUpdateSpeed'
[string "@Interface\AddOns\Details\core\gears.lua"]:564: in function `CheckForPerformanceProfile'
[string "@Interface\AddOns\Details\core\parser.lua"]:4645: in function <Interface\AddOns\Details\core\parser.lua:4521>
  Interface\AddOns\Details\classes\class_custom.lua:728: bad argument #1 to '_unpack' (table expected, got nil) 

**Screenshots**
Post images of the bug if necessary.

**Combat Log**
Include a link to a combatlog file if the error is about not detecting a skill, usable item or item proc.
The log can be as simple as hitting a mob with white damage and using the item/skill.

N/A
**Other Information**
I completely renamed my details saved variables, rebuilt my profile and it is still occurring.

**Comment by Tercioo** [comment]
Just to confirm, do you have a scripted display like Dynamic Overall 
Damage shown?

------ Original Message ------
From: "jmallette" ***@***.***>
To: "Tercioo/Details-Damage-Meter" 
***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 14-Jun-21 6:32:34 PM
Subject: [Tercioo/Details-Damage-Meter] TBC Classic - LUA error on 
entering combat (#224)

**Comment by jmallette** [comment]
@Tercioo Yes, I have two windows. One for current damage done and one for dynamic overall, that's correct.

**Comment by Tercioo** [comment]
Good, do you want to try a fix?
You just need to open the file 
Interface/Addons/Details/Classes/class_custom.lua and replace this
if (self.spec or self.my_actor.spec) then
by this:
if ((self.spec and self.spec ~= 0) or (self.my_actor.spec and 
self.my_actor.spec ~= 0)) then

Save the file and /reload

------ Original Message ------
From: "jmallette" ***@***.***>
To: "Tercioo/Details-Damage-Meter" 
***@***.***>
Cc: "Tercio Jose" ***@***.***>; "Mention" 
***@***.***>
Sent: 14-Jun-21 6:41:13 PM
Subject: Re: [Tercioo/Details-Damage-Meter] TBC Classic - LUA error on 
entering combat (#224)

**Comment by jmallette** [comment]
Seems to be working great with the fix. Thanks!
