### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by EternalPaw** [Tercioo/Details-Damage-Meter#24]
When I open the Deatils Option Menu I always get these 2 errors:

Message: AceLocale-3.0: Details: Missing entry for 'STRING_OPTIONS_TEXT_LTRANSLIT'
Time: Tue Nov 12 22:38:22 2019
Count: 1
Stack: AceLocale-3.0: Details: Missing entry for 'STRING_OPTIONS_TEXT_LTRANSLIT'
...AddOnSkins\Libs\Ace3\AceLocale-3.0\AceLocale-3.0.lua:31: in function <...AddOnSkins\Libs\Ace3\AceLocale-3.0\AceLocale-3.0.lua:29>
Interface\AddOns\Details\gumps\janela_options.lua:6781: in function `?'
Interface\AddOns\Details\gumps\janela_options.lua:11290: in function `OpenOptionsWindow'
Interface\AddOns\Details\gumps\janela_principal.lua:9420: in function <Interface\AddOns\Details\gumps\janela_principal.lua:9410>
[C]: in function `pcall'
Interface\AddOns\Details\Libs\DF\fw.lua:2667: in function `CoreDispatch'
Interface\AddOns\Details\Libs\DF\button.lua:887: in function <Interface\AddOns\Details\Libs\DF\button.lua:800>

Locals: <none>

Message: AceLocale-3.0: Details: Missing entry for 'STRING_OPTIONS_TEXT_LTRANSLIT_DESC'
Time: Tue Nov 12 22:38:22 2019
Count: 1
Stack: AceLocale-3.0: Details: Missing entry for 'STRING_OPTIONS_TEXT_LTRANSLIT_DESC'
...AddOnSkins\Libs\Ace3\AceLocale-3.0\AceLocale-3.0.lua:31: in function <...AddOnSkins\Libs\Ace3\AceLocale-3.0\AceLocale-3.0.lua:29>
Interface\AddOns\Details\gumps\janela_options.lua:6799: in function `?'
Interface\AddOns\Details\gumps\janela_options.lua:11290: in function `OpenOptionsWindow'
Interface\AddOns\Details\gumps\janela_principal.lua:9420: in function <Interface\AddOns\Details\gumps\janela_principal.lua:9410>
[C]: in function `pcall'
Interface\AddOns\Details\Libs\DF\fw.lua:2667: in function `CoreDispatch'
Interface\AddOns\Details\Libs\DF\button.lua:887: in function <Interface\AddOns\Details\Libs\DF\button.lua:800>

Locals: <none>

I tried it without any addons at all but the error is still popping up and I can't import any profiles

**Comment by Tercioo** [comment]
fixed, thanks.
