### ISSUE TITLE
1.14 - Addon not loading

### ISSUE THREAD

**Issue by Slivo-fr** [Tercioo/Details-Damage-Meter#246]
Hi,

1.14 brought most (all?) of the BC changes to classic ERA, the addon does not load at all.

Thanks for your work

**Comment by zdeyn** [comment]
I had a look at the codebase, and the errors mostly relate to the API changes regarding backdrops. I can't offer much more than this, as my experience with hacking in fixes to stuff for 1.14 doesn't extend to this level of template inheritance

**Comment by Tercioo** [comment]
this issues has been fixed, thanks!

**Comment by Slivo-fr** [comment]
Thanks :)
