### ISSUE TITLE
[BUG]Death Log Overkill Amount

### ISSUE THREAD

**Issue by gwtwind** [Tercioo/Details-Damage-Meter#255]
**Game and Details! version**
BCC29
2. 5. 2

**Describe the bug**
At death log tooltip, damage taken amount is incorrect when overkill included.
e.g. 10012 damage taken and 10065 overkill but it shows like below
-0.0s Melee (Magtheridon) --53 (10.1K overkill)

Error is `class_utility.lua #252`
`amount = amount - overkill`
this line is incorrect
because parser.lua already calculated amount as total damage - overkill damage.

**Comment by Tercioo** [comment]
Thank you! that line is being removed for next version.
