### ISSUE TITLE
attempt to perform arithmetic on field 'total_lines' (a nil value)

### ISSUE THREAD

**Issue by UTGuy** [Tercioo/Details-Damage-Meter#27]
Date: 2019-11-21 11:21:00
ID: 1
Error occured in: Global
Count: 1
Message: ...terface\AddOns\Details_Streamer\Details_Streamer.lua line 534:
   attempt to perform arithmetic on field 'total_lines' (a nil value)
Debug:
   (tail call): ?
   ...terface\AddOns\Details_Streamer\Details_Streamer.lua:534: NewText()
   ...terface\AddOns\Details_Streamer\Details_Streamer.lua:927: CastStart()
   ...terface\AddOns\Details_Streamer\Details_Streamer.lua:1161:
      ...terface\AddOns\Details_Streamer\Details_Streamer.lua:1134
   ...terface\AddOns\Details_Streamer\Details_Streamer.lua:50:
      ...terface\AddOns\Details_Streamer\Details_Streamer.lua:49
   ...terface\AddOns\Details_Streamer\Details_Streamer.lua:54:
      ...terface\AddOns\Details_Streamer\Details_Streamer.lua:53
   [C]: ?
   ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:342:
      ...ils\Libs\LibClassicCasterino\LibClassicCasterino.lua:340
   (tail call): ?
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.3.4
  AtlasLootClassicData, vv1.3.4
  AtlasLootClassicDungeonsAndRaids, vv1.3.4
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BuffwatchClassic, v1.11
  DBMCore, v1.13.18
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Dismounter, v1.2.1
  Dominos, v8.2.30
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.5
  Fizzle, v80205-1
  GatherMate2, v1.45.5
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixMaps, v1.13.36
  Masque, v8.2.7-Classic
  Peddler, v
  Plater, v
  Questie, v5.2.1
  RecipeRadarClassic, v1.0.0.23
  SexyMap, vv3-classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TradeSkillMaster, vv4.8.20
  VuhDo, v3.108-classic
  VuhDoOptions, v3.108-classic
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=5e7)

**Comment by UTGuy** [comment]
![image](https://user-images.githubusercontent.com/1872858/69361551-b9ae0180-0c5a-11ea-8963-ef21e0ea6cac.png)

**Comment by Tercioo** [comment]
too old version, detials is in .181 now.

**Comment by UTGuy** [comment]
Installed new version... will update if I see it again
