### ISSUE TITLE
Details-Damage-Meter/core/util.lua Incorrect translation

### ISSUE THREAD

**Issue by maioro** [Tercioo/Details-Damage-Meter#281]
core/util.lua
line 388 390 397 
천 （Korea）It should be  = 千 （Schinese or Tchinese）
Just like lines 368 and 370 or Displayed below
------------------------------------------------------------------------------------------
			if (locale == "kr") then
				symbol_1K, symbol_10K, symbol_1B = "천", "만", "억"
			elseif (locale == "cn") then
				symbol_1K, symbol_10K, symbol_1B = "千", "万", "亿"
			elseif (locale == "tw") then
				symbol_1K, symbol_10K, symbol_1B = "千", "萬", "億"
			end
		end
		
		if (not symbol_1K) then
			--> if a english client is trying to use east asian numeral system and there is no override, let's just use the chinese as default.
			--> if the user is from kr or tw and want to use english client,  an override must be used.
			symbol_1K, symbol_10K, symbol_1B = "千", "万", "亿"
------------------------------------------------------------------------------------------

**Comment by Tercioo** [comment]
Thanks!
