### ISSUE TITLE
gears.lua line 2310:    attempt to call global 'GetNumTalentTabs' (a nil value)

### ISSUE THREAD

**Issue by ghodhereek** [Tercioo/Details-Damage-Meter#29]
Issue: Error shows up right on the start of the game.

Date: 2019-11-25 13:44:26
ID: 12
Error occured in: Global
Count: 1
Message: ..\AddOns\Details\core\gears.lua line 2310:
   attempt to call global 'GetNumTalentTabs' (a nil value)
Debug:
   Details\core\gears.lua:2310:
      Details\core\gears.lua:2288
   ..\SharedXML\C_TimerAugment.lua:16:
      ..\SharedXML\C_TimerAugment.lua:14
Locals:
self = <table> {
 _callback = <function> defined @Interface\SharedXML\C_TimerAugment.lua:14
 _remainingIterations = 1
 _cancelled = true
}
targetPlayer = nil
(*temporary) = nil
(*temporary) = "attempt to call global 'GetNumTalentTabs' (a nil value)"
talentWatchClassic = <unnamed> {
 0 = <userdata>
 cooldown = 1574718271
}
_detalhes = <table> {
 SetBarSpecIconSettings = <function> defined @Interface\AddOns\Details\gumps\janela_principal.lua:4288
 APITopics = <table> {
 }
 InitializeRunCodeWindow = <function> defined @Interface\AddOns\Details\core\windows.lua:4496
 EntrarEmCombate = <function> defined @Interface\AddOns\Details\core\control.lua:366
 hex = <function> defined @Interface\AddOns\Details\core\util.lua:687
 BuildSpellList = <function> defined @Interface\AddOns\Details\functions\spellcache.lua:315
 opened_windows = 2
 RefreshAttributeTextSize = <function> defined @Interface\AddOns\Details\gumps\janela_principal.lua:7552
 PotionList = <table> {
 }
 EndRefresh = <function> defined @Interface\AddOns\Details\core\control.lua:1744
 FechaJanelaInfo = <function> defined @Interface\AddOns\Details\gumps\janela_info.lua:399
 GetMode = <function> defined @Interface\AddOns\Details\classes\classe_instancia.lua:148
 SetMode = <function> defined @Interface\AddOns\Details\classes\classe_instancia.lua:2706
 RestoreState_CurrentMythicDungeonRun = <function> defined @Interface\AddOns\Details\functions\profiles.lua:1487
 APIVersion = 140
 IsPluginEnabled = <function> defined @Interface\AddOns\Details\core\plugins.lua:58
 StopTalentLoadingAnimation = <function> defined @Interface\AddOns\Details\core\gears.lua:2630
 ImportProfile = <function> defined @Interface\AddOns\Details\functions\profiles.lua:1638
 show_totalhitdamage_on_overkill = false
 SetNickname = <function> defined @Interface\AddOns\Details\Libs\NickTag-1.0\NickTag-1.0.lua:495
 color_by_arena_team = true
 SortKeyGroupHeal = <function> defined @Interface\AddOns\Details\classes\classe_heal.lua:125
 SortKeyGroup = <function> defined @Interface\AddOns\Details\classes\classe_damage.lua:133
 IsInEncounter = <function> defined @Interface\AddOns\Details\core\parser.lua:5265
 Check_ZONE_CHANGED_NEW_AREA = <function> defined @Interface\AddOns\Details\core\parser.lua:4023
 plugin_window_pos = <table> {
 }
 gump = <table> {
 }
 CaptureRefresh = <function> defined @Interface\AddOns\Details\core\parser.lua:3677
 NewModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 InstancesToStoreData = <table> {
 }
 name_space_info = <function> defined @Interface\AddOns\Details\core\util.lua:1385
 ShowDelayMsg = <function> defined @Interface\AddOns\Details\boot.lua:721
 Resize = <function> defined @Interface\AddOns\Details\classes\classe_instancia.lua:1867
 GetEncounterActorsName = <function> defined @Interface\AddOns\Details\functions\boss.lua:306
 RequestCloudData = <function> defined @Interface\AddOns\Details\core\network.lua:743
 RestauraJanela = <function> defined @Interface\AddOns\Details\classes\classe_instancia.lua:1429
 default_skin_to_use = "Minimalistic"
 GetOpenedWindowsAmount = <function> defined @Interface\AddOns\Details\classes\classe_instancia.lua:256
 GetInstanceGroup = <function> defined @Interface\AddOns\Details\gumps\janela_principal.lua:8013
 deadlog_events = 32
 Dump = <function> defined @Interface\AddOns\Details\core\windows.lua:7143
 OpenNewsWindow = <function> defined @Interface\AddOns\Details\gumps\janela_news.lua:9
 last_instance_id = 1763
 _detalhes_props = <table> {
 }
 atributo_energy = <table> {
 }
 UnitDamageOnUnit = <function> defined @Interface\AddOns\Details\functions\api2.lua:1123
 name_space_generic = <function> defined @Interface\AddOns\Details\core\util.lua:1395
 storage = <table> {
 }
 AddOnStartTime = 184601.290000
 ContainerSortEnemies = <function> defined @Interface\AddOns\Details\classes\classe_damage.lua:250
 ToolBar = <table> {
 }
 FixToolbarMenu = <function> defined @Interface\AddOns\Details\classes\classe_instancia.lua:1422
 UseWestNumericalSystem = <function> defined @Interface\AddOns\Details\core\util.lua:28

**Comment by Tercioo** [comment]
/details to grab game and details versions.

**Comment by ghodhereek** [comment]
Details: C181
Game: v1.13.2

**Comment by Tercioo** [comment]
Nov 25: tested with the same version, character level 23 it's running okay.
Let's see if this happens to more people on this week.

**Comment by StuartLaird** [comment]
Getting this in live/retail this morning after updating lots of things via the Twitch app.
Details: C181
Game: 1.13.12
I know it says Game 1.13.12, but I am sitting in Dazar'alor on a DK.

**Comment by Tercioo** [comment]
Update again from Twichapp many reports on discord telling twitch sent wrong versions again.

**Comment by StuartLaird** [comment]
Looks like it.
Restarting the TwitchApp is not giving me any more updates, but a few addons are now at game version 1.13.2

**Comment by altere987** [comment]
Comes up at character login for me as well but I get 3 lua errors initially and more as playing.
C184
v1.13.2

Message: ...ace\AddOns\Details_TinyThreat\Details_TinyThreat.lua:51: Cannot find a library instance of "ThreatClassic-1.0".
Time: Tue Dec 10 18:35:12 2019
Count: 1
Stack: ...ace\AddOns\Details_TinyThreat\Details_TinyThreat.lua:51: Cannot find a library instance of "ThreatClassic-1.0".
[C]: in function `error'
Interface\AddOns\AAP-Core\lib\LibStub\LibStub.lua:23: in function `GetLibrary'
...ace\AddOns\Details_TinyThreat\Details_TinyThreat.lua:51: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "ThreatClassic-1.0"."

-------------------------------------------------------
Message: (null)
Time: Tue Dec 10 18:35:15 2019
Count: 3

-------------------------------------------------------
Message: Interface\AddOns\Details\core\gears.lua:2310: attempt to call global 'GetNumTalentTabs' (a nil value)
Time: Tue Dec 10 18:35:26 2019
Count: 1
Stack: Interface\AddOns\Details\core\gears.lua:2310: attempt to call global 'GetNumTalentTabs' (a nil value)
[C]: in function `GetNumTalentTabs'
Interface\AddOns\Details\core\gears.lua:2310: in function <Interface\AddOns\Details\core\gears.lua:2288>
Interface\SharedXML\C_TimerAugment.lua:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals:

**Comment by Tercioo** [comment]
yeah, that happens when details for retail is installed somehow
try to delete all details folders and do a clean install using the "Details! Damage Meter for Classic WoW"

------ Original Message ------

**Comment by Tercioo** [comment]
Any news on this issue, all good now?

**Comment by altere987** [comment]
I just did this yesterday but did not use the classic version. Just a
complete removal and re-installed which resolved all errors.
