### ISSUE TITLE
DetailsTBC.2.5.4.0033.146a LibOpenRaid error

### ISSUE THREAD

**Issue by Road-block** [Tercioo/Details-Damage-Meter#301]
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**

**Game and Details! version**
Use /details to grab these two.

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):

- Result (what happens when you follow the steps above):

- Expected (what you think the expected behavior would be when following the steps):

- When the bug started (a date, wow path release, details update, etc)?

- Additional information:

**Lua Error**
```
openRaidLib: error on scheduler: updatePlayerData_Schedule [string "@Interface\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:257: in function `NewUniqueTimer'
[string "@Interface\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:661: in function `?'
[string "@Interface\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:425: in function `TriggerEvent'
[string "@Interface\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:516: in function `?'
[string "@Interface\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:611: in function <...face\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua:610>
 ...face\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua:846: attempt to call global 'GetSpecializationInfoByID' (a nil value)
```

**Screenshots**
Post images of the bug if necessary.

**Combat Log**
Include a link to a combatlog file if the error is about not detecting a skill, usable item or item proc.
The log can be as simple as hitting a mob with white damage and using the item/skill.

**Other Information**
enUS BCC WoW Client, Details version: 2.5.4.0033.146a

**Comment by Road-block** [comment]
Followup error. Same version.
```
error on scheduler: leaveCombat_Schedule [string "@Interface\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:257: in function `NewUniqueTimer'
[string "@Interface\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:1071: in function `?'
[string "@Interface\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:425: in function `TriggerEvent'
[string "@Interface\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:543: in function `?'
[string "@Interface\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:611: in function <...face\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua:610>
 ...erface\AddOns\Details\Libs\LibOpenRaid\Functions.lua:41: attempt to get length of local 'table' (a number value)
```

**Comment by Flamanis** [comment]
Best place to report bugs is the Discord Server. This has already been fixed.

**Comment by Road-block** [comment]
I realized few days ago, I probably should have closed it myself.

That said discord is not a development platform and I'm not using my mobile as a password anywhere ...
