### ISSUE TITLE
Error with Details and Plater

### ISSUE THREAD

**Issue by reconops** [Tercioo/Details-Damage-Meter#313]
11x Details\Libs\DF\fw.lua:158: Usage: GetSpecializationInfo(specIndex[, isInspect[, isPet[, inspectTarget[, sex]]]])
[string "@Details\Libs\DF\fw.lua"]:158: in function <Details\Libs\DF\fw.lua:152>
[string "@Details\Libs\DF\panel.lua"]:6440: in function `PassLoadFilters'
[string "@Plater\Plater-Plater-v351-Retail.lua"]:11180: in function `CompileHook'
[string "@Plater\Plater-Plater-v351-Retail.lua"]:10551: in function `CompileAllScripts'
[string "@Plater\Plater-Plater-v351-Retail.lua"]:4269: in function <Plater\Plater.lua:4189>
[string "=[C]"]: in function `xpcall'
[string "@Details\Libs\DF\addon.lua"]:125: in function <Details\Libs\DF\addon.lua:85>
[string "=[C]"]: ?
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...ceDetails\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <...ceDetails\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by Flamanis** [comment]
Been fixed for a few weeks now.
