### ISSUE TITLE
Not resetting on new dungeon group

### ISSUE THREAD

**Issue by Anothersignup** [Tercioo/Details-Damage-Meter#315]
**Game and Details! version**
DetailsRetail.9.2.5.9824.146

**Describe the bug**
Options > Display > Erase Data > Auto.

- Result (what happens when you follow the steps above):
When I join an LFG the previous overall data is sometime saved to the next dungeon (with new group).

- Expected (what you think the expected behavior would be when following the steps):
That there would be no bars.

- When the bug started (a date, wow path release, details update, etc)?
With latest version, and recently before the latest version.

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*

**Comment by Flamanis** [comment]
You're in a regular dungeon, not a mythic plus. There is no option for new normal/heroic dungeon.

**Comment by Tercioo** [comment]
it clears when the m+ start
make sure /details options > display > Clear on Start Mythic+ is 
enabled.

/details reinstall is always an options as well.

------ Original Message ------
From: "Zindex" ***@***.***>
To: "Tercioo/Details-Damage-Meter" 
***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 10-Jun-22 9:30:00 PM
Subject: [Tercioo/Details-Damage-Meter] Not resetting on new dungeon 
group (Issue #315)
