### ISSUE TITLE
[Classic] Details block entering Battleground

### ISSUE THREAD

**Issue by shkabo** [Tercioo/Details-Damage-Meter#32]
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**

**Game and Details! version**
Use /details to grab these two.
Details!: DETAILS! VERSION: C184 
Details!: GAME VERSION: v1.13.2 

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
Que for battle ground
 BG Que pops up
 Click `Enter Battleground`
 Error happens, can't enter BG
- Result (what happens when you follow the steps above):
Can't enter BG, error happens

- Expected (what you think the expected behavior would be when following the steps):
Enter BG, no errors

- When the bug started (a date, wow path release, details update, etc)?
After the latest patch with BG's released

- Additional information:

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*
```
9x [ADDON_ACTION_FORBIDDEN] AddOn 'Details' tried to call the protected function 'AcceptBattlefieldPort()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `AcceptBattlefieldPort'
FrameXML\StaticPopup.lua:689: in function `OnAccept'
FrameXML\StaticPopup.lua:5003: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
```

**Screenshots**
Post images of the bug if necessary.

**Combat Log**
Include a link to a combatlog file if the error is about not detecting a skill, usable item or item proc.
The log can be as simple as hitting a mob with white damage and using the item/skill.

**Other Information**
If necessary, add more info here.

**Comment by olvega** [comment]
Can not click enter BG button through BG popup with Details! enabled,
it works when Details! is disabled.

**Comment by Desik** [comment]
As a workaround, just click the icon on the minimap to enter or leave the bg.

**Comment by Tercioo** [comment]
Latest version added a workaround, you may test and report if it's working, thank you!

**Comment by shkabo** [comment]
@Tercioo now button works, but I found some other error in the bg upon entering
```
Date: 2019-12-17 19:45:26
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Details\core\parser.lua line 1701:
   attempt to perform arithmetic on field 'total' (a nil value)
Debug:
   Details\core\parser.lua:1701:
      Details\core\parser.lua:1537
   (tail call): ?
Locals:
self = nil
token = "SPELL_HEAL"
time = 1576608326.331000
who_serial = "Player-4701-00AE724F"
who_name = "Hatecorelulz-Mograine"
who_flags = 1300
alvo_serial = "Player-4749-01672CDF"
alvo_name = "Foolsbane-Earthshaker"
alvo_flags = 1300
alvo_flags2 = 0
spellid = "Greater Heal"
spellname = "Greater Heal"
spelltype = 2
amount = 2280
overhealing = 0
absorbed = 0
critical = false
is_shield = nil
cura_efetiva = 2280
este_jogador = <table> {
 flag_original = 1300
 totalabsorb = 0.004430
 last_hps = 0
 healing_from = <table> {
 }
 timeMachine = 1
 targets = <table> {
 }
 iniciar_hps = true
 pets = <table> {
 }
 totalover_without_pet = 0.004430
 heal_enemy_amt = 0
 healing_taken = 0.004430
 totalover = 0.004430
 total_without_pet = 0.004430
 start_time = 1576608326
 classe = "Priest"
 serial = "Player-4701-00AE724F"
 targets_overheal = <table> {
 }
 targets_absorbs = <table> {
 }
 nome = "Hatecorelulz-Mograine"
 spells = <table> {
 }
 grupo = true
 displayName = "Hatecorelulz"
 heal_enemy = <table> {
 }
 last_event = 1576608326
 custom = 0
 tipo = 2
 on_hold = false
 totaldenied = 0.004430
 delay = 0
 pvp = true
}
meu_dono = nil
jogador_alvo = <table> {
 flag_original = 1300
 totalabsorb = 0.003900
 last_hps = 0
 healing_from = <table> {
 }
 targets = <table> {
 }
 iniciar_hps = false
 pets = <table> {
 }
 totalover_without_pet = 0.003900
 heal_enemy_amt = 0
 healing_taken = 0.003900
 totalover = 0.003900
 total_without_pet = 0.003900
 start_time = 0
 classe = "Warlock"
 serial = "Player-4749-01672CDF"
 targets_overheal = <table> {
 }
 targets_absorbs = <table> {
 }
 nome = "Foolsbane-Earthshaker"
 spells = <table> {
 }
 grupo = true
 displayName = "Foolsbane"
 heal_enemy = <table> {
 }
 last_event = 0
 custom = 0
 tipo = 2
 on_hold = false
 totaldenied = 0.003900
 delay = 0
 pvp = true
}
alvo_dono = nil
(*temporary) = nil
(*temporary) = 2280
(*temporary) = true
(*temporary) = <function> defined @Interface\AddOns\Details\core\timemachine.lua:122
(*temporary) = <table> {
 flag_original = 1300
 totalabsorb = 0.004430
 last_hps = 0
 healing_from = <table> {
 }
 timeMachine = 1
 targets = <table> {
 }
 iniciar_hps = true
 pets = <table> {
 }
 totalover_without_pet = 0.004430
 heal_enemy_amt = 0
 healing_taken = 0.004430
 totalover = 0.004430
 total_without_pet = 0.004430
 start_time = 1576608326
 classe = "Priest"
 serial = "Player-4701-00AE724F"
 targets_overheal = <table> {
 }
 targets_absorbs = <table> {
 }
 nome = "Hatecorelulz-Mograine"
 spells = <table> {
 }
 grupo = true
 displayName = "Hatecorelulz"
 heal_enemy = <table> {
 }
 last_event = 1576608326
 custom = 0
 tipo = 2
 on_hold = false
 totaldenied = 0.004430
 delay = 0
 pvp = true
}
(*temporary) = <table> {
 1 = <table> {
 }
}
(*temporary) = 1
(*temporary) = <table> {
 1 = <table> {
 }
}
(*temporary) = <table> {
 flag_original = 1300
 totalabsorb = 0.004430
 last_hps = 0
 healing_from = <table> {
 }
 timeMachine = 1
 targets = <table> {
 }
 iniciar_hps = true
 pets = <table> {
 }
 totalover_without_pet = 0.004430
 heal_enemy_amt = 0
 healing_taken = 0.004430
 totalover = 0.004430
 total_without_pet = 0.004430
 start_time = 1576608326
 classe = "Priest"
 serial = "Player-4701-00AE724F"
 targets_overheal = <table> {
 }
 targets_absorbs = <table> {
 }
 nome = "Hatecorelulz-Mograine"
 spells = <table> {
 }
 grupo = true
 displayName = "Hatecorelulz"
 heal_enemy = <table> {
 }
 last_event = 1576608326
 custom = 0
 tipo = 2
 on_hold = false
 totaldenied = 0.004430
 delay = 0
 pvp = true
}
(*temporary) = <table> {
}
(*temporary) = "Foolsbane-Earthshaker"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field 'total' (a nil value)"
_in_combat = true
_bit_band = <function> defined =[C]:-1
OBJECT_TYPE_PETS = 12288
SPELLID_SHAMAN_SLT = 98021
parser = <table> {
 WipeSourceCache = <function> defined @Interface\AddOns\Details\core\parser.lua:3646
 swing = <function> defined @Interface\AddOns\Details\core\parser.lua:306
 buff = <function> defined @Interface\AddOns\Details\core\parser.lua:1825
 energize = <function> defined @Interface\AddOns\Details
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AddOnSkins, v4.39
  AimedShotCastbarClassic, v1.0
  AlreadyKnown, v1.22
  AtlasLootClassic, vv1.4.3
  AtlasLootClassicData, vv1.4.3
  AtlasLootClassicDungeonsAndRaids, vv1.4.3
  AtlasLootClassicMaps, vv1.0.0
  Auctionator, v8.1.0
  BagBrother, v
  Bagnon, v8.2.16
  BigDebuffs, vv8.5
  CharacterStatsClassic, v2.8.1
  ClassicAuraDurations, v
  ClassicCastbars, vv1.2.0-hotfix
  ClassicCastbarsOptions, v
  Cleanup, v
  DBMCore, v1.13.24
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  ElvUI, v1.19
  ElvUIGennUI, v1.05
  EZJunk, v1.0.1
  FarmLog, vv1.19
  FiveSecondRule, v1.15
  Focused, v1.0.16
  GatherMate2, v1.45.5
  GroupBulletinBoard, v2.21
  HealComm, v
  HonorAssist, v0.9.1
  honorspy, v1.6.7
  LeatrixMaps, v1.13.39
  LetMeCast, v1.3
  LoseControl, v1.01
  MikScrollingBattleText, v5.7.149
  MonolithDKP, v2.0.6
  NiceDamage, v40000
  PetXP, v0.2
  Plater, v
  Questie, v5.3.1
  QuestLogEx, v1.2
  RealMobHealth, v2.17
  RollTrackerClassic, v1.92
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SortBags, v0.1.3
  SpeedyAutoLoot, v2.0.25
  SpellbookAbridged, v2.6.1
  Spy, v1.0.19
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomTom, vv11303-1.0.9
  TrinketMenu, v7.3.2
  TukuiWorldFont, v1
  unitscan, v0.1.11
  WhatsTraining, v1.8.7
  YaHT, v
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=559)
```

**Comment by ressikanflute** [comment]
Details is still blocking that button. Has all the time for me since battlegrounds came to the game.

DETAILS! VERSION: C189 
GAME VERSION: v1.13.3
(latests version in Twitch app: DetailsClassic.1.13.3.189.142)

> 8x [ADDON_ACTION_FORBIDDEN] AddOn 'Details' tried to call the protected function 'AcceptBattlefieldPort()'.
> !BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
> [C]: in function `AcceptBattlefieldPort'
> FrameXML\StaticPopup.lua:689: in function `OnAccept'
> FrameXML\StaticPopup.lua:5003: in function `StaticPopup_OnClick'
> [string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Yes, tried to disable one addon after the other to isolate which was the cause. The base of Details is the one. Tried disable all the plugins, but the button still refused to be clicked. It was only possible to click it when I disabled Details itself.

**Comment by Tercioo** [comment]
> @Tercioo now button works, but I found some other error in the bg upon entering
> 
> ```
> Date: 2019-12-17 19:45:26
> ID: 1
> Error occured in: Global
> Count: 1
> Message: ..\AddOns\Details\core\parser.lua line 1701:
>    attempt to perform arithmetic on field 'total' (a nil value)
> Debug:
>    Details\core\parser.lua:1701:
>       Details\core\parser.lua:1537
>    (tail call): ?
> Locals:
> self = nil
> token = "SPELL_HEAL"
> time = 1576608326.331000
> who_serial = "Player-4701-00AE724F"
> who_name = "Hatecorelulz-Mograine"
> who_flags = 1300
> alvo_serial = "Player-4749-01672CDF"
> alvo_name = "Foolsbane-Earthshaker"
> alvo_flags = 1300
> alvo_flags2 = 0
> spellid = "Greater Heal"
> spellname = "Greater Heal"
> spelltype = 2
> amount = 2280
> overhealing = 0
> absorbed = 0
> critical = false
> is_shield = nil
> cura_efetiva = 2280
> este_jogador = <table> {
>  flag_original = 1300
>  totalabsorb = 0.004430
>  last_hps = 0
>  healing_from = <table> {
>  }
>  timeMachine = 1
>  targets = <table> {
>  }
>  iniciar_hps = true
>  pets = <table> {
>  }
>  totalover_without_pet = 0.004430
>  heal_enemy_amt = 0
>  healing_taken = 0.004430
>  totalover = 0.004430
>  total_without_pet = 0.004430
>  start_time = 1576608326
>  classe = "Priest"
>  serial = "Player-4701-00AE724F"
>  targets_overheal = <table> {
>  }
>  targets_absorbs = <table> {
>  }
>  nome = "Hatecorelulz-Mograine"
>  spells = <table> {
>  }
>  grupo = true
>  displayName = "Hatecorelulz"
>  heal_enemy = <table> {
>  }
>  last_event = 1576608326
>  custom = 0
>  tipo = 2
>  on_hold = false
>  totaldenied = 0.004430
>  delay = 0
>  pvp = true
> }
> meu_dono = nil
> jogador_alvo = <table> {
>  flag_original = 1300
>  totalabsorb = 0.003900
>  last_hps = 0
>  healing_from = <table> {
>  }
>  targets = <table> {
>  }
>  iniciar_hps = false
>  pets = <table> {
>  }
>  totalover_without_pet = 0.003900
>  heal_enemy_amt = 0
>  healing_taken = 0.003900
>  totalover = 0.003900
>  total_without_pet = 0.003900
>  start_time = 0
>  classe = "Warlock"
>  serial = "Player-4749-01672CDF"
>  targets_overheal = <table> {
>  }
>  targets_absorbs = <table> {
>  }
>  nome = "Foolsbane-Earthshaker"
>  spells = <table> {
>  }
>  grupo = true
>  displayName = "Foolsbane"
>  heal_enemy = <table> {
>  }
>  last_event = 0
>  custom = 0
>  tipo = 2
>  on_hold = false
>  totaldenied = 0.003900
>  delay = 0
>  pvp = true
> }
> alvo_dono = nil
> (*temporary) = nil
> (*temporary) = 2280
> (*temporary) = true
> (*temporary) = <function> defined @Interface\AddOns\Details\core\timemachine.lua:122
> (*temporary) = <table> {
>  flag_original = 1300
>  totalabsorb = 0.004430
>  last_hps = 0
>  healing_from = <table> {
>  }
>  timeMachine = 1
>  targets = <table> {
>  }
>  iniciar_hps = true
>  pets = <table> {
>  }
>  totalover_without_pet = 0.004430
>  heal_enemy_amt = 0
>  healing_taken = 0.004430
>  totalover = 0.004430
>  total_without_pet = 0.004430
>  start_time = 1576608326
>  classe = "Priest"
>  serial = "Player-4701-00AE724F"
>  targets_overheal = <table> {
>  }
>  targets_absorbs = <table> {
>  }
>  nome = "Hatecorelulz-Mograine"
>  spells = <table> {
>  }
>  grupo = true
>  displayName = "Hatecorelulz"
>  heal_enemy = <table> {
>  }
>  last_event = 1576608326
>  custom = 0
>  tipo = 2
>  on_hold = false
>  totaldenied = 0.004430
>  delay = 0
>  pvp = true
> }
> (*temporary) = <table> {
>  1 = <table> {
>  }
> }
> (*temporary) = 1
> (*temporary) = <table> {
>  1 = <table> {
>  }
> }
> (*temporary) = <table> {
>  flag_original = 1300
>  totalabsorb = 0.004430
>  last_hps = 0
>  healing_from = <table> {
>  }
>  timeMachine = 1
>  targets = <table> {
>  }
>  iniciar_hps = true
>  pets = <table> {
>  }
>  totalover_without_pet = 0.004430
>  heal_enemy_amt = 0
>  healing_taken = 0.004430
>  totalover = 0.004430
>  total_without_pet = 0.004430
>  start_time = 1576608326
>  classe = "Priest"
>  serial = "Player-4701-00AE724F"
>  targets_overheal = <table> {
>  }
>  targets_absorbs = <table> {
>  }
>  nome = "Hatecorelulz-Mograine"
>  spells = <table> {
>  }
>  grupo = true
>  displayName = "Hatecorelulz"
>  heal_enemy = <table> {
>  }
>  last_event = 1576608326
>  custom = 0
>  tipo = 2
>  on_hold = false
>  totaldenied = 0.004430
>  delay = 0
>  pvp = true
> }
> (*temporary) = <table> {
> }
> (*temporary) = "Foolsbane-Earthshaker"
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = "attempt to perform arithmetic on field 'total' (a nil value)"
> _in_combat = true
> _bit_band = <function> defined =[C]:-1
> OBJECT_TYPE_PETS = 12288
> SPELLID_SHAMAN_SLT = 98021
> parser = <table> {
>  WipeSourceCache = <function> defined @Interface\AddOns\Details\core\parser.lua:3646
>  swing = <function> defined @Interface\AddOns\Details\core\parser.lua:306
>  buff = <function> defined @Interface\AddOns\Details\core\parser.lua:1825
>  energize = <function> defined @Interface\AddOns\Details
> AddOns:
>   Swatter, v8.2.6377 (SwimmingSeadragon)
>   AddOnSkins, v4.39
>   AimedShotCastbarClassic, v1.0
>   AlreadyKnown, v1.22
>   AtlasLootClassic, vv1.4.3
>   AtlasLootClassicData, vv1.4.3
>   AtlasLootClassicDungeonsAndRaids, vv1.4.3
>   AtlasLootClassicMaps, vv1.0.0
>   Auctionator, v8.1.0
>   BagBrother, v
>   Bagnon, v8.2.16
>   BigDebuffs, vv8.5
>   CharacterStatsClassic, v2.8.1
>   ClassicAuraDurations, v
>   ClassicCastbars, vv1.2.0-hotfix
>   ClassicCastbarsOptions, v
>   Cleanup, v
>   DBMCore, v1.13.24
>   DBMDefaultSkin, v
>   DBMStatusBarTimers, v
>   Details, v
>   DetailsTinyThreat, v
>   ElvUI, v1.19
>   ElvUIGennUI, v1.05
>   EZJunk, v1.0.1
>   FarmLog, vv1.19
>   FiveSecondRule, v1.15
>   Focused, v1.0.16
>   GatherMate2, v1.45.5
>   GroupBulletinBoard, v2.21
>   HealComm, v
>   HonorAssist, v0.9.1
>   honorspy, v1.6.7
>   LeatrixMaps, v1.13.39
>   LetMeCast, v1.3
>   LoseControl, v1.01
>   MikScrollingBattleText, v5.7.149
>   MonolithDKP, v2.0.6
>   NiceDamage, v40000
>   PetXP, v0.2
>   Plater, v
>   Questie, v5.3.1
>   QuestLogEx, v1.2
>   RealMobHealth, v2.17
>   RollTrackerClassic, v1.92
>   SlideBar, v8.2.6375 (SwimmingSeadragon)
>   SortBags, v0.1.3
>   SpeedyAutoLoot, v2.0.25
>   SpellbookAbridged, v2.6.1
>   Spy, v1.0.19
>   Stubby, v8.2.6376 (SwimmingSeadragon)
>   TomTom, vv11303-1.0.9
>   TrinketMenu, v7.3.2
>   TukuiWorldFont, v1
>   unitscan, v0.1.11
>   WhatsTraining, v1.8.7
>   YaHT, v
>   BlizRuntimeLib_enUS v1.13.3.11303 <none>
>   (ck=559)
> ```

You still getting this "total" error with recent versions?

**Comment by ressikanflute** [comment]
I don't see that error atm, only the one I posted.

**Comment by ressikanflute** [comment]
Does that mean you fixed the issue of Details trying to execute AcceptBattlefieldPort() ?

Can't see any commits or pull requests regarding that.

**Comment by Tercioo** [comment]
Not a problem from Details!
It's an issue with the game client which Blizzard seems to not care about.
This issue already happened in the Retail version of the game years ago and got fixed pretty quickly.

At the moment the workaround is the right click the minimap battleground and hit 'Enter Battleground', as courtesy Details! moves the battleground minimap icon from the minimap to the bottom side of the enter battleground popup.


------ Original Message ------

**Comment by ressikanflute** [comment]
Ok. Thanks for clarification.

**Comment by mrbuds** [comment]
Fyi there is a ticket about it at https://github.com/Stanzilla/WoWUIBugs/issues/140

**Comment by Tercioo** [comment]
Hi Buds, this issue has been fixed a few months ago.
If it is already happening, I don't think is Details!, at least newer 
versions.

------ Original Message ------
From: "Buds" ***@***.***>
To: "Tercioo/Details-Damage-Meter" 
***@***.***>
Cc: "Tercio Jose" ***@***.***>; "State change" 
***@***.***>
Sent: 08-Jul-21 4:19:57 PM
Subject: Re: [Tercioo/Details-Damage-Meter] [Classic] Details block 
entering Battleground (#32)
