### ISSUE TITLE
DetailsRetail.v9.2.7.10017.146  "'IsWoTLKWow" error

### ISSUE THREAD

**Issue by DakJaniels** [Tercioo/Details-Damage-Meter#342]
**Game and Details! version**
Retail. 9.2.7
Details v9.2.7.10017.146

**Describe the bug**

Mouse over class icon in the damage done sort. Produces lua error.

**Lua Error**
2x Details\frames\window_main.lua:2169: attempt to call field 'IsWoTLKWow' (a nil value)
[string "@Details\frames\window_main.lua"]:2169: in function <Details\frames\window_main.lua:2111>

Locals:
self = DetailsBarra_IconFrame_1_1 {
 0 = <userdata>
 row = DetailsBarra_1_1 {
 }
 instance_id = 1
}
actor = <table> {
 flag_original = 1297
 totalabsorbed = 0.005931
 colocacao = 1
 minha_barra = DetailsBarra_1_1 {
 }
 timeMachine = 3
 damage_from = <table> {
 }
 targets = <table> {
 }
 avoidance = <table> {
 }
 pets = <table> {
 }
 isTank = true
 friendlyfire = <table> {
 }
 classe = "PALADIN"
 raid_targets = <table> {
 }
 total_without_pet = 346979.005931
 on_hold = false
 friendlyfire_total = 0
 dps_started = true
 total = 346979.005931
 spec = 66
 aID = "60-0EBF6BF7"
 nome = "Dackness"
 spells = <table> {
 }
 grupo = true
 displayName = "Dackness"
 serial = "Player-60-0EBF6BF7"
 last_dps = 181095.514581
 custom = 0
 last_event = 1661983861
 damage_taken = 0.005931
 start_time = 1661983859
 delay = 0
 tipo = 1
}
serial = "Player-60-0EBF6BF7"
name = "Dackness"
class = "PALADIN"
spec = 66
talents = <table> {
 1 = 22428
 2 = 22431
 3 = 21811
 4 = 22433
 5 = 17597
 6 = 23087
 7 = 21202
}
ilvl = <table> {
 time = 1661982977
 name = "Dackness"
 ilvl = 289.875000
}
icon_size = 20
instance = <table> {
 h_baixo = DetailsBottomSideBarHighlight1 {
 }
 menu_icons_size = 0.990000
 h_esquerda = DetailsLeftSideBarHighlight1 {
 }
 bg_r = 0
 fullborder_size = 0.500000
 color_buttons = <table> {
 }
 toolbar_icon_file = "Details\images\toolbar_icons_2"
 micro_displays_locked = true
 tooltip = <table> {
 }
 icons = <table> {
 }
 ponto3 = <table> {
 }
 ponto1 = <table> {
 }
 rolagem = false
 rows_max = 50
 titlebar_texture = "Details Serenity"
 windowBackgroundDisplay = Details_GumpFrame1 {
 }
 lastIcon = <table> {
 }
 fontstrings_text_limit_offset = -10
 menu_icons = <table> {
 }
 isMoving = false
 show_sidebars = true
 hide_icon = true
 consolidate = false
 toolbar_side = 1
 sub_atributo = 1
 atributo = 1
 menu_icons_alpha = 0.920000
 bg_b = 0
 largura_scroll = 26
 rowareaborder_color = <table> {
 }
 color = <table> {
 }
 sub_atributo_last = <table> {
 }
 barraS = <table> {
 }
 h_cima = DetailsTopSideBarHighlight1 {
 }
 switch_healer = false
 showing = <table> {
 }
 ponto4 = <table> {
 }
 __locked = true
 menu_alpha = <table> {
 }
 snap = <table> {
 }
 rowareaborder_size = 0.500000
 clickthrough_incombatonly = true
 hide_in_combat_alpha = 0
 firstIcon = DetailsClearSegmentsButton1 {
 }
 switch_damager_in_combat = false
 StatusBar = <table> {
 }
 verticalSnap = true
 hide_in_combat = false
 posicao = <table> {
 }
 row_height = 25
 titlebar_texture_color = <table> {
 }
 __pos = <table> {
 }
 show_statusbar = false
 clickthrough_window = false
 titlebar_shown = false
 menu_anchor = <table> {
 }
 total_buttons_shown = 5
 hide_out_of_combat = false
 rows_created = 9
 bars_sort_direction = 1
 use_auto_align_multi_fontstrings = true
 __was_opened = true
 fullborder_shown = false
 clickthrough_toolbaricons = false
 row_info = <table> {
 }
 barras = <table> {
 }
 horizontalSnap = false
 ignore_mass_showhide = false
 windowSwitchButton = Details_SwitchButtonFrame1 {
 }
 switch_all_roles_after_wipe = false
 icon_desaturated = false
 desaturated_menu = false
 micro_displays_side = 2
 window_scale = 1
 h_direita = DetailsRightSideBarHighlight1 {
 }
 is_interacting = false
 last_interaction = 1661983862
 do_not_snap = false
 meu_id = 1
 bg_g = 0
 LastModo = 2
 skin_custom = ""
 mostrando = "normal"
 top = 346979.005931
 rows_fit_in_window = 9
 ponto2 = <table> {
 }
 oldwith = 211.971375
 attribute_text = <table> {
 }
 hide_in_combat_type = 1
 scroll = Details_ScrollBar1 {
 }
 bars_inverted = false
 bgdisplay = Details_GumpFrame1 {
 }
 bgframe = Details_WindowFrame1 {
 }
 baseframe = DetailsBaseFrame1 {
 }
 switch_healer_in_combat = false
 ativa = true
 break_snap_button = DetailsBreakSnapButton1 {
 }
 alturaAntiga = 129.999985
 fontstrings_text3_anchor = 35
 segmento = 0
 last_modo = 2
 menu2_points = <table> {
 }
 skin = "New Gray"
 menu_points = <table> {
 }
 following = <table> {
 }
 rows_showing = 1
 modo = 2
 fontstrings_text2_anchor = 70
 alert = DetailsAlertFrame1 {
 }
 switch_tank = false
 freeze_texto = <unnamed> {
 }
 inic

**Comment by Tercioo** [comment]
10018 on the way, thank you!

**Comment by DakJaniels** [comment]
Thank you.
