### ISSUE TITLE
LUA error when logging in; today's new version

### ISSUE THREAD

**Issue by raysmith59** [Tercioo/Details-Damage-Meter#348]
Version R10018
Game Version 9.2.7

3x Details_Streamer\Details_Streamer.lua:216: attempt to call method 'SetResizeBounds' (a nil value)
[string "@Details_Streamer\Details_Streamer.lua"]:216: in function <Details_Streamer\Details_Streamer.lua:66>
[string "@Details_Streamer\Details_Streamer.lua"]:2327: in function `OnEvent'
[string "@Details\core\plugins.lua"]:294: in function <Details\core\plugins.lua:291>

Locals:
fader = <function> defined @Details\core\util.lua:122
titlebar = DetailsStreamerTitlebar {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:144
 text = <unnamed> {
 }
 Center = <unnamed> {
 }
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:382
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:206
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:174
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:270
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:414
 RightEdge = <unnamed> {
 }
 backdropInfo = <table> {
 }
 BottomEdge = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:180
 BottomLeftCorner = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 TopEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:286
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:321
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:274
 TopRightCorner = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:339
 TopLeftCorner = <unnamed> {
 }
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:238
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:391
 LeftEdge = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:258
}
(*temporary) = nil
(*temporary) = Details_Streamer {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:144
 Center = <unnamed> {
 }
 backdropInfo = <table> {
 }
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:382
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:206
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:174
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:270
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:414
 RightEdge = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
 TopRightCorner = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:180
 BottomRightCorner = <unnamed> {
 }
 BottomLeftCorner = <unnamed> {
 }
 TopEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:286
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:321
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:274
 __parent = <table> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:339
 TopLeftCorner = <unnamed> {
 }
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:238
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:391
 LeftEdge = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:258
}
(*temporary) = 150
(*temporary) = 10
(*temporary) = 800
(*temporary) = 1024
(*temporary) = "attempt to call method 'SetResizeBounds' (a nil value)"
StreamOverlay = <table> {
 __options = 1
 CurrentVersion = "v1.2"
 OnEnablePlugin = <function> defined @Details_Streamer\Details_Streamer.lua:90
 CreateMinimapIcon = <function> defined @Details_Streamer\Details_Streamer.lua:2483
 __enabled = true
 SetLocked = <function> defined @Details_Streamer\Details_Streamer.lua:1522
 OnDetailsEvent = <function> defined @Details_Streamer\Details_Streamer.lua:71
 Enabled = true
 CastFinished = <function> defined @Details_Streamer\Details_Streamer.lua:1041
 OnEvent = <function> defined @Details_Streamer\Details_Streamer.lua:2312
 OpenOptionsPanel = <function> defined @Details_Streamer\Details_Streamer.lua:1667
 CastStar

**Comment by Tercioo** [comment]
looking into

------ Original Message ------
From: "raysmith59" ***@***.***>
To: "Tercioo/Details-Damage-Meter" 
***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 15-Sep-22 10:23:31 PM
Subject: [Tercioo/Details-Damage-Meter] LUA error when logging in; 
today's new version (Issue #348)

**Comment by Tercioo** [comment]
fixed
