### ISSUE TITLE
Details blocking the update of online guild members in ElvUi

### ISSUE THREAD

**Issue by klainn** [Tercioo/Details-Damage-Meter#35]
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**

**Game and Details! version**
DETAILS! VERSION: 87229
GAME VERSION: v8.2.5
ElvUI Version 11.27

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
Log out of WoW
Disable All Addons except for ElvUI and Details Damage Meter
Log in
- Result (what happens when you follow the steps above):
The count of online guild members displays 0. It should at a minimum display 1 for myself.
- Expected (what you think the expected behavior would be when following the steps):
It should display the proper number of members online.
- When the bug started (a date, wow path release, details update, etc)?
Within the last 2-3 weeks.
- Additional information:

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*

**Screenshots**
Post images of the bug if necessary.

**Combat Log**
Include a link to a combatlog file if the error is about not detecting a skill, usable item or item proc.
The log can be as simple as hitting a mob with white damage and using the item/skill.

**Other Information**
I know this is an odd one but this is easily reproducible on two accounts that I know of running both ElvUI 11.27 and Details version 87229.

When you log in with only ElvUI and the OptionsUI component of ElvUI, you see on the minimap a Guild and a Friends online count. The friends online count is fine, but the Guild count always displays 0 until you hover over the field or reload your ui.

To test I disabled all addons except for ElvUI and it works fine. I then added addons one by one to verify if the problem remained. When a addon was verified as not effecting the Guild online count, it was then disabled and the next addon checked. With only "Details Damage Meter" and ElvUI enabled, the problem remains. When I log out, disable details and then log back in with only ElvUI enabled, I see the count displayed properly. When I log back out, enable only Details Damage Meter (not any of the additional Details plugins) and log back in, the count of online guild members is always zero. It should, at the very least display 1 for myself being online. This is a recent issue (within the last 2-3 weeks).

**Comment by Tercioo** [comment]
Have you spoken with ElvUI Team about this issue?

**Comment by klainn** [comment]
Yes I did. But since the only time it happens is when I enable details they suggested I come here.

**Comment by Tercioo** [comment]
Not an issue with Details!
