### ISSUE TITLE
Lua Error in login

### ISSUE THREAD

**Issue by BlueNightSky** [Tercioo/Details-Damage-Meter#357]
**Game and Details! version**
Details.Wrath.SL.DF.10030.146
Retail 9.2.7.45745

The following errors appear in login
**Lua Error**
1x ...faceDetails\Libs\LibOpenRaid\LibOpenRaid.lua:2088: attempt to index local 'itemLink' (a nil value)
[string "@Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:2088: in function <...faceDetails\Libs\LibOpenRaid\LibOpenRaid.lua:2082>
[string "@Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:2099: in function `UpdatePlayerKeystoneInfo'
[string "@Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:2154: in function `OnReceiveRequestData'
[string "@Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:2216: in function `?'
[string "@Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:521: in function `TriggerEvent'
[string "@Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:615: in function `?'
[string "@Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:695: in function <...faceDetails\Libs\LibOpenRaid\LibOpenRaid.lua:694>

Locals:
(for index) = 3
(for limit) = 4
(for step) = 1
backpackId = 3
(for index) = 5
(for limit) = 32
(for step) = 1
slotId = 5
itemId = nil
itemLink = nil
(*temporary) = 3
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'itemLink' (a nil value)"

And this error message appears in the chat window
`openRaidLib: error on scheduler: updatePlayerData_Schedule [string "@Interface\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:350: in function `NewUniqueTimer'
[string "@Interface\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:769: in function `?'
[string "@Interface\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:521: in function `TriggerEvent'
[string "@Interface\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:615: in function `?'
[string "@Interface\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua"]:695: in function <...face\AddOns\Details\Libs\LibOpenRaid\LibOpenRaid.lua:694>
 ...ns\Details\Libs\LibOpenRaid\GetPlayerInformation.lua:249: attempt to index global 'LIB_OPEN_RAID_WEAPON_ENCHANT_IDS' (a nil value)`

**Comment by zeenk** [comment]
Same here

![2022-09-27_05-59-19](https://user-images.githubusercontent.com/68170439/192428792-7af7549b-fa41-423f-b6a7-6ab8eb115789.png)

**Comment by zeenk** [comment]
@BlueNightSky
https://www.curseforge.com/wow/addons/details/files/4009058
Seems to be fixed in latest alpha patch.

**Comment by BlueNightSky** [comment]
Thank you for replying, but my error is slightly different from you.
My error still exist, I had to go back to the old version first.

**Comment by iShark5060** [comment]
I think it's because of a wrong version:
Curse automatically installs "[Details.Wrath.SL.DF.10030.146](https://www.curseforge.com/wow/addons/details/files/4008993)", which looks to me like a version for Wrath (could be wrong tho).. because at the same time (well okay, 2 minutes prior) the version "[DetailsRetail.9.2.7.10029b.146](https://www.curseforge.com/wow/addons/details/files/4008990)" got uploaded - and that works without problem for me.
