### ISSUE TITLE
[CLASSIC] Details bug

### ISSUE THREAD

**Issue by volostyle** [Tercioo/Details-Damage-Meter#37]
### **Before Start!**
This is the only addon enabled.

**Game and Details! version**
Details version C188
Game version v1.13.3

**Describe the bug**
Bug seems to be caused by BG's.  When entering the BG and going in combat, the LUA errors are thrown constantly.  Even upon exiting the BG, the LUA errors continue even in PvE content.  Sometimes doing a /details reset fixes the issue.  Other times doing a /reset and relogging fixes the issue.

**Lua Error**

Message: Interface\AddOns\Details\classes\classe_damage.lua:135: attempt to compare string with number
Time: Fri Dec 27 11:00:27 2019
Count: 1
Stack: Interface\AddOns\Details\classes\classe_damage.lua:135: attempt to compare string with number
Interface\AddOns\Details\classes\classe_damage.lua:135: in function <Interface\AddOns\Details\classes\classe_damage.lua:133>
[C]: ?
Interface\AddOns\Details\classes\classe_damage.lua:2058: in function <Interface\AddOns\Details\classes\classe_damage.lua:1568>
(tail call): ?
Interface\AddOns\Details\core\control.lua:1932: in function `AtualizaGumpPrincipal'
Interface\AddOns\Details\core\util.lua:460: in function `UpdateToKFunctions'
Interface\AddOns\Details\core\util.lua:451: in function `SelectNumericalSystem'
Interface\AddOns\Details\functions\profiles.lua:550: in function `ApplyProfile'
Interface\AddOns\Details\functions\loaddata.lua:414: in function `LoadConfig'
Interface\AddOns\Details\core\parser.lua:4823: in function <Interface\AddOns\Details\core\parser.lua:4788>
Interface\AddOns\Details\core\parser.lua:4832: in function <Interface\AddOns\Details\core\parser.lua:4829>
(tail call): ?

Locals: table1 = <table> {
 flag_original = 1320
 totalabsorbed = 0.002375
 end_time = 1577461834
 damage_from = <table> {
 }
 targets = <table> {
 }
 last_dps = 0
 pets = <table> {
 }
 dps_started = false
 delay = 1577461830
 classe = "UNGROUPPLAYER"
 raid_targets = <table> {
 }
 total_without_pet = 387.002375
 __index = <table> {
 }
 damage_taken = 0.002375
 fight_component = true
 total = 387.002375
 tipo = 1
 friendlyfire_total = 0
 nome = "Tactishian-Benediction"
 spells = <table> {
 }
 grupo = true
 displayName = "Tactishian"
 serial = "Player-4728-00BAFD9E"
 on_hold = false
 custom = 0
 last_event = 1577461830
 friendlyfire = <table> {
 }
 start_time = 1577461833
 pvp_component = true
 pvp = true
}
table2 = <table> {
 flag_original = 1300
 totalabsorbed = 0.003281
 damage_from = <table> {
 }
 targets = <table> {
 }
 delay = 0
 pets = <table> {
 }
 on_hold = false
 total = "ROGUE"
 classe = "Rogue"
 raid_targets = <table> {
 }
 total_without_pet = 0.003281
 __index = <table> {
 }
 friendlyfire_total = 0
 dps_started = false
 end_time = 1577461834
 damage_taken = 0.003281
 tipo = 1
 nome = "Achilios-Blaumeux"
 spells = <table> {
 }
 grupo = true
 displayName = "Achilios"
 last_dps = 0
 serial = "Player-4397-003F411C"
 custom = 0
 last_event = 0
 friendlyfire = <table> {
 }
 start_time = 1577461834
 pvp_component = true
 pvp = true
}
(*temporary) = 387.002375
(*temporary) = "ROGUE"
(*temporary) = "attempt to compare string with number"
keyName = "total"

**Screenshots**
Post images of the bug if necessary.

**Combat Log**
Include a link to a combatlog file if the error is about not detecting a skill, usable item or item proc.
The log can be as simple as hitting a mob with white damage and using the item/skill.

**Other Information**
If necessary, add more info here.

**Comment by Tercioo** [comment]
Thank you for the report. Do you think this problem started with the .188 update from yesterday?

------ Original Message ------

**Comment by Tercioo** [comment]
Closing for now, user didn't answered.
