### ISSUE TITLE
[suggestion] option to toggle in battleground

### ISSUE THREAD

**Issue by anzz1** [Tercioo/Details-Damage-Meter#39]
A great simple feature to add would be to add a configuration option to auto-hide Details when in battlegrounds. It is easy to detect it for example with events UPDATE_BATTLEFIELD_STATUS or ZONE_CHANGED_NEW_AREA or using hooksecurefunc with AcceptBattlefieldPort().

**Comment by Tercioo** [comment]
It's done by scripting, there's a bunch of examples in the docs (see discord > resources channel).
