### ISSUE TITLE
Versions on CF vs Wago

### ISSUE THREAD

**Issue by tflo** [Tercioo/Details-Damage-Meter#392]
I'm using both the CurseForge and the Wago client by WoWUp (largely preferring Wago over Overwolf!), but since some weeks it seems that most Details updates are only pushed to CF. (In the time immediately after you started with Wago, this was not the case.)

PS: It just occurs to me now:

You also have introduced a "standalone" distro of your mod some time ago, which might coincide with your first Wago push, not sure. Is this 'standalone' thing meant to be the Wago distro? If Yes, how should I understand "standalone"? Also my "normal" Details install runs perfectly fine 'standalone' without being "standalone".

Do you maybe mean 'all-in-one' with "standalone"? Then it _should_ be (probably) compatible with the CF downloads (though currently my CF client does not recognize the installs coming from the Wago client).

Thanks for clarification, and for considering uploading all versions also to Wago,

– Tom

**Comment by Tercioo** [comment]
I'm aware, wago updates atm are done manually

------ Original Message ------
From: "Tom" ***@***.***>
To: "Tercioo/Details-Damage-Meter" 
***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 01-Dec-22 4:39:22 PM
Subject: [Tercioo/Details-Damage-Meter] Versions on CF vs Wago (Issue 
#392)

**Comment by tflo** [comment]
Ah, ok. Thanks!

**Comment by tflo** [comment]
Had added a PS (edit) to the OP, shortly before your reply.

**Comment by tflo** [comment]
Anyways, closing this, as it is minor stuff.

**Comment by tflo** [comment]
Hmm, reopening it, bc I think not having the up-to-date versions on Wago _is_ an issue.  Though a minor one. (But also the opaque naming, 'standalone' vs normal).

**Comment by tflo** [comment]
Closing for futility. thanks.
