### ISSUE TITLE
74 Lua Warning at launch 

### ISSUE THREAD

**Issue by Seizzz** [Tercioo/Details-Damage-Meter#4]
Message: Interface\AddOns\Details\locales\Details-enUS.lua:6: unexpected symbol near '@'
Time: Wed Jun 12 12:06:24 2019
Count: 1
Stack: Interface\AddOns\Details\locales\Details-enUS.lua:6: unexpected symbol near '@'

Locals:

**Comment by Seizzz** [comment]
Message: Interface\AddOns\Details\boot.lua:28: Usage: GetLocale(application[, silent]): 'application' - No locales registered for 'Details'
Time: Thu Jun 13 00:59:51 2019
Count: 1
Stack: Interface\AddOns\Details\boot.lua:28: Usage: GetLocale(application[, silent]): 'application' - No locales registered for 'Details'
[C]: ?
...astbars_Options\Libs\AceLocale-3.0\AceLocale-3.0.lua:134: in function `GetLocale'
Interface\AddOns\Details\boot.lua:28: in main chunk

Locals: (*temporary) = "Usage: GetLocale(application[, silent]): 'application' - No locales registered for 'Details'"

**Comment by Seizzz** [comment]
Message: Interface\AddOns\Details\core\util.lua:4: Usage: GetLocale(application[, silent]): 'application' - No locales registered for 'Details'
Time: Thu Jun 13 00:59:51 2019
Count: 1
Stack: Interface\AddOns\Details\core\util.lua:4: Usage: GetLocale(application[, silent]): 'application' - No locales registered for 'Details'
[C]: ?
...astbars_Options\Libs\AceLocale-3.0\AceLocale-3.0.lua:134: in function `GetLocale'
Interface\AddOns\Details\core\util.lua:4: in main chunk

Locals: (*temporary) = "Usage: GetLocale(application[, silent]): 'application' - No locales registered for 'Details'"

**Comment by Seizzz** [comment]
Message: Interface\AddOns\Details\functions\profiles.lua:5: Usage: GetLocale(application[, silent]): 'application' - No locales registered for 'Details'
Time: Thu Jun 13 00:59:51 2019
Count: 1
Stack: Interface\AddOns\Details\functions\profiles.lua:5: Usage: GetLocale(application[, silent]): 'application' - No locales registered for 'Details'
[C]: ?
...astbars_Options\Libs\AceLocale-3.0\AceLocale-3.0.lua:134: in function `GetLocale'
Interface\AddOns\Details\functions\profiles.lua:5: in main chunk

Locals: (*temporary) = "Usage: GetLocale(application[, silent]): 'application' - No locales registered for 'Details'"

**Comment by Seizzz** [comment]
Message: Interface\AddOns\Details\functions\hooks.lua:19: attempt to index field 'hooks' (a nil value)
Time: Thu Jun 13 00:59:51 2019
Count: 1
Stack: Interface\AddOns\Details\functions\hooks.lua:19: attempt to index field 'hooks' (a nil value)
Interface\AddOns\Details\functions\hooks.lua:19: in main chunk

Locals: _detalhes = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 BFACORE = 131
 Enable = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 APITopics = <table> {
 }
 EnableModule = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 UnregisterComm = <function> defined @Interface\AddOns\ClassicCastbars_Options\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Interface\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:172
 Deserialize = <function> defined @Interface\AddOns\Details\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:246
 userversion = "v8.1.5.7129"
 SetNicknameAvatar = <function> defined @Interface\AddOns\Details\Libs\NickTag-1.0\NickTag-1.0.lua:542
 ScheduleRepeatingTimer = <function> defined @Interface\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Interface\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:160
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 name = "_detalhes"
 IsEnabled = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 ScheduleTimer = <function> defined @Interface\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 ResetPlayerPersona = <function> defined @Interface\AddOns\Details\Libs\NickTag-1.0\NickTag-1.0.lua:361
 GetNickname = <function> defined @Interface\AddOns\Details\Libs\NickTag-1.0\NickTag-1.0.lua:645
 GetNicknameBackground = <function> defined @Interface\AddOns\Details\Libs\NickTag-1.0\NickTag-1.0.lua:673
 APIText = <table> {
 }
 resize_debug = <table> {
 }
 version = "v8.1.5.7129 (core 140)"
 APIVersion = 140
 realversion = 140
 IsModule = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:468
 game_version = "v8.1.5"
 SetDefaultModuleState = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:387
 SetNickname = <function> defined @Interface\AddOns\Details\Libs\NickTag-1.0\NickTag-1.0.lua:495
 UnregisterAllComm = <function> defined @Interface\AddOns\ClassicCastbars_Options\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Serialize = <function> defined @Interface\AddOns\Details\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:122
 enabledState = true
 Disable = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
 build_counter = 7129
 NickTagSetCache = <function> defined @Interface\AddOns\Details\Libs\NickTag-1.0\NickTag-1.0.lua:406
 RegisterComm = <function> defined @Interface\AddOns\Details\Libs\AceComm-3.0\AceComm-3.0.lua:60
 GetNicknameTable = <function> defined @Interface\AddOns\Details\Libs\NickTag-1.0\NickTag-1.0.lua:686
 GetNicknameAvatar = <function> defined @Interface\AddOns\Details\Libs\NickTag-1.0\NickTag-1.0.lua:658
 IterateModules = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
 alpha_build_counter = 7129
 CancelTimer = <function> defined @

**Comment by Tercioo** [comment]
This is the development version of Details!
To play you need to get the version from Curse, here is the link:
https://wow.curseforge.com/projects/details/files

**Comment by Seizzz** [comment]
Oh sorry, thought it was the classic version as suggest the site
willitclassic. Com

Thx for your answer

Le jeu. 13 juin 2019 à 02:19, Tercio Jose <notifications@github.com> a
écrit :
