### ISSUE TITLE
[Classic] Some issues with BG's

### ISSUE THREAD

**Issue by ramboozer** [Tercioo/Details-Damage-Meter#40]
Make sure the bug also happen when Details! is the only addon enabled.

Game and Details! version C189
Game Version v.1.13.3

**Describe the bug**
 Cannot report player from map during BG or The Enter Battleground Button does not work

**Lua Error**
`Date: 2020-01-11 14:40:29
ID: 3
Error occured in: AddOn: Details
Count: 1
Message: Error: AddOn Details attempted to call a forbidden function (ReportPlayerIsPVPAFK()) from a tainted execution path.
Debug:
   [C]: ReportPlayerIsPVPAFK()
   ..._SharedMapDataProviders\GroupMembersDataProvider.lua:188: func()
   ..\FrameXML\UIDropDownMenu.lua:958: UIDropDownMenuButton_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
None`

`Date: 2020-01-11 15:28:33
ID: 4
Error occured in: AddOn: Details
Count: 1
Message: Error: AddOn Details attempted to call a forbidden function (AcceptBattlefieldPort()) from a tainted execution path.
Debug:
   [C]: AcceptBattlefieldPort()
   ..\FrameXML\StaticPopup.lua:689: OnAccept()
   ..\FrameXML\StaticPopup.lua:5003: StaticPopup_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
None`

Screenshots
https://puu.sh/EYNY6/3b0b7ae07a.png

**Comment by Tercioo** [comment]
I'ts a blizzard issue with it's classic client.
