### ISSUE TITLE
Bug in WD 10334 ALPHA 2 10.0.2

### ISSUE THREAD

**Issue by Addonman** [Tercioo/Details-Damage-Meter#400]
DETAILS! VERSION: WD 10334 ALPHA 2 10.0.2

Count: 1
Message: ...erface/AddOns/Details/Libs/LibOpenRaid/Functions.lua line 450:
   attempt to concatenate local 'itemName' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/WagoAnalytics/WagoAnalytics.lua"]:72:
      Interface/AddOns/WagoAnalytics/WagoAnalytics.lua:70
   [string "@Interface/AddOns/Details/Libs/LibOpenRaid/Functions.lua"]:450: BuildEquipmentItemLinks()
   [string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:1613: AddUnitGearList()
   [string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:1018:
      ...face/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua:1010
   [string "=[C]"]: xpcall()
   [string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:546:
      ...face/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua:536

Count: 1
Message: ...face/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua line 2161:
   attempt to index local 'currentCooldowns' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/WagoAnalytics/WagoAnalytics.lua"]:72:
      Interface/AddOns/WagoAnalytics/WagoAnalytics.lua:70
   [string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:2161: CheckForSpellsAdeedOrRemoved()
   [string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:2051: CheckCooldownChanges()
   [string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:2006: functionToCallback()
   [string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:750: TriggerEvent()
   [string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:919:
      ...face/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua:919
   [string "=[C]"]: xpcall()
   [string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:546:
      ...face/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua:536

**Comment by Tercioo** [comment]
thank you! could you give the character name and realm?
need to check the arvory of the character to see the gear

------ Original Message ------
From: "Addonman" ***@***.***>
To: "Tercioo/Details-Damage-Meter" 
***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 11-Dec-22 10:18:30 AM
Subject: [Tercioo/Details-Damage-Meter] Bug in WD 10334 ALPHA 2 10.0.2 
(Issue #400)

**Comment by Addonman** [comment]
https://worldofwarcraft.com/en-gb/character/eu/twisting-nether/airlocko

**Comment by Tercioo** [comment]
I see you have experience with code, would you mind to edit the code to see if fixes?
file: wowfolder/retail/Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua

these lines need to be inside a C_Timer, as shown on the second block of code
```
                --gear info
                local playerGearInfo = openRaidLib.GearManager.GetPlayerFullGearInfo()
                openRaidLib.GearManager.AddUnitGearList(unitName, unpack(playerGearInfo))
```

```
            --gear info
            C_Timer.After(2, function()
                local playerGearInfo = openRaidLib.GearManager.GetPlayerFullGearInfo()
                openRaidLib.GearManager.AddUnitGearList(unitName, unpack(playerGearInfo))
            end)
```

**Comment by Addonman** [comment]
Still getting first error,but not second one
Count: 1
Message: ...erface/AddOns/Details/Libs/LibOpenRaid/Functions.lua line 450:
   attempt to concatenate local 'itemName' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/WagoAnalytics/WagoAnalytics.lua"]:72:
      Interface/AddOns/WagoAnalytics/WagoAnalytics.lua:70
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Details/Libs/LibOpenRaid/Functions.lua"]:450: BuildEquipmentItemLinks()
   [string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:1615: AddUnitGearList()
   [string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:1019:
      ...face/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua:1017
Locals:
(*temporary) = <function> defined =[C]:-1

**Comment by Tercioo** [comment]
thank you!

Could you make a quick debug for me?

On the file: Interface/AddOns/Details/Libs/LibOpenRaid/Functions.lua

After the line: "function 
openRaidLib.GearManager.BuildEquipmentItemLinks(equippedGearList)"
Add: dumpt(equippedGearList)

It will look like this: "function 
openRaidLib.GearManager.BuildEquipmentItemLinks(equippedGearList) 
dumpt(equippedGearList)"

It will show a window with the contents of the equippedGearList which I 
need to see what's going on.


------ Original Message ------
From: "Addonman" ***@***.***>
To: "Tercioo/Details-Damage-Meter" 
***@***.***>
Cc: "Tercio Jose" ***@***.***>; "Comment" 
***@***.***>
Sent: 11-Dec-22 11:25:06 AM
Subject: Re: [Tercioo/Details-Damage-Meter] Bug in WD 10334 ALPHA 2 
10.0.2 (Issue #400)

**Comment by Addonman** [comment]
[1] =  {
   ["1"] = 1,
   ["2"] = 0,
   ["4"] = ":190620::::::::60:267::81:6:6652:7580:8133:8116:1505:6646",
},
[2] =  {
   ["1"] = 2,
   ["2"] = 0,
   ["4"] = ":190635::::::::60:267::11:4:8114:6652:7578:1488",
},
[3] =  {
   ["1"] = 3,
   ["2"] = 0,
   ["4"] = ":190981::::::::60:267::11:4:8113:6652:7956:1485",
},
[4] =  {
   ["1"] = 5,
   ["2"] = 0,
   ["4"] = ":190978::::::::60:267::11:4:8113:7946:6652:1485",
},
[5] =  {
   ["1"] = 6,
   ["2"] = 0,
   ["4"] = ":190469::::::::60:267::11:2:6652:7579",
},
[6] =  {
   ["1"] = 7,
   ["2"] = 0,
   ["4"] = ":190621::::::::60:267::81:6:6652:8133:8116:43:1505:6646",
},
[7] =  {
   ["1"] = 8,
   ["2"] = 0,
   ["4"] = ":188007::::::::60:267::28:5:6652:8093:8137:8131:1492",
},
[8] =  {
   ["1"] = 9,
   ["2"] = 0,
   ["4"] = ":190348::::::::60:267::11:5:8114:7933:6652:7579:1488",
},
[9] =  {
   ["1"] = 10,
   ["2"] = 0,
   ["4"] = ":190343::::::::60:267::11:3:8113:6652:1485",
},
[10] =  {
   ["1"] = 11,
   ["2"] = 0,
   ["4"] = ":190632::::::::60:267::11:4:8113:6652:7578:1485",
},
[11] =  {
   ["1"] = 12,
   ["2"] = 0,
   ["4"] = ":190633::::::::60:267::11:4:8113:6652:7579:1485",
},
[12] =  {
   ["1"] = 13,
   ["2"] = 0,
   ["4"] = ":187447::::::::60:267::81:3:6652:1479:6646",
},
[13] =  {
   ["1"] = 14,
   ["2"] = 0,
   ["4"] = ":190602::::::::60:267::27:4:8108:8145:6652:1482",
},
[14] =  {
   ["1"] = 15,
   ["2"] = 0,
   ["4"] = ":190605::::::::60:267::11:3:8113:6652:1485",
},
[15] =  {
   ["1"] = 16,
   ["2"] = 0,
   ["4"] = ":188050::::::::60:267::26:2:6652:1475",
},

**Comment by Addonman** [comment]
[1] =  {
   ["1"] = 1,
   ["2"] = 1,
   ["3"] = 259,
   ["4"] = ":190620::::::::60:267::81:6:6652:7580:8133:8116:1505:6646",
},
[2] =  {
   ["1"] = 2,
   ["2"] = 0,
   ["3"] = 249,
   ["4"] = ":190635::::::::60:267::11:4:8114:6652:7578:1488",
},
[3] =  {
   ["1"] = 3,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190981::::::::60:267::11:4:8113:6652:7956:1485",
},
[4] =  {
   ["1"] = 5,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190978::::::::60:267::11:4:8113:7946:6652:1485",
},
[5] =  {
   ["1"] = 6,
   ["2"] = 0,
   ["3"] = 265,
   ["4"] = ":190469::::::::60:267::11:2:6652:7579",
},
[6] =  {
   ["1"] = 7,
   ["2"] = 0,
   ["3"] = 259,
   ["4"] = ":190621::::::::60:267::81:6:6652:8133:8116:43:1505:6646",
},
[7] =  {
   ["1"] = 8,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":188007::::::::60:267::28:5:6652:8093:8137:8131:1492",
},
[8] =  {
   ["1"] = 9,
   ["2"] = 0,
   ["3"] = 249,
   ["4"] = ":190348::::::::60:267::11:5:8114:7933:6652:7579:1488",
},
[9] =  {
   ["1"] = 10,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190343::::::::60:267::11:3:8113:6652:1485",
},
[10] =  {
   ["1"] = 11,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190632::::::::60:267::11:4:8113:6652:7578:1485",
},
[11] =  {
   ["1"] = 12,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190633::::::::60:267::11:4:8113:6652:7579:1485",
},
[12] =  {
   ["1"] = 13,
   ["2"] = 0,
   ["3"] = 233,
   ["4"] = ":187447::::::::60:267::81:3:6652:1479:6646",
},
[13] =  {
   ["1"] = 14,
   ["2"] = 0,
   ["3"] = 236,
   ["4"] = ":190602::::::::60:267::27:4:8108:8145:6652:1482",
},
[14] =  {
   ["1"] = 15,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190605::::::::60:267::11:3:8113:6652:1485",
},
[15] =  {
   ["1"] = 16,
   ["2"] = 0,
   ["3"] = 229,
   ["4"] = ":188050::::::::60:267::26:2:6652:1475",
},

**Comment by Addonman** [comment]
where is that c_timer?

**Comment by Addonman** [comment]
First one is was generated as i was logging in ,2nd was generate as i was playing a game -maybe that diff there

**Comment by Tercioo** [comment]
good to know about that, also I want to say thank so much for having the patience to deal with these requests, unfortunately they don't happen on my end.

the c_timer here: https://github.com/Tercioo/Details-Damage-Meter/issues/400#issuecomment-1345556519
interesting if you set it to be 10 instead of 2, to see if the list shows the ["3"]. and set it back to the original code to see if  doesn't show the ["3"] in the list.

![image](https://user-images.githubusercontent.com/9000280/206913290-5cbc979d-68fd-47f6-8b8a-8efbd2fec451.png)

**Comment by Addonman** [comment]
on clean alt only details and swatter enabled -c_timer on 10
[1] =  {
   ["1"] = 5,
   ["2"] = 0,
   ["3"] = 16,
   ["4"] = ":157690::::::::10:269:::",
},
[2] =  {
   ["1"] = 6,
   ["2"] = 0,
   ["3"] = 16,
   ["4"] = ":157696::::::::10:269:::",
},
[3] =  {
   ["1"] = 7,
   ["2"] = 0,
   ["3"] = 16,
   ["4"] = ":157694::::::::10:269:::",
},
[4] =  {
   ["1"] = 8,
   ["2"] = 0,
   ["3"] = 16,
   ["4"] = ":157691::::::::10:269:::",
},
[5] =  {
   ["1"] = 9,
   ["2"] = 0,
   ["3"] = 16,
   ["4"] = ":157697::::::::10:269:::",
},
[6] =  {
   ["1"] = 10,
   ["2"] = 0,
   ["3"] = 16,
   ["4"] = ":157692::::::::10:269:::",
},
[7] =  {
   ["1"] = 16,
   ["2"] = 0,
   ["3"] = 16,
   ["4"] = ":157627::::::::10:269:::",
},
[8] =  {
   ["1"] = 17,
   ["2"] = 0,
   ["3"] = 16,
   ["4"] = ":157627::::::::10:269:::",
},

**Comment by Addonman** [comment]
first on 10 then original code
loging in
[1] =  {
   ["1"] = 1,
   ["2"] = 0,
   ["4"] = ":190620::::::::60:267::81:6:6652:7580:8133:8116:1505:6646",
},
[2] =  {
   ["1"] = 2,
   ["2"] = 0,
   ["4"] = ":190635::::::::60:267::11:4:8114:6652:7578:1488",
},
[3] =  {
   ["1"] = 3,
   ["2"] = 0,
   ["4"] = ":190981::::::::60:267::11:4:8113:6652:7956:1485",
},
[4] =  {
   ["1"] = 5,
   ["2"] = 0,
   ["4"] = ":190978::::::::60:267::11:4:8113:7946:6652:1485",
},
[5] =  {
   ["1"] = 6,
   ["2"] = 0,
   ["4"] = ":190469::::::::60:267::11:2:6652:7579",
},
[6] =  {
   ["1"] = 7,
   ["2"] = 0,
   ["4"] = ":190621::::::::60:267::81:6:6652:8133:8116:43:1505:6646",
},
[7] =  {
   ["1"] = 8,
   ["2"] = 0,
   ["4"] = ":188007::::::::60:267::28:5:6652:8093:8137:8131:1492",
},
[8] =  {
   ["1"] = 9,
   ["2"] = 0,
   ["4"] = ":190348::::::::60:267::11:5:8114:7933:6652:7579:1488",
},
[9] =  {
   ["1"] = 10,
   ["2"] = 0,
   ["4"] = ":190343::::::::60:267::11:3:8113:6652:1485",
},
[10] =  {
   ["1"] = 11,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190632::::::::60:267::11:4:8113:6652:7578:1485",
},
[11] =  {
   ["1"] = 12,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190633::::::::60:267::11:4:8113:6652:7579:1485",
},
[12] =  {
   ["1"] = 13,
   ["2"] = 0,
   ["3"] = 233,
   ["4"] = ":187447::::::::60:267::81:3:6652:1479:6646",
},
[13] =  {
   ["1"] = 14,
   ["2"] = 0,
   ["3"] = 236,
   ["4"] = ":190602::::::::60:267::27:4:8108:8145:6652:1482",
},
[14] =  {
   ["1"] = 15,
   ["2"] = 0,
   ["4"] = ":190605::::::::60:267::11:3:8113:6652:1485",
},
[15] =  {
   ["1"] = 16,
   ["2"] = 0,
   ["4"] = ":188050::::::::60:267::26:2:6652:1475",
},

playing 

[1] =  {
   ["1"] = 1,
   ["2"] = 1,
   ["3"] = 259,
   ["4"] = ":190620::::::::61:267::81:6:6652:7580:8133:8116:1505:6646",
},
[2] =  {
   ["1"] = 2,
   ["2"] = 0,
   ["3"] = 249,
   ["4"] = ":190635::::::::61:267::11:4:8114:6652:7578:1488",
},
[3] =  {
   ["1"] = 3,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190981::::::::61:267::11:4:8113:6652:7956:1485",
},
[4] =  {
   ["1"] = 5,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190978::::::::61:267::11:4:8113:7946:6652:1485",
},
[5] =  {
   ["1"] = 6,
   ["2"] = 0,
   ["3"] = 265,
   ["4"] = ":190469::::::::61:267::11:2:6652:7579",
},
[6] =  {
   ["1"] = 7,
   ["2"] = 0,
   ["3"] = 259,
   ["4"] = ":190621::::::::61:267::81:6:6652:8133:8116:43:1505:6646",
},
[7] =  {
   ["1"] = 8,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":188007::::::::61:267::28:5:6652:8093:8137:8131:1492",
},
[8] =  {
   ["1"] = 9,
   ["2"] = 0,
   ["3"] = 249,
   ["4"] = ":190348::::::::61:267::11:5:8114:7933:6652:7579:1488",
},
[9] =  {
   ["1"] = 10,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190343::::::::61:267::11:3:8113:6652:1485",
},
[10] =  {
   ["1"] = 11,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190632::::::::61:267::11:4:8113:6652:7578:1485",
},
[11] =  {
   ["1"] = 12,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190633::::::::61:267::11:4:8113:6652:7579:1485",
},
[12] =  {
   ["1"] = 13,
   ["2"] = 0,
   ["3"] = 233,
   ["4"] = ":187447::::::::61:267::81:3:6652:1479:6646",
},
[13] =  {
   ["1"] = 14,
   ["2"] = 0,
   ["3"] = 236,
   ["4"] = ":190602::::::::61:267::27:4:8108:8145:6652:1482",
},
[14] =  {
   ["1"] = 15,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190605::::::::61:267::11:3:8113:6652:1485",
},
[15] =  {
   ["1"] = 16,
   ["2"] = 0,
   ["3"] = 229,
   ["4"] = ":188050::::::::61:267::26:2:6652:1475",
},



returned to original code

playing
[1] =  {
   ["1"] = 1,
   ["2"] = 1,
   ["3"] = 259,
   ["4"] = ":190620::::::::61:267::81:6:6652:7580:8133:8116:1505:6646",
},
[2] =  {
   ["1"] = 2,
   ["2"] = 0,
   ["3"] = 249,
   ["4"] = ":190635::::::::61:267::11:4:8114:6652:7578:1488",
},
[3] =  {
   ["1"] = 3,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190981::::::::61:267::11:4:8113:6652:7956:1485",
},
[4] =  {
   ["1"] = 5,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190978::::::::61:267::11:4:8113:7946:6652:1485",
},
[5] =  {
   ["1"] = 6,
   ["2"] = 0,
   ["3"] = 265,
   ["4"] = ":190469::::::::61:267::11:2:6652:7579",
},
[6] =  {
   ["1"] = 7,
   ["2"] = 0,
   ["3"] = 259,
   ["4"] = ":190621::::::::61:267::81:6:6652:8133:8116:43:1505:6646",
},
[7] =  {
   ["1"] = 8,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":188007::::::::61:267::28:5:6652:8093:8137:8131:1492",
},
[8] =  {
   ["1"] = 9,
   ["2"] = 0,
   ["3"] = 249,
   ["4"] = ":190348::::::::61:267::11:5:8114:7933:6652:7579:1488",
},
[9] =  {
   ["1"] = 10,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190343::::::::61:267::11:3:8113:6652:1485",
},
[10] =  {
   ["1"] = 11,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190632::::::::61:267::11:4:8113:6652:7578:1485",
},
[11] =  {
   ["1"] = 12,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190633::::::::61:267::11:4:8113:6652:7579:1485",
},
[12] =  {
   ["1"] = 13,
   ["2"] = 0,
   ["3"] = 233,
   ["4"] = ":187447::::::::61:267::81:3:6652:1479:6646",
},
[13] =  {
   ["1"] = 14,
   ["2"] = 0,
   ["3"] = 236,
   ["4"] = ":190602::::::::61:267::27:4:8108:8145:6652:1482",
},
[14] =  {
   ["1"] = 15,
   ["2"] = 0,
   ["3"] = 246,
   ["4"] = ":190605::::::::61:267::11:3:8113:6652:1485",
},
[15] =  {
   ["1"] = 16,
   ["2"] = 0,
   ["3"] = 229,
   ["4"] = ":188050::::::::61:267::26:2:6652:1475",
},


loging in after reload
[1] =  {
   ["1"] = 1,
   ["2"] = 0,
   ["4"] = ":190620::::::::61:267::81:6:6652:7580:8133:8116:1505:6646",
},
[2] =  {
   ["1"] = 2,
   ["2"] = 0,
   ["4"] = ":190635::::::::61:267::11:4:8114:6652:7578:1488",
},
[3] =  {
   ["1"] = 3,
   ["2"] = 0,
   ["4"] = ":190981::::::::61:267::11:4:8113:6652:7956:1485",
},
[4] =  {
   ["1"] = 5,
   ["2"] = 0,
   ["4"] = ":190978::::::::61:267::11:4:8113:7946:6652:1485",
},
[5] =  {
   ["1"] = 6,
   ["2"] = 0,
   ["4"] = ":190469::::::::61:267::11:2:6652:7579",
},
[6] =  {
   ["1"] = 7,
   ["2"] = 0,
   ["4"] = ":190621::::::::61:267::81:6:6652:8133:8116:43:1505:6646",
},
[7] =  {
   ["1"] = 8,
   ["2"] = 0,
   ["4"] = ":188007::::::::61:267::28:5:6652:8093:8137:8131:1492",
},
[8] =  {
   ["1"] = 9,
   ["2"] = 0,
   ["4"] = ":190348::::::::61:267::11:5:8114:7933:6652:7579:1488",
},
[9] =  {
   ["1"] = 10,
   ["2"] = 0,
   ["4"] = ":190343::::::::61:267::11:3:8113:6652:1485",
},
[10] =  {
   ["1"] = 11,
   ["2"] = 0,
   ["4"] = ":190632::::::::61:267::11:4:8113:6652:7578:1485",
},
[11] =  {
   ["1"] = 12,
   ["2"] = 0,
   ["4"] = ":190633::::::::61:267::11:4:8113:6652:7579:1485",
},
[12] =  {
   ["1"] = 13,
   ["2"] = 0,
   ["4"] = ":187447::::::::61:267::81:3:6652:1479:6646",
},
[13] =  {
   ["1"] = 14,
   ["2"] = 0,
   ["4"] = ":190602::::::::61:267::27:4:8108:8145:6652:1482",
},
[14] =  {
   ["1"] = 15,
   ["2"] = 0,
   ["4"] = ":190605::::::::61:267::11:3:8113:6652:1485",
},
[15] =  {
   ["1"] = 16,
   ["2"] = 0,
   ["4"] = ":188050::::::::61:267::26:2:6652:1475",
},


in chat also say error on scheduler 
[17:13:00] openRaidLib: error on scheduler: updatePlayerData_Schedule [string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:572: in function `NewUniqueTimer'
[string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:1026: in function `functionToCallb

**Comment by Tercioo** [comment]
Thank you!
That's a lot of data for me work on

------ Original Message ------
From: "Addonman" ***@***.***>
To: "Tercioo/Details-Damage-Meter" 
***@***.***>
Cc: "Tercio Jose" ***@***.***>; "Comment" 
***@***.***>
Sent: 11-Dec-22 1:17:46 PM
Subject: Re: [Tercioo/Details-Damage-Meter] Bug in WD 10334 ALPHA 2 
10.0.2 (Issue #400)

**Comment by Tercioo** [comment]
hey, new alpha is available, it fixed this issues.
if it continues to happen, let me know.

**Comment by Addonman** [comment]
Ok.Logged in . No error so far.
