### ISSUE TITLE
/played and /details playedclass is spammed after killing mobs or when commands are used once

### ISSUE THREAD

**Issue by MarwanAl-Obaidi** [Tercioo/Details-Damage-Meter#403]
**Game and Details! version**
WOTLK Version: WD 10336 RELEASE 3.4.0

**Describe the bug**
- Steps to Reproduce
Typing /played, /details playedclass, or by killing mobs.

- Result (what happens when you follow the steps above):
The time played gets spammed for a few lines
![played](https://user-images.githubusercontent.com/56071948/207300286-2132a884-d613-4de5-bbdd-995ca9d8d377.PNG)

- Expected (what you think the expected behavior would be when following the steps):
A single line of the time played should be shown when /played or /details playedclass is used or nothing when a mob is killed.

- When the bug started?
12/13/2022
Details-Details.DF.Wrath.10336.148.zip

**Comment by Tercioo** [comment]
Thank you for reporting, using the command /details playedclass stops 
details from printing these messages.

------ Original Message ------
From: "Marwan Al-Obaidi" ***@***.***>
To: "Tercioo/Details-Damage-Meter" 
***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 13-Dec-22 8:10:42 AM
Subject: [Tercioo/Details-Damage-Meter] /played and /details playedclass 
is spammed after killing mobs or when commands are used once (Issue 
#403)
