### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Revnn** [Tercioo/Details-Damage-Meter#404]
**Game and Details! version**
WD 10335 RELEASE 10.0.2

- Expected (what you think the expected behavior would be when following the steps):
- Random during battles

- When the bug started (a date, wow path release, details update, etc)?
- With the latest update.

- Additional information:

**Lua Error**
Message: ...erface/AddOns/Details/Libs/LibOpenRaid/Functions.lua:57: attempt to get length of local 'table' (a nil value)
Time: Tue Dec 13 08:32:16 2022
Count: 3
Stack: ...erface/AddOns/Details/Libs/LibOpenRaid/Functions.lua:57: attempt to get length of local 'table' (a nil value)
[string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:1673: in function `SendAllGearInfo'
[string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:1533: in function <...face/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua:1532>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:548: in function <...face/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua:538>

Locals: <none>

**Comment by Revnn** [comment]
Guess you literally just fixed it.

**Comment by Tercioo** [comment]
yes thank you for reporting!

------ Original Message ------
From: "Revn" ***@***.***>
To: "Tercioo/Details-Damage-Meter" 
***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 13-Dec-22 8:50:35 AM
Subject: Re: [Tercioo/Details-Damage-Meter] Lua Error (Issue #404)
