### ISSUE TITLE
2x Details/Libs/LibOpenRaid/Functions.lua:57: attempt to get length of local 'table' (a nil value)

### ISSUE THREAD

**Issue by d4kir92** [Tercioo/Details-Damage-Meter#406]
2x Details/Libs/LibOpenRaid/Functions.lua:57: attempt to get length of local 'table' (a nil value)

**Comment by Flamanis** [comment]
Thanks for reporting. What version of the addon are you running on from `/details version`

**Comment by d4kir92** [comment]
i was using latest version on that point

**Comment by Flamanis** [comment]
Please could you get the in game output to make sure that is what is actually loaded?

**Comment by d4kir92** [comment]
![image](https://user-images.githubusercontent.com/23246564/208287339-628d0461-b97c-445c-b176-6e878e126204.png)

**Comment by Flamanis** [comment]
Thank you. Could you give any information regarding the character that this happened on including any information about where you were/what you did?

**Comment by d4kir92** [comment]
i ported out of a dungeon with hearthstone, then i got an error in loadingscreen/after loadingscreen

**Comment by d4kir92** [comment]
fixed
