### ISSUE TITLE
Details/Libs/LibOpenRaid/Functions.lua:57: attempt to get length of local 'table' (a nil value)

### ISSUE THREAD

**Issue by d4kir92** [Tercioo/Details-Damage-Meter#413]
4x Details/Libs/LibOpenRaid/Functions.lua:57: attempt to get length of local 'table' (a nil value)
[string "@Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:1673: in function `SendAllGearInfo'
[string "@Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:994: in function <...faceDetails/Libs/LibOpenRaid/LibOpenRaid.lua:989>
[string "=[C]"]: in function `xpcall'
[string "@Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:548: in function <...faceDetails/Libs/LibOpenRaid/LibOpenRaid.lua:538>

WD 10335 RELEASE 10.0.2

**Comment by d4kir92** [comment]
after hearthstone out of a m+ dungeon

**Comment by Flamanis** [comment]
What does `/run print("lib version:", LibStub:GetLibrary("LibOpenRaid-1.0").__version)` in game print out?

**Comment by d4kir92** [comment]
![image](https://user-images.githubusercontent.com/23246564/208499822-a4641a95-853c-4b69-a016-61db37d6b9e7.png)

**Comment by d4kir92** [comment]
only details has it:
![image](https://user-images.githubusercontent.com/23246564/208601950-53868b01-d604-4bd2-9f62-b17670b95843.png)


all addons up to date

**Comment by Flamanis** [comment]
If the version you get from `/details version` is WD 10335 RELEASE 10.0.2, then your addon is **NOT** up to date. Can you please get it to print again and see if you have 10337?

**Comment by d4kir92** [comment]
testing:
WD 10337 RELEASE 10.0.2

**Comment by Flamanis** [comment]
And if you run the `/run print("lib version:", LibStub:GetLibrary("LibOpenRaid-1.0").__version)` command again while it says 10337?

**Comment by d4kir92** [comment]
87

**Comment by Flamanis** [comment]
Should be fixed then as long as you're on those versions or greater. Let me know if it occurs again, and if it does, what those two commands output.

**Comment by d4kir92** [comment]
no error :D
