### ISSUE TITLE
10406.148 broke Auto Run Code function

### ISSUE THREAD

**Issue by comiluv** [Tercioo/Details-Damage-Meter#433]
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**
yes

**Game and Details! version**
Use /details to grab these two.
WD 10406 Release 10.0.2

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
1. /dt options
2. click Auto Run Code on leftmost pane
3. Under On Initialization event, paste this code
```lua
local b=ActionButton13 _MH=_MH or(b:SetAttribute("*type1","macro")or SecureHandlerWrapScript(b,"PreClick",b,'Z=IsShiftKeyDown()and 0 or(Z or 0)%8+1 self:SetAttribute("macrotext1","/wm [nomod]"..Z)'))or 1
```
4. Save and /reload

- Result (what happens when you follow the steps above):
```Details!: error running auto run script: on_init [string "..."]:31:attempt to index local 'b' (a nil value)```

- Expected (what you think the expected behavior would be when following the steps):
code runs without throwing errors

- When the bug started (a date, wow path release, details update, etc)?
updating to 10406.148 broke this

- Additional information:
if you ```local b=ActionButton12``` the code runs fine. This code only throws error when ```local b``` is assigned to ActionButton13 or higher.

**Comment by Flamanis** [comment]
This is not a bug with Details. That code is only put into the auto run code section to make it run after a reload. Nothing more. Not our problem.

**Comment by comiluv** [comment]
Appears to be the macro contains a bug
