### ISSUE TITLE
WOTLK Details not recording dps

### ISSUE THREAD

**Issue by Stevecrow13** [Tercioo/Details-Damage-Meter#442]
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**
Details is the only addon enabled

**Game and Details! version**
Use /details to grab these two.
WD 10409 RELEASE 3.4.1

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
- load a character

- Result (what happens when you follow the steps above):
- Details does not show dps meters.  Tiny threat does still work though

- Expected (what you think the expected behavior would be when following the steps):
- Dps meters to work

- When the bug started (a date, wow path release, details update, etc)?
- Started after the Ulduar update

- Additional information:
- I've uninstalled and reinstalled the addon, as well as removed the details files from the WTF folder.

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*
Message: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
Time: Fri Jan 27 09:02:43 2023
Count: 4
Stack: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface/AddOns/Details/Libs/DF/fw.lua"]:3185: in function `Mixin'
[string "@Interface/AddOns/Details/classes/class_heal.lua"]:111: in function `funcao_de_criacao'
[string "@Interface/AddOns/Details/classes/container_actors.lua"]:732: in function `PegarCombatente'
[string "@Interface/AddOns/Details/core/parser.lua"]:2401: in function <Interface/AddOns/Details/core/parser.lua:2286>
[string "=(tail call)"]: ?

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Screenshots**
Post images of the bug if necessary.

**Combat Log**
Include a link to a combatlog file if the error is about not detecting a skill, usable item or item proc.
The log can be as simple as hitting a mob with white damage and using the item/skill.

**Other Information**
The LUA error doesn't show with other add

**Comment by Stevecrow13** [comment]
Another LUA error is:

Message: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
Time: Fri Jan 27 09:02:44 2023
Count: 1
Stack: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface/AddOns/Details/Libs/DF/fw.lua"]:3185: in function `Mixin'
[string "@Interface/AddOns/Details/classes/class_damage.lua"]:494: in function `funcao_de_criacao'
[string "@Interface/AddOns/Details/classes/container_actors.lua"]:732: in function `PegarCombatente'
[string "@Interface/AddOns/Details/core/parser.lua"]:1026: in function <Interface/AddOns/Details/core/parser.lua:674>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by Tercioo** [comment]
Hello!
Have you tested with latest version? 10410

------ Original Message ------
From: "Stevecrow13" ***@***.***>
To: "Tercioo/Details-Damage-Meter" 
***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 27-Jan-23 11:03:49 AM
Subject: Re: [Tercioo/Details-Damage-Meter] WOTLK Details not recording 
dps (Issue #442)

**Comment by Stevecrow13** [comment]
That wasn't available last night via curseforge.  I just updated it am am getting the error's below:
--------------------------------------------------
Message: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
Time: Fri Jan 27 11:39:18 2023
Count: 1
Stack: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface/AddOns/Details/Libs/DF/fw.lua"]:3185: in function `Mixin'
[string "@Interface/AddOns/Details/classes/class_utility.lua"]:181: in function `funcao_de_criacao'
[string "@Interface/AddOns/Details/classes/container_actors.lua"]:732: in function `PegarCombatente'
[string "@Interface/AddOns/Details/core/parser.lua"]:3619: in function `add_buff_uptime'
[string "@Interface/AddOns/Details/classes/class_utility.lua"]:1622: in function `CatchRaidBuffUptime'
[string "@Interface/AddOns/Details/core/control.lua"]:364: in function `EntrarEmCombate'
[string "@Interface/AddOns/Details/core/parser.lua"]:995: in function <Interface/AddOns/Details/core/parser.lua:674>
[string "=(tail call)"]: ?

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

---------------------------------------------------------------
Message: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
Time: Fri Jan 27 11:40:19 2023
Count: 15
Stack: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface/AddOns/Details/Libs/DF/fw.lua"]:3185: in function `Mixin'
[string "@Interface/AddOns/Details/classes/class_utility.lua"]:181: in function `funcao_de_criacao'
[string "@Interface/AddOns/Details/classes/container_actors.lua"]:732: in function `PegarCombatente'
[string "@Interface/AddOns/Details/core/parser.lua"]:4173: in function <Interface/AddOns/Details/core/parser.lua:4144>
[string "=(tail call)"]: ?

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
----------------------------------------------------------
Message: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
Time: Fri Jan 27 11:40:19 2023
Count: 17
Stack: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface/AddOns/Details/Libs/DF/fw.lua"]:3185: in function `Mixin'
[string "@Interface/AddOns/Details/classes/class_damage.lua"]:494: in function `funcao_de_criacao'
[string "@Interface/AddOns/Details/classes/container_actors.lua"]:732: in function `PegarCombatente'
[string "@Interface/AddOns/Details/core/parser.lua"]:1026: in function <Interface/AddOns/Details/core/parser.lua:674>
[string "=(tail call)"]: ?

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
-------------------------------------------------------------------------
Message: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
Time: Fri Jan 27 11:39:44 2023
Count: 3
Stack: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface/AddOns/Details/Libs/DF/fw.lua"]:3185: in function `Mixin'
[string "@Interface/AddOns/Details/classes/class_utility.lua"]:181: in function `funcao_de_criacao'
[string "@Interface/AddOns/Details/classes/container_actors.lua"]:732: in function `PegarCombatente'
[string "@Interface/AddOns/Details/classes/container_actors.lua"]:708: in function `PegarCombatente'
[string "@Interface/AddOns/Details/core/parser.lua"]:4173: in function <Interface/AddOns/Details/core/parser.lua:4144>
[string "=(tail call)"]: ?

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
--------------------------------------------------------------------------------------
Message: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
Time: Fri Jan 27 11:39:28 2023
Count: 1
Stack: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface/AddOns/Details/Libs/DF/fw.lua"]:3185: in function `Mixin'
[string "@Interface/AddOns/Details/classes/class_utility.lua"]:181: in function `funcao_de_criacao'
[string "@Interface/AddOns/Details/classes/container_actors.lua"]:732: in function `PegarCombatente'
[string "@Interface/AddOns/Details/core/parser.lua"]:3619: in function `add_buff_uptime'
[string "@Interface/AddOns/Details/classes/class_utility.lua"]:1622: in function `CatchRaidBuffUptime'
[string "@Interface/AddOns/Details/core/control.lua"]:481: in function `SairDoCombate'
[string "@Interface/AddOns/Details/core/parser.lua"]:5916: in function <Interface/AddOns/Details/core/parser.lua:5887>
[string "=(tail call)"]: ?

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
-----------------------------------------------------------------------------------
Message: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
Time: Fri Jan 27 11:40:06 2023
Count: 1
Stack: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface/AddOns/Details/Libs/DF/fw.lua"]:3185: in function `Mixin'
[string "@Interface/AddOns/Details/classes/class_damage.lua"]:494: in function `funcao_de_criacao'
[string "@Interface/AddOns/Details/classes/container_actors.lua"]:732: in function `PegarCombatente'
[string "@Interface/AddOns/Details/core/parser.lua"]:1863: in function <Interface/AddOns/Details/core/parser.lua:1832>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
--------------------------------------------------------------------------------------
Message: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
Time: Fri Jan 27 11:40:11 2023
Count: 3
Stack: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface/AddOns/Details/Libs/DF/fw.lua"]:3185: in function `Mixin'
[string "@Interface/AddOns/Details/classes/class_resources.lua"]:88: in function `funcao_de_criacao'
[string "@Interface/AddOns/Details/classes/container_actors.lua"]:732: in function `PegarCombatente'
[string "@Interface/AddOns/Details/core/parser.lua"]:3843: in function <Interface/AddOns/Details/core/parser.lua:3804>
[string "=(tail call)"]: ?

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
---------------------------------------------------------------------------------
Message: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
Time: Fri Jan 27 11:40:17 2023
Count: 3
Stack: Interface/AddOns/Details/Libs/DF/fw.lua:3185: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface/AddOns/Details/Libs/DF/fw.lua"]:3185: in function `Mixin'
[string "@Interface/AddOns/Details/classes/class_damage.lua"]:494: in function `funcao_de_criacao'
[string "@Interface/AddOns/Details/classes/container_actors.lua"]:732: in function `PegarCombatente'
[string "@Interface/AddOns/Details/core/parser.lua"]:1026: in function <Interface/AddOns/Details/core/parser.lua:674>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
----------------------------------------------------------------

**Comment by Flamanis** [comment]
You manually updated and overwrote the old folder. Delete the old folder and install again.

**Comment by Stevecrow13** [comment]
That worked!  I used the reinstall option in Curseforge to try and fix the option.  Thank you so much for your help!
