### ISSUE TITLE
[Feature Request] Large Warning for Tank / Heal Deaths

### ISSUE THREAD

**Issue by mpalermo73** [Tercioo/Details-Damage-Meter#446]
**Game and Details! version**
Use /details to grab these two.
WD: 10410
Release: 10.0.1

---

More Wish List than "bug".  I am thankful that Details! can announce deaths in the chat.  What I'm hoping for is a large on-screen warning specifically for tank and/or heals deaths.  I main a DK so I have BRez available.  It would be handy to have a big, in-your-face, warning.  DBM, for example, flashes big warnings on the screen for things.

**Comment by Flamanis** [comment]
That is something that is more in touch with a weakaura. See if there's one already made on wago.

**Comment by mpalermo73** [comment]
OK, fair enough!
