### ISSUE TITLE
[Feature] Window Backdrop Color

### ISSUE THREAD

**Issue by Stefan7s** [Tercioo/Details-Damage-Meter#451]
Hi,

I wanted to know if the option to change the window backdrop color and transparency could be added in the future ? Or if there is a way to change it currently in the code ? and if so how please ?

Stefan

**Comment by Flamanis** [comment]
I suspect you're refering to the "Rows Area Color" in the Window Body section of Details options

**Comment by Stefan7s** [comment]
I'm blind, it's there, thank you.
