### ISSUE TITLE
Segments Locked no longer works

### ISSUE THREAD

**Issue by danpk1** [Tercioo/Details-Damage-Meter#483]
Enabling the segments Locked in display options no longer works. Windows always showing different segments

**Comment by Flamanis** [comment]
Need version outputs please. There should have been a format when opening this issue to follow

**Comment by Flamanis** [comment]
Issue has been found and fixed. Most recent release should have it.

Please for future, follow the prefilled guide for reporting issues.

**Comment by danpk1** [comment]
Will do and thanks for the update - all sorted
