### ISSUE TITLE
row.iconHighlight texture not properly updating when scrolling down, when staying at the same bar position with cursor

### ISSUE THREAD

**Issue by Undisclosed-Information** [Tercioo/Details-Damage-Meter#491]
How to reproduce
-----------------------

1. Put your cursor on a bar
2. dont move the cursor, only scroll down
3. if you look closely you will see that an old icon (from the first time your entered the bar with your cursor before scrolling) is visible through the row.icone_classe texture.

This should be a simple fix to resolve. Thanks in advance.

**Comment by decod3d** [comment]
credits go straight to my high resolution screen 😆
