### ISSUE TITLE
Background color not correctly applied in options panel, because of a leaking global variable

### ISSUE THREAD

**Issue by Undisclosed-Information** [Tercioo/Details-Damage-Meter#495]
The background color setting in Bars: General > Background > Color is not correctly applied, because the internal function is assigning an empty global variable to the color table, see [window_options2_sections.lua#L1353](https://github.com/Tercioo/Details-Damage-Meter/blob/281868aaec71c586bca6718c43d189b4cf79529d/frames/window_options2_sections.lua#L1353)

```LUA
{--background color
     type = "color",
     get = function()
          local r, g, b = unpack(currentInstance.row_info.fixed_texture_background_color)
          local alpha = currentInstance.row_info.alpha --unused assignment
          return {r, g, b, a} --leaking global 'a'
     end,
     set = function(self, r, g, b, a)
          editInstanceSetting(currentInstance, "SetBarSettings", nil, nil, nil, nil, nil, nil, {r, g, b, a})
          afterUpdate()
     end,
     name = Loc ["STRING_COLOR"],
     desc = Loc ["STRING_OPTIONS_BAR_COLOR_DESC"],
},
```

Solution
-----------------------
```LUA
{--background color
     type = "color",
     get = function()
          local r, g, b, a = unpack(currentInstance.row_info.fixed_texture_background_color)
          return {r, g, b, a}
     end,
     set = function(self, r, g, b, a)
          editInstanceSetting(currentInstance, "SetBarSettings", nil, nil, nil, nil, nil, nil, {r, g, b, a})
          afterUpdate()
     end,
     name = Loc ["STRING_COLOR"],
     desc = Loc ["STRING_OPTIONS_BAR_COLOR_DESC"],
},

**Comment by decod3d** [comment]
The same applies to [window_options2_sections.lua#L1282](https://github.com/Tercioo/Details-Damage-Meter/blob/281868aaec71c586bca6718c43d189b4cf79529d/frames/window_options2_sections.lua#L1282)

**Comment by decod3d** [comment]
even if the alpha value is internally stored with value 0, opening the selector instantly puts it back to alpha 1. With that said it definitely does effect the application.

Here is another I found... [window_options2_sections.lua#L2020](https://github.com/Tercioo/Details-Damage-Meter/blob/281868aaec71c586bca6718c43d189b4cf79529d/frames/window_options2_sections.lua#L2020)

**Comment by Flamanis** [comment]
Oh absolutely yes. It would effect that since it would reset the selector. As I said, an issue to be sure. I'll get to adding it to a fix, thanks for reporting.
