### ISSUE TITLE
Multiple WotLK Errors

### ISSUE THREAD

**Issue by stratoru** [Tercioo/Details-Damage-Meter#512]
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**

**Game and Details! version**
DETAILS! VERSION: WD10737 ALPHA 48 3.4.1

Locals:
Skipped (In Encounter)

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen): 
BUG 1: Go into combat in WotLK.
BUG 2 (Player Breakdown): Click player DPS bar in damage window.

- Result (what happens when you follow the steps above):
BUG 1: Receive error. No known adverse event occurs.
BUG 2: Bugged appearing player breakdown window pops up. Get error. 

- Expected (what you think the expected behavior would be when following the steps):
BUG 1: N/A
BUG 2: Normal Player breakdown window appears.

- When the bug started (a date, wow path release, details update, etc)?
Today.

- Additional information:
This is the second similar error this week. A playerbreakdown bug occured earlier in the week and was fixed initially, but has returned. 

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*
BUG 1: 
```
21x Details/core/parser.lua:3717: attempt to index local 'cooldownInfo' (a boolean value)
[string "@Details/core/parser.lua"]:3717: in function <Details/core/parser.lua:3669>
[string "=(tail call)"]: ?
```

BUG 2: 

```
3x ...Ons/Details/frames/window_playerbreakdown_spells.lua:1959: attempt to index local 'actorObject' (a nil value)
[string "@Details/frames/window_playerbreakdown_spells.lua"]:1959: in function <...Ons/Details/frames/window_playerbreakdown_spells.lua:1932>
```

```
7x ...Ons/Details/frames/window_playerbreakdown_spells.lua:527: attempt to index local 'spellTable' (a nil value)
[string "@Details/frames/window_playerbreakdown_spells.lua"]:527: in function <...Ons/Details/frames/window_playerbreakdown_spells.lua:470>

```

```
15x Details/Libs/DF/fw.lua:3349: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Details/Libs/DF/fw.lua"]:3349: in function `Mixin'
[string "@Details/classes/class_damage.lua"]:4578: in function <Details/classes/class_damage.lua:4487>
[string "=(tail call)"]: ?
[string "@Details/frames/window_playerbreakdown.lua"]:306: in function `OpenBreakdownWindow'
[string "@Details/frames/window_main.lua"]:2003: in function <Details/frames/window_main.lua:1952>


```
**Screenshots**
Post images of the bug if necessary.

**Combat Log**
Include a link to a combatlog file if the error is about not detecting a skill, usable item or item proc.
The log can be as simple as hitting a mob with white damage and using the item/skill.

**Other Information**
If necessary, add more info here.

**Comment by Flamanis** [comment]
Bug 1 is a legit bug. Bug 2 is from you not installing/updating correctly.

Delete your folders and reinstall. When updating addons, always treat it like a clean install. Remove old folders and install new ones. Do not overwrite.

**Comment by Flamanis** [comment]
Bug 1 should be fixed with most recent Alpha

**Comment by stratoru** [comment]
> 

So updating via CurseForge app is not supported?

**Comment by Flamanis** [comment]
It is. The mixin issue is indicative of a manual install

**Comment by Flamanis** [comment]
I found the actual issue. New file was added but not added to Wrath TOC. #517 addresses it.

**Comment by stratoru** [comment]
Thanks. Didn't think I had manually installed anything. Glad to hear I wasn't losing my mind!
