### ISSUE TITLE
Would you be interested in making use of the new addon compartment feature?

### ISSUE THREAD

**Issue by brittyazel** [Tercioo/Details-Damage-Meter#519]
Hi @Tercioo,

In 10.0 Blizzard added the new [addon compartment](https://wowpedia.fandom.com/wiki/Addon_compartment) feature to replace the need for minimap icons. It was further refined in 10.1, and it looks like a pretty nice addition to the base UI. (Granted, afaik it only exists in retail for right now).

Likewise, Meorawr has created a support library called [LibDBCompartment](https://github.com/Meorawr/LibDBCompartment) that is meant to mirror LibDBIcon to the best of its ability. 

Would you be interested in a feature such as this? I'd be happy to implement it myself and submit a PR. It could be as simple as defaulting to LibDBCompartment for retail and keeping LibDBIcon for classic/classic-era.

**Comment by Tercioo** [comment]
Hey man, I'm not interested, but thanks for offering.

**Comment by brittyazel** [comment]
Oh, alright. Do you mind me asking why?

**Comment by Bareno** [comment]
Seconding that, would be nice to know why, would be really nice to have the minimap button gone and instead have an option in that nice frame.

https://www.reddit.com/r/wow/comments/13a7hwf/addon_developers_please_start_using_the_new/

**Comment by Tercioo** [comment]
> 

hey, of course, it's 15 lines of code to implement it into the compartment, no need yet another library. but thanks for offering man.

**Comment by funkydude** [comment]
Support for this was added to LibDBIcon to make the process as easy as possible for devs, but it's their choice if they want to support it or not. If they've said no, don't nag them, just run the following in game on any addon you wish that's using LibDBIcon to create minimap buttons (virtually all of them):

`/run LibStub("LibDBIcon-1.0"):AddButtonToCompartment("Details")`

**Comment by brittyazel** [comment]
@funkydude apologies if I came off as "nagging". My intention was to be as polite and respectful as possible.
