### ISSUE TITLE
Bug: newly created windows dont always inherit custom settings such as font etc.

### ISSUE THREAD

**Issue by Rezy942** [Tercioo/Details-Damage-Meter#535]
As title says - this issue has been plagueing this amazing addon for years now.
As you can see below - 2 top windows were made on day 1 of setting up fresh details options. I changed everything, font, sizes, layout, etc.

Fast forward few days later, same exact logic - i create 2 more windows via Window Control -> Create window
Except this time the new window act like Details was just installed fresh. No idea why.

Is this a bug or is there a way to force these windows to inherit the "parent" window settings?

Example:
![image](https://github.com/Tercioo/Details-Damage-Meter/assets/122007087/d6a6030a-41ce-4b6d-b4ba-c2bced275ec4)

**Comment by Flamanis** [comment]
Skins->Apply to All Windows button, when you have selected one of the other ones in the dropdown at the bottom right

**Comment by Rezy942** [comment]
Thank you! That worked! Didnt know about that feature.
Its very weird though how first time i created 2nd window it took the settings of 1st one, then later that stopped.
Something wonky is going on.
Anyways, problem fixed, thanks!
