### ISSUE TITLE
Spell Reflect damage

### ISSUE THREAD

**Issue by Musouv** [Tercioo/Details-Damage-Meter#56]
There has been a weakaura going around recently that shows spellreflect damage attributed to the player that reflects here: https://wago.io/IwPukH70B
However it does have a few issues as stated by the author that would be fixed if implemented by default into details. Would it be possible to add this as a default plugin/option and fix the issues listed?

**Comment by athei** [comment]
Please consider doing that. It would be extremely helpful.
