### ISSUE TITLE
[Classic] LUA errors in BGs

### ISSUE THREAD

**Issue by 0anth** [Tercioo/Details-Damage-Meter#58]
**Game and Details! version**
Details!: DETAILS! VERSION: C197
Details!: GAME VERSION: v1.13.3

**Describe the bug**
LUA error appears shortly after starting a BG, roughly when first combat begins. Details remains empty until leaving BGs and clearing all data.

There are a few different errors, but I believe this is the first one to appear. I can supply a combatlog, but this error happens every time, before I ever have a chance to attack anyone. 

Error has been occurring since I started doing BGs, I've only just decided to report it, seeing other people have the same issue with no solution.

**Lua Error**

> Date: 2020-03-23 09:15:57 
> ID: 1 
> Error occured in: Global 
> Count: 9 
> Message: ..\AddOns\Details\core\parser.lua line 1717: 
>    attempt to perform arithmetic on field 'total' (a nil value) 
> Debug: 
>    Details\core\parser.lua:1717: 
>       Details\core\parser.lua:1537 
>    (tail call): ? 
>    (tail call): ? 
> Locals: 
> self = <table> { 
>  WipeSourceCache = <function> defined @Interface\AddOns\Details\core\parser.lua:3646
>  swing = <function> defined @Interface\AddOns\Details\core\parser.lua:306
>  buff = <function> defined @Interface\AddOns\Details\core\parser.lua:1825
>  energize = <function> defined @Interface\AddOns\Details\core\parser.lua:2723
>  dispell = <function> defined @Interface\AddOns\Details\core\parser.lua:3167
>  spellcast = <function> defined @Interface\AddOns\Details\core\parser.lua:3070
>  spell_dmg = <function> defined @Interface\AddOns\Details\core\parser.lua:421
>  unbuff = <function> defined @Interface\AddOns\Details\core\parser.lua:2200
>  SLT_damage = <function> defined @Interface\AddOns\Details\core\parser.lua:1097
>  add_defensive_cooldown = <function> defined @Interface\AddOns\Details\core\parser.lua:2858
>  rangemissed = <function> defined @Interface\AddOns\Details\core\parser.lua:1208
>  buff_refresh = <function> defined @Interface\AddOns\Details\core\parser.lua:2067
>  heal = <function> defined @Interface\AddOns\Details\core\parser.lua:1537
>  environment = <function> defined @Interface\AddOns\Details\core\parser.lua:3616
>  RevomeActorFromCache = <function> defined @Interface\AddOns\Details\core\parser.lua:5059
>  RefreshFunctions = <function> defined @Interface\AddOns\Details\core\parser.lua:3940
>  heal_absorb = <function> defined @Interface\AddOns\Details\core\parser.lua:1495
>  range = <function> defined @Interface\AddOns\Details\core\parser.lua:311
>  heal_denied = <function> defined @Interface\AddOns\Details\core\parser.lua:1416
>  SetParserFunction = <function> defined @Interface\AddOns\Details\core\parser.lua:3887
>  original_functions = <table> {
>  }
>  dead = <function> defined @Interface\AddOns\Details\core\parser.lua:3441
>  ress = <function> defined @Interface\AddOns\Details\core\parser.lua:3259
>  add_buff_uptime = <function> defined @Interface\AddOns\Details\core\parser.lua:2525
>  interrupt = <function> defined @Interface\AddOns\Details\core\parser.lua:2963
>  break_cc = <function> defined @Interface\AddOns\Details\core\parser.lua:3355
>  add_debuff_uptime = <function> defined @Interface\AddOns\Details\core\parser.lua:2485
>  summon = <function> defined @Interface\AddOns\Details\core\parser.lua:1335
>  swingmissed = <function> defined @Interface\AddOns\Details\core\parser.lua:1204
>  MonkStagger_damage = <function> defined @Interface\AddOns\Details\core\parser.lua:889
>  add_cc_done = <function> defined @Interface\AddOns\Details\core\parser.lua:1981
>  add_bad_debuff_uptime = <function> defined @Interface\AddOns\Details\core\parser.lua:2324
>  SLT_healing = <function> defined @Interface\AddOns\Details\core\parser.lua:1764
>  LOTM_damage = <function> defined @Interface\AddOns\Details\core\parser.lua:1031
>  missed = <function> defined @Interface\AddOns\Details\core\parser.lua:1213
> }
> token = "SPELL_ABSORBED"
> time = 1584926157.240000
> who_serial = "Pet-0-4389-30-5339-1860-0200155E24"
> who_name = "Ormkath <Quix-Windseeker>"
> who_flags = 4372
> alvo_serial = "Player-4727-0131EA97"
> alvo_name = "Quix-Windseeker"
> alvo_flags = 1300
> alvo_flags2 = 0
> spellid = "Sacrifice"
> spellname = "Sacrifice"
> spelltype = 32
> amount = 142
> overhealing = 0
> absorbed = 0
> critical = nil
> is_shield = true
> cura_efetiva = 142
> este_jogador = <table> {
>  flag_original = 4372
>  totalabsorb = 142.008580
>  last_hps = 0
>  timeMachine = 38
>  healing_from = <table> {
>  }
>  iniciar_hps = true
>  targets = <table> {
>  }
>  start_time = 1584926157
>  pets = <table> {
>  }
>  totalover_without_pet = 0.008580
>  targets_absorbs = <table> {
>  }
>  healing_taken = 0.008580
>  totalover = 0.008580
>  total_without_pet = 142.008580
>  owner = <table> {
>  }
>  classe = "PET"
>  serial = "Pet-0-4389-30-5339-1860-0200155E24"
>  total = 142.008580
>  targets_overheal = <table> {
>  }
>  ownerName = "Quix-Windseeker"
>  nome = "Ormkath <Quix-Windseeker>"
>  spells = <table> {
>  }
>  heal_enemy_amt = 0
>  displayName = "Ormkath <Quix>"
>  heal_enemy = <table> {
>  }
>  last_event = 1584926157
>  custom = 0
>  tipo = 2
>  on_hold = false
>  totaldenied = 0.008580
>  delay = 0
>  pvp = true
> }
> meu_dono = <table> {
>  flag_original = 1300
>  totalabsorb = 0.005147
>  last_hps = 0
>  healing_from = <t
> AddOns:
>   Swatter, v8.2.6377 (SwimmingSeadragon)
>   WowheadLooter, v11304
>   AdiBags, vv1.9.17-classic
>   AdvancedInterfaceOptions, v1.3.4
>   Atlas, vv1.47.00.11303.00
>   AtlasClassicWoW, vv1.47.00.11303.00
>   AtlasLootClassic, vv1.4.7
>   AtlasLootClassicData, vv1.4.7
>   AtlasLootClassicDungeonsAndRaids, vv1.4.7
>   AucAdvanced, v8.2.6430 (SwimmingSeadragon)
>   AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
>   AucScanData, v8.2.6365 (SwimmingSeadragon)
>   AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
>   AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
>   AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
>   AucStatSimple, v8.2.6399 (SwimmingSeadragon)
>   AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
>   AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
>   BagFreeSpaceCounter, v1.0.3
>   BankItems, v2.5
>   BeanCounter, v8.2.6434 (SwimmingSeadragon)
>   CharacterStatsClassic, v3.3.3
>   ClassicAuraDurations, v
>   ClassicCastbars, vv1.3.0
>   ClassicCastbarsOptions, v
>   ClassicLootAssistant, v
>   ClassicSpellActivations, v
>   ClassicWorldMapEnhanced, v1.1-Release
>   DBMCore, v1.13.41
>   DBMDefaultSkin, v
>   DBMPvP, vr86
>   DBMStatusBarTimers, v
>   Details, v
>   DetailsTinyThreat, v
>   eCastingBar, v1.3.0
>   Enchantrix, v8.2.6428 (SwimmingSeadragon)
>   EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
>   ExtendedCharacterStats, v2.2.1
>   ExtVendorUIClassic, v1.0.4
>   FADEWorldTimers, v1.0
>   GatherMate2, v1.45.5
>   GTFO, v4.55
>   HandyNotes, vv1.5.9
>   HandyNotesDungeonLocationsClassic, v1.03
>   HandyNotesFlightMastersClassic, v1.06
>   HandyNotesNPCsClassic, v1.22
>   HandyNotesTravelGuideClassic, vv2.1.6
>   HealBotData, v1.13.4.0
>   HealBoten, v1.13.4.0
>   HealBotOptions, v1.13.4.0
>   HealCommClassic, v
>   honorspy, v1.7.3
>   InFlightLoad, v1.13.005
>   Informant, v8.2.6374 (SwimmingSeadragon)
>   LetMeCast, v1.3
>   MizusRaidTracker, vv0.84.4-classic
>   ModernQuestWatch, v1.0.9
>   NeatPlates, v1.13.4.2
>   NeatPlatesAlvara, v5a
>   NeatPlatesBlizzardPlates, v2.0
>   NeatPlatesClassicPlates, v
>   NeatPlatesGraphite, v
>   NeatPlatesGrey, v
>   NeatPlatesNeon, v
>   NeatPlatesQuatre, v
>   NeatPlatesRenaitre, vv7.0.3
>   NeatPlatesRoth, v
>   NeatPlatesSimple, v7.3.0
>   NeatPlatesSlimHorizontal, v2.2
>   NeatPlatesSlimVertical, v2.2
>   NeatPlatesHub, v
>   NeatPlatesWidgets, v
>   NugRunning, v1.13.36
>   OmniCC, v8.1.1
>   Prat30, v3.7.50
>   Prat30Libraries, v
>   QuestFrameFixer, v1.1.1
>   QuestIconDesaturation, v3.1
>   Questie, v5.10.0 0 fd3ff918
>   RCLootCouncilClassic, v0.7.2
>   Recount, vv1.13.4a
>   RollTrackerClassic, v2.21
>   Scrap, v8.3.2
>   ShadowedUnitFrames, vv4.2.3-Classic
>   ShardLock, v0.1.0
>   SlideBar, v8.2.6375 (SwimmingSeadragon)
>   Stubby, v8.2.6376 (SwimmingSeadragon)
>   ThreatClassic2, v2.12
>   TitanClassic, v1.2.1.11304
>   TitanClassicAmmo, v1.2.1.11304
>   TitanClassicBag, v1.2.1.11304
>   TitanClassicClock, v1.2.1.11304
>   TitanClassicGold, v1.2.1.11304
>   TitanClassicLocation, v1.2.1.11304
>   TitanClassicLootType, v1.2.1.11304
>   TitanClassicMail, v1.0.0.1
>   TitanClassicPerformance, v1.2.1.11304
>   TitanClassicReagentTracker, v1.0.911304
>   TitanClassicRegen, v1.2.1.11304
>   TitanClassicRepair, v1.2.1.11304
>   TitanClassicVolume, v1.2.1.11304
>   TitanClassicXP, v1.2.1.11304
>   TitanProfession, vv1.2-classic
>   TitanProfessionsMulti, v1.4
>   TitanSpacer, v1.2
>   VendorPrice, v1.3.1
>   WeakAuras, v2.16.6
>   WhatsTraining, v1.8.7
>   XckRaidSubManager, v2.0
>   BlizRuntimeLib_enUS v1.13.4.11304 <none>
>   (ck=cfd)

**Comment by Tercioo** [comment]
Old issue, It's already fixed.
