### ISSUE TITLE
Update blurred icon in details meter (Evoker Aug)

### ISSUE THREAD

**Issue by Mithras2801** [Tercioo/Details-Damage-Meter#590]
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**

**Game and Details! version**
Game - 10.1.5 (50791) (release x64)
Details - VWD 11856 RELEASE 10.1.5

**Describe the bug**
- Steps to Reproduce 
- Do DMG/Healing etc
- We see blurred icon evoker augmentation

- Additional information:
Upgrade icon pls

**Screenshots**
![Details icon evoker](https://github.com/Tercioo/Details-Damage-Meter/assets/6137838/99b081a1-50e9-4631-9e62-679f044b0b17)

![Details version](https://github.com/Tercioo/Details-Damage-Meter/assets/6137838/ddc55c3c-a6d8-447e-aabb-b4541e8dcdc1)

**Comment by Mithras2801** [comment]
https://www.wowhead.com/icon=5198700/classicon-evoker-augmentation

**Comment by LEGOL2** [comment]
I've created a pr #591

**Comment by Flamanis** [comment]
#571 has been there for a while for this exact purpose. Honestly, I haven't really looked at why it hasn't been merged yet.

**Comment by Mithras2801** [comment]
> #571 has been there for a while for this exact purpose. Honestly, I haven't really looked at why it hasn't been merged yet.

When will the amendment to the Augmentation icon addon be introduced??
