### ISSUE TITLE
Wow crash upon loading in

### ISSUE THREAD

**Issue by Konsafloof** [Tercioo/Details-Damage-Meter#602]
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**

**Game and Details! version**
WoW 10.1.7.51187
Cant get addon version

**Describe the bug**
Upon loading into character game instantly crashes

**Lua Error**
No Lua errors

**Screenshots**
![Wow_l35jMZ82rm](https://github.com/Tercioo/Details-Damage-Meter/assets/109347817/6a167ef4-c188-4ee6-bc75-cc19b88f56c3)

**Combat Log**
No Combat Log

**Other Information**
[2023-09-06 08.54.04 Crash - 7736.txt](https://github.com/Tercioo/Details-Damage-Meter/files/12537481/2023-09-06.08.54.04.Crash.-.7736.txt)

**Comment by Flamanis** [comment]
Any information about what class/race?

**Comment by Tercioo** [comment]
Oh, crashes are a blizzard thing, please post your crash dump at:
https://us.forums.blizzard.com/en/wow/c/support/technical-support/15
They get to you fast there.
