### ISSUE TITLE
Tidy Threat

### ISSUE THREAD

**Issue by webphut** [Tercioo/Details-Damage-Meter#61]
Show threat of raid/party members while healing group/raid members. 

I know I can target hostile mobs and threat will show, but I want tidy threat to show threat while targeting my group/raid members too. 

May it be possible you can make changes so this will work that way?

**Comment by webphut** [comment]
Why have a comment section if you won’t reply back to questions?

**Comment by Tercioo** [comment]
It's being implemented, thank you!
