### ISSUE TITLE
[DF] Sporadic errors in battlegrounds (attempt to perform arithmetic on a boolean value)

### ISSUE THREAD

**Issue by Railander** [Tercioo/Details-Damage-Meter#621]
VWD 12019 RELEASE 10.1.7

Very sporadic bug during bgs, don't really know how to reproduce on my end.
Usually happens in the middle of the match at no particular moment, and tends to pop up multiple times in quick succession and then stopping.
My best guess is it may have to do with new players joining mid game, had a match just now where a new enemy player spawned next to me and soon after targeting and attacking them i got the error twice in a row.

Message: Interface/AddOns/Details/core/parser.lua:2557: attempt to perform arithmetic on a boolean value
Time: Tue Oct 31 06:54:34 2023
Count: 1
Stack: Interface/AddOns/Details/core/parser.lua:2557: attempt to perform arithmetic on a boolean value
[string "=[C]"]: ?
[string "@Interface/AddOns/Details/core/parser.lua"]:2557: in function <Interface/AddOns/Details/core/parser.lua:2378>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by Tercioo** [comment]
Thank you, the error got documented and should get a fix soon.


------ Original Message ------
From "Railander" ***@***.******@***.***>>
To "Tercioo/Details-Damage-Meter" ***@***.******@***.***>>
Cc "Subscribed" ***@***.******@***.***>>
Date 31-Oct-23 7:33:40 AM
Subject [Tercioo/Details-Damage-Meter] [DF] Sporadic errors in battlegrounds (attempt to perform arithmetic on a boolean value) (Issue #621)


VWD 12019 RELEASE 10.1.7

Very sporadic bug during bgs, don't really know how to reproduce on my end.
Usually happens in the middle of the match at no particular moment, and tends to pop up multiple times in quick succession and then stopping.
My best guess is it may have to do with new players joining mid game, had a match just now where a new enemy player spawned next to me and soon after targeting and attacking them i got the error twice in a row.

Message: Interface/AddOns/Details/core/parser.lua:2557: attempt to perform arithmetic on a boolean value
Time: Tue Oct 31 06:54:34 2023
Count: 1
Stack: Interface/AddOns/Details/core/parser.lua:2557: attempt to perform arithmetic on a boolean value
[string "=[C]"]: ?
[string ***@***.***/AddOns/Details/core/parser.lua"]:2557: in function <Interface/AddOns/Details/core/parser.lua:2378>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?

Locals: (*temporary) = defined =[C]:-1
