### ISSUE TITLE
[DF] Constant errors in blitz battleground (attempt to concatenate upvalue 'realmName')

### ISSUE THREAD

**Issue by Railander** [Tercioo/Details-Damage-Meter#626]
VWD 12028 RELEASE 10.2.0

Constant errors inside Battleground Blitz since last update, starts as soon as entering it and repeats every few seconds.

Message: Interface/AddOns/Details/core/parser.lua:7143: attempt to concatenate upvalue 'realmName' (a nil value)
Time: Fri Nov 10 14:41:17 2023
Count: 1
Stack: Interface/AddOns/Details/core/parser.lua:7143: attempt to concatenate upvalue 'realmName' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/Details/core/parser.lua"]:7143: in function `ReadPvPData'
[string "@Interface/AddOns/Details/core/parser.lua"]:7102: in function <Interface/AddOns/Details/core/parser.lua:7101>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by Flamanis** [comment]
Test on most recent version, 12032

**Comment by Railander** [comment]
Fixed at least as of 12033.
