### ISSUE TITLE
Details keeps switching to Classic Version

### ISSUE THREAD

**Issue by Laxxboy** [Tercioo/Details-Damage-Meter#64]
As the title states, whenever I update my Details! it will install the Classic version by default. In the Twitch list of my addons it is listed as DetailsClassic.1.1.3.4.199.142.zip
but when I click on it, it lists it as Details-DetailsRetail.8.3.0.7282.140.zip In game, I get the alert that I am using the Classic version. I have uninstalled an reinstalled several times now but it always default updates to Classic version. I don't even have Classic installed on my PC

**Comment by Tercioo** [comment]
It's an issue with the Twitch app.
