### ISSUE TITLE
[Request] Roboto Bold Condensed Font

### ISSUE THREAD

**Issue by zeenk** [Tercioo/Details-Damage-Meter#640]
## Edited this post as I noticed later that this font was actually not part of default Details, came from some other addon.

Hi, I was looking around trying to find a nice looking font that supports cyrillic letters so I don't have those squares in my details window when playing with russians, I know there's also the transit option I could use to avoid that but found a pretty nice font that looks pretty similar to the default font + support russian names so thought it could be nice to have it as an option in Details :)

_This is the default font "Accidental Presidency"_
![2023-12-07_07-00-02](https://github.com/Tercioo/Details-Damage-Meter/assets/68170439/ae3fb38a-ca59-4ecf-bc24-78e179d2ae2f)

_This is Roboto Bold Condensed._
![2023-12-07_07-00-50](https://github.com/Tercioo/Details-Damage-Meter/assets/68170439/df174b6d-99c5-4e32-9a9b-33cfd12f6308)

I found it from https://www.curseforge.com/wow/addons/elvui-additional-fonts and added it to sharedmedia addon so I could use it in Details (This is just a request so I don't need to have an extra addon installed just to be able to use this font in Details.)

Here is the font file:
[Roboto-BoldCondensed.zip](https://github.com/Tercioo/Details-Damage-Meter/files/13596307/Roboto-BoldCondensed.zip)

**Comment by Flamanis** [comment]
LibSharedMedia is used to allow you to use other addons to accentuate Details. Installing another addon that puts these items into LSM is the preferred method of adding custom fonts. There are quite a few font options that support cyrillic that are shipped with Details by default iirc.

**Comment by zeenk** [comment]
Yeah I tried all the default fonts that come with Details that also supports Cyrillic but didn't like any of them, sucks that that the default Accidental Presidency font doesn't support it cause I like that one, but yeah guess I'll just keep this other addon then to be able to use this new font.
