### ISSUE TITLE
Can't clear report results and randomly whispering people on my Bnet

### ISSUE THREAD

**Issue by sarahlogic** [Tercioo/Details-Damage-Meter#648]
I am having an issue with the report feature and would love to know if there is a way to address this.

Once a long time ago, I whispered a friend the interrupts for a dungeon and shared overall damage with the party. I did the party announce accidentally because the options were a bit confusing. Now under the report results tab, I have a permanent "overall damage to party" and "interrupts whisper" as dropdowns when hovering over the report button when on every character, regardless of profile selected.

The buttons are so tiny I sometimes accidentally click on the overall report results button in the main bar at the top of the details window without even entering the dropdown. This automatically chooses a random person on my Bnet list and whispers them the interrupts recently tracked, including people I haven't talked to in ages. 

Is there a way to remove this feature or at least clear the automated announcements tracked without reinstalling? I am scouring the settings but am really tired of sending these random whispers when I misclick. I tried clearing all data and looking at the options and creating new profiles, but it seems linked to the overall game as opposed to per character. I would love to remove this setting, or the data stored within it, without having to uninstall and reinstall to recreate all my profiles (I have a lot of characters). 

If I have to uninstall I will, but appreciate any suggestions if there is a way to fix it otherwise. Thank you!

**Comment by Tercioo** [comment]
Could you use this macro and check if the issue is gone?
**/run wipe(Details.latest_report_table)**

**Comment by sarahlogic** [comment]
Thank you! That appears to have wiped the saved information from the
dropdown, so hopefully all is well. I really appreciate your response.
