### ISSUE TITLE
Old conflicting libraries

### ISSUE THREAD

**Issue by thewopr** [Tercioo/Details-Damage-Meter#67]
**Game and Details! version**
C201
v1.13.3

In the most recently version of Details for classic. (https://www.curseforge.com/wow/addons/details/files/2945466)

There is both LibThreatClassic2 AND ThreatClassic-1.0 in the Libs folder.

Is this intentional? Could this be causing conflicts?

**Comment by Malevola** [comment]
Threat has seemed to be inaccurate for weeks now. I'm also curious is this is the issue.

**Comment by Tercioo** [comment]
Those libs has been removed.
