### ISSUE TITLE
Lua Error after finishing M+ key

### ISSUE THREAD

**Issue by tomrus88** [Tercioo/Details-Damage-Meter#678]
**Game and Details! version**
Use /details to grab these two.
DETAILS! VERSION: VWD 12256 RELEASE 10.2.5 

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
Do a M+ key, after finishing it lua error appears

- Result (what happens when you follow the steps above):
```
Message: ...tails/frames/window_mythicplus/window_end_of_run.lua:417: attempt to index field 'ReadyFrame' (a nil value)
Time: Wed Feb  7 17:23:35 2024
Count: 1
Stack: ...tails/frames/window_mythicplus/window_end_of_run.lua:417: attempt to index field 'ReadyFrame' (a nil value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/Details/frames/window_mythicplus/window_end_of_run.lua"]:417: in function <...tails/frames/window_mythicplus/window_end_of_run.lua:329>
```
- Expected (what you think the expected behavior would be when following the steps):
No lua error

- When the bug started (a date, wow path release, details update, etc)?
With recent addon update

**Comment by Tercioo** [comment]
Do you remember if the error occurred on the second finished run? (no error on first completed m+, and the error on the second finished run).

**Comment by Tercioo** [comment]
nevermind, fixed.

**Comment by tomrus88** [comment]
Error is appearing on every M+ completion for me, be it first, second, etc...
