### ISSUE TITLE
Mythic Skitra dps discrepancies - may be the game itself, though

### ISSUE THREAD

**Issue by raysmith59** [Tercioo/Details-Damage-Meter#69]
Our raid did mythic Skitra for the first time tonight and we had some significant log discrepancies between players.  I had a buddy at 7th place in overall damage on my meter while he had himself at the top.  I had myself doing 14M damage vs him having me at 10M.  I'm not seeing any discussion of dps discrepancies anywhere and I thought Blizz fixed the logging for phased fights years ago.  I also did the log upload to WL and those numbers match my Details numbers so I'm not sure if it's an issue with Details or with the fight logging itself but I figured I'd get a better answer here than from Blizzard.

For what it's worth, when we compared my spell damage done to dig into the numbers behind the damage done, the only numbers that matched were the melee damage done by my two hunter pets, after that (including the Kill Commands associated with my two pets) all of the spells were under-reported in his Details compared to mine.

Is this something wrong with Details or is it an issue with the base game?

**Comment by Tercioo** [comment]
Because of the encounter split players into different phases and they cannot see the combatlog.
