### ISSUE TITLE
Sporadic LUA error during classic stress test 

### ISSUE THREAD

**Issue by vazheel** [Tercioo/Details-Damage-Meter#7]
Hey Tercioo!

I ran into this glitch fairly often running Details Damage Meter in Durotar during the classic stress test. I've attached the full LUA dump in a gist for you. I can take a look at it as well, although I have to admit the Portuguese variable names are throwing me for a loop :)

Calthaza is right, it happens on normal mobs too ~It appears to happen whenever I get a debuff that's a dot on me, so the scorpid poison will fairly reliably set it off~

https://gist.github.com/vazheel/25a8843b02f797b98aa2815e6175de91

**Comment by vazheel** [comment]
Update: I added a simple nil check around this line https://github.com/Tercioo/Details-Damage-Meter/blob/master/functions/spellcache.lua#L237

And it went away -- I don't really understand what this code is trying to accomplish, so I leave it up to you if this would be a reasonable solution

**Comment by Calthaza** [comment]
10x Details\functions\spellcache.lua:237: attempt to concatenate local 'nome' (a nil value)
Details\functions\spellcache.lua:237: in function `SpellIsDot'
Details\classes\classe_damage_habilidade.lua:75: in function `funcao_de_criacao'
...aceDetails\classes\container_habilidades.lua:71: in function `PegaHabilidade'
Details\core\parser.lua:950: in function <Details\core\parser.lua:419>
(tail call): ?

Locals:
InCombatSkipped


I am killing Mottled Boars in durotar, so it does not have anything with debuff as the other guy mentioned.

**Comment by vazheel** [comment]
Good point, I noticed that it happened reliably with mobs with dots, and sporadically with non-dot mobs. I updated my original message.

**Comment by Tercioo** [comment]
Got it! thanks.

**Comment by jsabin69** [comment]
Error continues with latest update:


Message: Interface\AddOns\Details\functions\spellcache.lua:237: attempt to concatenate local 'nome' (a nil value)
Time: Sat Aug 10 06:39:11 2019
Count: 8
Stack: Interface\AddOns\Details\functions\spellcache.lua:237: attempt to concatenate local 'nome' (a nil value)
Interface\AddOns\Details\functions\spellcache.lua:237: in function `SpellIsDot'
...\AddOns\Details\classes\classe_damage_habilidade.lua:75: in function `funcao_de_criacao'
...ace\AddOns\Details\classes\container_habilidades.lua:71: in function `PegaHabilidade'
Interface\AddOns\Details\core\parser.lua:948: in function <Interface\AddOns\Details\core\parser.lua:419>
(tail call): ?

Locals: self = <table> {
 SetBarSpecIconSettings = <function> defined @Interface\AddOns\Details\gumps\janela_principal.lua:4285
 APITopics = <table> {
 }
 InitializeRunCodeWindow = <function> defined @Interface\AddOns\Details\core\windows.lua:4496
 EncounterDetailsTempWindow = <function> defined @Interface\AddOns\Details_EncounterDetails\frames.lua:49
 EntrarEmCombate = <function> defined @Interface\AddOns\Details\core\control.lua:313
 hex = <function> defined @Interface\AddOns\Details\core\util.lua:687
 BuildSpellList = <function> defined @Interface\AddOns\Details\functions\spellcache.lua:308
 opened_windows = 2
 RefreshAttributeTextSize = <function> defined @Interface\AddOns\Details\gumps\janela_principal.lua:7546
 PotionList = <table> {
 }
 EndRefresh = <function> defined @Interface\AddOns\Details\core\control.lua:1691
 FechaJanelaInfo = <function> defined @Interface\AddOns\Details\gumps\janela_info.lua:380
 GetMode = <function> defined @Interface\AddOns\Details\classes\classe_instancia.lua:148
 SetMode = <function> defined @Interface\AddOns\Details\classes\classe_instancia.lua:2706
 RestoreState_CurrentMythicDungeonRun = <function> defined @Interface\AddOns\Details\functions\profiles.lua:1478
 APIVersion = 140
 IsPluginEnabled = <function> defined @Interface\AddOns\Details\core\plugins.lua:58
 ImportProfile = <function> defined @Interface\AddOns\Details\functions\profiles.lua:1629
 SetNickname = <function> defined @Interface\AddOns\Details\Libs\NickTag-1.0\NickTag-1.0.lua:495
 color_by_arena_team = true
 SortKeyGroupHeal = <function> defined @Interface\AddOns\Details\classes\classe_heal.lua:125
 SortKeyGroup = <function> defined @Interface\AddOns\Details\classes\classe_damage.lua:133
 IsInEncounter = <function> defined @Interface\AddOns\Details\core\parser.lua:5314
 Check_ZONE_CHANGED_NEW_AREA = <function> defined @Interface\AddOns\Details\core\parser.lua:4072
 plugin_window_pos = <table> {
 }
 gump = <table> {
 }
 CaptureRefresh = <function> defined @Interface\AddOns\Details\core\parser.lua:3726
 NewModule = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 InstancesToStoreData = <table> {
 }
 name_space_info = <function> defined @Interface\AddOns\Details\core\util.lua:1385
 ShowDelayMsg = <function> defined @Interface\AddOns\Details\boot.lua:658
 Resize = <function> defined @Interface\AddOns\Details\classes\classe_instancia.lua:1867
 GetEncounterActorsName = <function> defined @Interface\AddOns\Details\functions\boss.lua:306
 RequestCloudData = <function> defined @Interface\AddOns\Details\core\network.lua:721
 RestauraJanela = <function> defined @Interface\AddOns\Details\classes\classe_instancia.lua:1429
 default_skin_to_use = "Minimalistic"
 GetOpenedWindowsAmount = <function> defined @Interface\AddOns\Details\classes\classe_instancia.lua:256
 GetInstanceGroup = <function> defined @Interface\AddOns\Details\gumps\janela_principal.lua:8007
 deadlog_events = 32
 Dump = <function> defined @Interface\AddOns\Details\core\windows.lua:7132
 OpenNewsWindow = <function> defined @Interface\AddOns\Details\gumps\janela_news.lua:9
 last_instance_id = 0
 _detalhes_props = <table> {
 }
 atributo_energy = <table> {
 }
 UnitDamageOnUnit = <function> defined @Interface\AddOns\Details\functions\api2.lua:1123
 name_space_generic = <function> defined @Interface\AddOns\Det

**Comment by Tercioo** [comment]
this issue should be solved with latest version from curse

**Comment by Tercioo** [comment]
also, spellIds not working correctly on the client side

**Comment by Tercioo** [comment]
Made a new version for classic only, it's available at curse and wow interface.
