### ISSUE TITLE
Wrong dropdown popup in wotlk

### ISSUE THREAD

**Issue by Cabro** [Tercioo/Details-Damage-Meter#704]
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**

**Game and Details! version**
DETAILS! VERSION: VWD 12553 RELEASE 3.4.3

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
Mouseover the encounter list and the popup with the list is not appearing anymore.

- Result (what happens when you follow the steps above):
You get instead the settings popup dropdown. (Probably some bad copy+paste for wotlk)

- Expected (what you think the expected behavior would be when following the steps):
Should show the encounter list.

- When the bug started (a date, wow path release, details update, etc)?
A couple of versions ago, was hoping for a fix to be incoming earlier.

- Additional information:
When you reset all info, the encounter list shows, well, sort of. See snips below.
It just stops showing the encounter list dropdown at some point and shows the settings dropdown instead. I don't know what the trigger for this is. Could be when you reach too many encounters in the list? Seems to happen right after entering world if you already had some encounters from last time you played. Your guess is as good as mine.
Wotlk

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*
No lua errors.

**Screenshots**
Post images of the bug if necessary.
Wrong dropdown.
![image](https://github.com/Tercioo/Details-Damage-Meter/assets/1155017/8f24c551-88a5-4b0a-89b7-07b23dcc6f55)

After reset it shows the encounter list:
![image](https://github.com/Tercioo/Details-Damage-Meter/assets/1155017/2687bf23-af35-4cfa-bde7-6da15b5ff582)

How it should look like:
![image](https://github.com/Tercioo/Details-Damage-Meter/assets/1155017/dac53b21-d2e9-4ab1-8eb5-3538ca41cc35)

**Combat Log**
Include a link to a combatlog file if the error is about not detecting a skill, usable item or item proc.
The log can be as simple as hitting a mob with white damage and using the item/skill.

**Other Information**
If necessary, add more info here.

**Comment by Cabro** [comment]
After some more investigating, seems the bug is that it is just not showing the dropdown at all when you mouseover the encounters icon, and it just copies the last dropdown active (if there is any).

**Comment by Cabro** [comment]
Could it be this weird `-nan(ind)%`?
![image](https://github.com/Tercioo/Details-Damage-Meter/assets/1155017/ec4cc0b2-72d6-4117-806a-7ec0846e66d2)

**Comment by Flamanis** [comment]
Try updating to the most recent alpha.

**Comment by Cabro** [comment]
bug seems to be solved in alpha
