### ISSUE TITLE
In Cataclysm Classic Dungeon Finder instances and only inside them, the player's hunter pet's damage is not attributed to the player's damage, but other hunters' pets' damage are attributed to their owners' damage

### ISSUE THREAD

**Issue by AlexFolland** [Tercioo/Details-Damage-Meter#759]
## Game and Details! version

Cataclysm Classic

VWD 12801 ALPHA 58 4.4.0

## Steps to reproduce

1. Play as a hunter in Cataclysm Classic.
2. Attack enemies as usual outside a dungeon and observe combined pet damage in the Details damage window.
3. Use the dungeon finder menu to queue for a random dungeon.
4. Await and then join the dungeon.  If there is no other hunter, finish the dungeon and go to step 3.
5. Attack enemies as usual inside the dungeon finder instance and observe that the player's hunter pet's damage is not attributed to the player's damage, but other hunters' pets' damage are attributed to their owners' damage.

## Observed behavior

In Cataclysm Classic Dungeon Finder instances and only inside them, the player's hunter pet's damage is not attributed to the player's damage, but other hunters' pets' damage are attributed to their owners' damage.

## Expected behavior

All hunters' pets' damage, healing, and other logged effects are expected to always be attributed to their owners.

## When did the bug first manifest (a date, wow path release, details update, etc.)?

I don't know since I just came back to playing 2 days ago.  I first observed it the day after I started playing Cataclysm Classic on my hunter, when I ran my first dungeon finder instance.  That was 2 days ago; 2024-06-18.  The issue may have been reproducible longer than that.

## Lua Errors

I see no Lua errors from Details with or without other addons enabled.

## Screenshots

![image](https://github.com/Tercioo/Details-Damage-Meter/assets/601517/dfc495c6-6bb9-4a5c-a0de-79d323779b3f)

## Other Information

I can manually calculate my total damage by switching from "Standard" to "Everything" view and adding my pet's damage to mine.  This is a major inconvenience though.

**Comment by Flamanis** [comment]
Can you screenshot the window showing your pet?

**Comment by AlexFolland** [comment]
Here.  I think this captures the requested information.

![image](https://github.com/Tercioo/Details-Damage-Meter/assets/601517/931d9cf9-71f4-405b-b1ac-18b78261407e)

**Comment by Flamanis** [comment]
Could you get a combatlog file of this occuring?

**Comment by AlexFolland** [comment]
OK, I did.  Here it is.

[WoWCombatLog-062324_213933.txt](https://github.com/user-attachments/files/15949915/WoWCombatLog-062324_213933.txt)

**Comment by Flamanis** [comment]
Did this log come from you personally? Or another player?

**Comment by AlexFolland** [comment]
Me personally.

**Comment by Flamanis** [comment]
I was hoping you weren't going to say that. Log shows your events are
occurring with your name containing your realm name, with your pet not
having your realm name. I'll check in the morning personally if that is the
case for the issue

**Comment by AlexFolland** [comment]
I didn't manually edit the combat log, so I don't think you'd need to check personally if that's the case.  You can see it in my combat log.

**Comment by Flamanis** [comment]
In game events dont always line up with out of game, so i need to check
that against hunter pets and see what we might be doing wrong when trying
to detect

**Comment by AlexFolland** [comment]
I've tested this again after today's update which mentioned a fix for this.  I'm happy to report that this is fixed with today's update!  Thank you very much for the fix.
