### ISSUE TITLE
Deaths not showing cooldowns on right

### ISSUE THREAD

**Issue by JoeTruelove** [Tercioo/Details-Damage-Meter#763]
I used to be able to see the defensive cooldowns either available or timers for those not on the deaths of each person per current segment to the right of the deaths when hovering over one. It no longer shows for some reason and cannot find any settings to show them again. Will provide a screen shot of what it is supposed to look like and what it looks like now.

what it currently looks like
![Screenshot 2024-07-02 233336](https://github.com/Tercioo/Details-Damage-Meter/assets/43154676/b52989ad-51cc-46f7-970f-cd332370a250)

what it is supposed to look like, which you can see the cooldowns on the bottom right
![whatissupposedtolooklike](https://github.com/Tercioo/Details-Damage-Meter/assets/43154676/8a5b9882-d439-48f8-8cbb-55a8a00d2824)

**Comment by Tercioo** [comment]
Advanced Death Logs plugin.

**Comment by JoeTruelove** [comment]
sorry to be a pain but I have advanced death logs plugin updated and enabled in the settings. I hadn't changed anything when it stopped working so I'm unsure if there's a hidden way to enable or disable it or something. I've uninstalled the addon and reinstalled and still nothing (to clarify I did do a dungeon after the reinstall to make sure it got a fresh log).

**Comment by JoeTruelove** [comment]
I have figured out that there is some sort of conflict with plater for some reason, I disabled plater and the plugin death thing started working and re-enabled plater and it stopped working again. I installed buggrabber to find the conflict directly and will post it bellow. Not sure what caused this to start happening cause I've had plater for a long time and my friend has plater and advanced death log and theirs works but for some reason mine isn't. If you need any more information I have the tab on the side and will reply as soon as I see it. Thank you.

36x Details/Libs/DF/cooltip.lua:3422: attempt to perform arithmetic on field '?' (a nil value)
[string "@Details/Libs/DF/cooltip.lua"]:3422: in function `AddLine'
[string "@Details_DeathGraphs/details_hook.lua"]:63: in function <Details_DeathGraphs/details_hook.lua:10>
[string "=[C]"]: in function `ShowDeathTooltipFunction'
[string "@Details/classes/class_utility.lua"]:369: in function <Details/classes/class_utility.lua:366>
[string "=(tail call)"]: ?
[string "@Details/frames/window_main.lua"]:1845: in function <Details/frames/window_main.lua:1841>

Locals:
self = <table> {
 ShowSelectedTexture = <function> defined @Details/Libs/DF/cooltip.lua:919
 mouseOver = false
 internalYMod = 0
 SetWallpaper = <function> defined @Details/Libs/DF/cooltip.lua:3055
 ShowCooltip = <function> defined @Details/Libs/DF/cooltip.lua:3583
 RightIconTable = <table> {
 }
 SetTitleAnchor = <function> defined @Details/Libs/DF/cooltip.lua:423
 LastSize = 0
 PrintDebug = <function> defined @Details/Libs/DF/cooltip.lua:53
 Type = 1
 OptionsTable = <table> {
 }
 default_text_size = 10.500000
 PopupFrameTable = <table> {
 }
 WallpaperTable = <table> {
 }
 IsShown = <function> defined @Details/Libs/DF/cooltip.lua:3579
 Show = <function> defined @Details/Libs/DF/cooltip.lua:3574
 SelectedIndexSec = <table> {
 }
 Hide = <function> defined @Details/Libs/DF/cooltip.lua:3616
 GetType = <function> defined @Details/Libs/DF/cooltip.lua:2581
 active = false
 InjectQuickTooltip = <function> defined @Details/Libs/DF/cooltip.lua:3862
 ShowRoundedCorner = <function> defined @Details/Libs/DF/cooltip.lua:372
 LanguageEditBox = EditBox {
 }
 QuickTooltip = <function> defined @Details/Libs/DF/cooltip.lua:3850
 SetBannerImage = <function> defined @Details/Libs/DF/cooltip.lua:3159
 TopIconTableSub = <table> {
 }
 ExecFunc = <function> defined @Details/Libs/DF/cooltip.lua:3670
 WallpaperTableSub = <table> {
 }
 Msg = <function> defined @Details/Libs/DF/cooltip.lua:60
 default_height = 20
 Close = <function> defined @Details/Libs/DF/cooltip.lua:3620
 HideRoundedCorner = <function> defined @Details/Libs/DF/cooltip.lua:390
 selectedAnchor = <table> {
 }
 AddFromTable = <function> defined @Details/Libs/DF/cooltip.lua:3555
 AddSpecial = <function> defined @Details/Libs/DF/cooltip.lua:3488
 SetSpellByID = <function> defined @Details/Libs/DF/cooltip.lua:1943
 ShowSub = <function> defined @Details/Libs/DF/cooltip.lua:1549
 CreateButtonOnSecondFrame = <function> defined @Details/Libs/DF/cooltip.lua:897
 AddPopUpFrame = <function> defined @Details/Libs/DF/cooltip.lua:3327
 AddIcon = <function> defined @Details/Libs/DF/cooltip.lua:3225
 SetupWallpaper = <function> defined @Details/Libs/DF/cooltip.lua:1514
 SetDebug = <function> defined @Details/Libs/DF/cooltip.lua:64
 FunctionsTableSub = <table> {
 }
 Preset = <function> defined @Details/Libs/DF/cooltip.lua:3819
 TextAndIcon = <function> defined @Details/Libs/DF/cooltip.lua:990
 SetOption = <function> defined @Details/Libs/DF/cooltip.lua:2509
 LastIndex = 0
 HideSelectedTexture = <function> defined @Details/Libs/DF/cooltip.lua:913
 AddMenu = <function> defined @Details/Libs/DF/cooltip.lua:2803
 HideSub = <function> defined @Details/Libs/DF/cooltip.lua:1722
 SetBannerText = <function> defined @Details/Libs/DF/cooltip.lua:3092
 SetLastSelected = <function> defined @Details/Libs/DF/cooltip.lua:2667
 frame2 = GameCooltipFrame2 {
 }
 SetColor = <function> defined @Details/Libs/DF/cooltip.lua:2638
 Indexes = 0
 defaultFont = "Friz Quadrata TT"
 ParametersTableMain = <table> {
 }
 GetOwner = <function> defined @Details/Libs/DF/cooltip.lua:2521
 AddStatusBar = <function> defined @Details/Libs/DF/cooltip.lua:2974
 BuildCooltip = <function> defined @Details/Libs/DF/cooltip.lua:2186
 FunctionsTableMain = <table> {
 }
 LeftTextTableSub = <table> {
 }
 Select = <function> defined @Details/Libs/DF/cooltip.lua:2686
 SetFixedParameter = <function> defined @Details/Libs/DF/cooltip.lua:2624
 GetFixedParameter = <function> defined @Int
