### ISSUE TITLE
Plugins need TOC update for Cata

### ISSUE THREAD

**Issue by OrceMaceski** [Tercioo/Details-Damage-Meter#768]
Plugins are missing .toc for cataclysm client

**Comment by Tercioo** [comment]
done, sent another release


------ Original Message ------
From "Orce Maceski" ***@***.******@***.***>>
To "Tercioo/Details-Damage-Meter" ***@***.******@***.***>>
Cc "Subscribed" ***@***.******@***.***>>
Date 11-Jul-24 6:20:55 PM
Subject [Tercioo/Details-Damage-Meter] Plugins need TOC update for Cata (Issue #768)


Plugins are missing .toc for cataclysm client
