### ISSUE TITLE
Lines 68-70 of startup.lua are setting camera distance to max on every game launch - intentional?

### ISSUE THREAD

**Issue by Tograblah** [Tercioo/Details-Damage-Meter#770]
I've confirmed, by means of editing my own startup.lua file and changing the numeric value that line 70 is setting the CVar to, that Details is currently setting the camera distance to max on every launch of WoW.

I personally prefer a camera distance of 1.5 and am wondering if the aforementioned lines in startup.lua may be unintentionally enabled as there is some text in there stating `--disable for releases`.

Not a big deal by any means - I can just change the 2.6 to 1.5 on my end each update, but I wanted to check in as to whether what I've described is working as intended.

**Comment by Tercioo** [comment]
Thanks for reporting and providing the line where the issue is.
That's a line that should not be there for releases.
I'm surprise that after 3 days you're the only one complaining, I think I'll set the camera to 2.6 on details! install, it might be helping a lot of people.
