### ISSUE TITLE
Totally down after creating custom statistic code

### ISSUE THREAD

**Issue by gfhfhoo** [Tercioo/Details-Damage-Meter#782]
**Game and Details! version**
VCT 12816 RELEASE 3.4.3

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):

All statistic functions except `tiny threat addon` were down after that I created my own statistic code. Following tips(reinstall and reload) is failed to make it normal. Even nothing happened when reinstalled this addon.

- Result (what happens when you follow the steps above):

All statistic functions failed.

- Expected (what you think the expected behavior would be when following the steps):

at least functions are enable to use normally after being reinstalled.

- When the bug started (a date, wow path release, details update, etc)?

Today.

- Additional information:

I don't know if the occurrence is caused by my code, so I pasted my code here.(I am new here!)
```lua
local Combat, Container, Instance = ...
local total, top, amount = 0, 0, 0

local cur = Details:GetCurrentCombat()

local player = Details:GetActor()

if player and cur then
    for name, _ in pairs(player.damage_from) do
        local enemy = Details:GetActor(name)
        local spells = enemy:GetSpellList()
        for spellid, spell in pairs(spells) do
            if spell.targets[player.name] ~= nil then
                Container:AddValue(spell,spell.total)
                total = total+ spell.total
                if top < spell.total then
                    top = spell.total
                end
                amount = amount + 1
            end
            
        end
    end
end

return total, top, amount
```

**Lua Error**

---
Message: Interface/AddOns/Details/functions/spec_augmentation.lua:1 (null)

---
Message: Interface_Wrath\FrameXML\Bindings.xml:1 Interface/AddOns/Details/functions/spec_augmentation.lua:1 (null)

---

**Screenshots**
Post images of the bug if necessary.

**Combat Log**
Include a link to a combatlog file if the error is about not detecting a skill, usable item or item proc.
The log can be as simple as hitting a mob with white damage and using the item/skill.

**Other Information**
If necessary, add more info here.

**Comment by Flamanis** [comment]
Addon isn't made to run on wrath anymore. The last probably stable release for wrath was https://www.curseforge.com/wow/addons/details/files/5318009

**Comment by gfhfhoo** [comment]
> Addon isn't made to run on wrath anymore. The last probably stable release for wrath was https://www.curseforge.com/wow/addons/details/files/5318009

Thank you, I will try it. And is there any examples about custom statistics? The doc is so tedious that I don't know where should I start.
