### ISSUE TITLE
Feature request: allow details screen to appear in front of wow UI

### ISSUE THREAD

**Issue by LanaYoobee** [Tercioo/Details-Damage-Meter#791]
**Game and Details! version**
VCT 12819 Release 11.0.0

**Describe the bug**
I used to have my quest log on the right and the details below it , near my chat windows. With 11.0, the quest log got moved by the game (even though I had it set to where i wanted it via Edit, it got moved to top left). When I repositioned the quest log back to the right side of the screen, I noticed it covers the Details screen. I am pretty sure it used fall behind it. I noticed also the Details Options screen also gets covered by all other UI elements (eg, my raid frames), while, for example, DBM options window goes above. The options one is not a biggie of course as it's not often looked and can be moved, but it would be nice for the Details itself to appear above any other UI elements.

**Screenshots**

![image](https://github.com/user-attachments/assets/958a8f6a-8820-4fce-a573-92da26ef6962)

![image](https://github.com/user-attachments/assets/5c2597f4-2b85-4329-8700-205bf0c5a23a)

**Comment by Tercioo** [comment]
Layer Strata > Dialog


------ Original Message ------
From "LanaYoobee" ***@***.******@***.***>>
To "Tercioo/Details-Damage-Meter" ***@***.******@***.***>>
Cc "Subscribed" ***@***.******@***.***>>
Date 26-Jul-24 6:53:32 PM
Subject [Tercioo/Details-Damage-Meter] Feature request: allow details screen to appear in front of wow UI (Issue #791)


Before Start!

Make sure the bug also happen when Details! is the only addon enabled.

Game and Details! version
VCT 12819 Release 11.0.0

Describe the bug
I used to have my quest log on the right and the details below it , near my chat windows. With 11.0, the quest log got moved by the game (even though I had it set to where i wanted it via Edit, it got moved to top left). When I repositioned the quest log back to the right side of the screen, I noticed it covers the Details screen. I am pretty sure it used fall behind it. I noticed also the Details Options screen also gets covered by all other UI elements (eg, my raid frames), while, for example, DBM options window goes above. The options is not a biggie of course as it's not often looked and can be moved.

Screenshots
Post images of the bug if necessary.
image.png (view on web)<https://github.com/user-attachments/assets/958a8f6a-8820-4fce-a573-92da26ef6962>

image.png (view on web)<https://github.com/user-attachments/assets/5c2597f4-2b85-4329-8700-205bf0c5a23a>

**Comment by Flamanis** [comment]
Yep. This feature already exists and it's by using the Strata system provided by Blizzard to decide which elements are drawn over others. It sounds like you changed the strata for your other frames to be over the details windows.

**Comment by LanaYoobee** [comment]
thanks for that @Tercioo . @Flamanis no i didn't change anything. Maybe the game changed its own values. Fixed now, cheers.
