### ISSUE TITLE
Details!: Streamer addon is missing

### ISSUE THREAD

**Issue by davidmann4** [Tercioo/Details-Damage-Meter#797]
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**

**Game and Details! version**
VCT 12822 RELEASE 11.0.0

**Describe the bug**

After installing the lastest update the streamer action tracker is missing 

![image](https://github.com/user-attachments/assets/c8ff73be-590c-4af0-87a1-e70fc578018a)

The "Broadcaster Tools" still refers to the Action Tracker and even shows a screenshot of it, but I cannot activate it there either.
![image](https://github.com/user-attachments/assets/ead045b2-8c42-4a19-a2d5-7e4c5e617c24)

**Comment by Tercioo** [comment]
Check addons folder for a folder named "Details_Streamer" and also check for "Details!: Streamer (plugin)" ingame on the addon list panel.

**Comment by davidmann4** [comment]
installed th elast update and its back again!
