### ISSUE TITLE
Classic LUA errors, Hunter

### ISSUE THREAD

**Issue by ajungg** [Tercioo/Details-Damage-Meter#8]
When playing a Hunter with Pet i get the following lua error as soon as i hover over my name: 

`Message: Interface\AddOns\Details\classes\classe_damage.lua:2975: attempt to concatenate local 'nome_magia' (a nil value)
Time: Sat Aug 10 19:10:41 2019
Count: 4
Stack: Interface\AddOns\Details\classes\classe_damage.lua:2975: attempt to concatenate local 'nome_magia' (a nil value)
Interface\AddOns\Details\classes\classe_damage.lua:2975: in function <Interface\AddOns\Details\classes\classe_damage.lua:2873>
(tail call): ?
Interface\AddOns\Details\core\control.lua:1654: in function `MontaTooltip'
Interface\AddOns\Details\gumps\janela_principal.lua:1911: in function <Interface\AddOns\Details\gumps\janela_principal.lua:1907>

Locals: self = <table> {
 flag_original = 1297
 totalabsorbed = 0.007065
 damage_from = <table> {
 }
 targets = <table> {
 }
 colocacao = 1
 pets = <table> {
 }
 minha_barra = DetailsBarra_1_1 {
 }
 friendlyfire_total = 0
 raid_targets = <table> {
 }
 total_without_pet = 127.007065
 friendlyfire = <table> {
 }
 on_hold = false
 dps_started = false
 total = 168.007065
 classe = "HUNTER"
 serial = "Player-4442-0002238D"
 nome = "Impi"
 spells = <table> {
 }
 grupo = true
 displayName = "Impi"
 end_time = 1565456781
 last_dps = 30.900653
 custom = 0
 tipo = 1
 damage_taken = 0.007065
 start_time = 1565456772
 delay = 0
 last_event = 1565456780
}
instancia = <table> {
 h_baixo = DetailsBottomSideBarHighlight1 {
 }
 menu_icons_size = 0.850000
 h_esquerda = DetailsLeftSideBarHighlight1 {
 }
 bg_r = 0.094118
 color_buttons = <table> {
 }
 toolbar_icon_file = "Interface\AddOns\Details\images\toolbar_icons"
 modo = 2
 tooltip = <table> {
 }
 icons = <table> {
 }
 ponto3 = <table> {
 }
 ponto1 = <table> {
 }
 rolagem = false
 rows_max = 50
 windowBackgroundDisplay = Details_GumpFrame1 {
 }
 lastIcon = <table> {
 }
 menu_icons = <table> {
 }
 isMoving = false
 show_sidebars = false
 hide_icon = true
 consolidate = false
 toolbar_side = 1
 sub_atributo = 1
 atributo = 1
 bg_b = 0.094118
 need_rolagem = false
 backdrop_texture = "Details Ground"
 color = <table> {
 }
 sub_atributo_last = <table> {
 }
 barraS = <table> {
 }
 bgdisplay = Details_GumpFrame1 {
 }
 switch_healer = false
 ponto2 = <table> {
 }
 ponto4 = <table> {
 }
 __locked = true
 menu_alpha = <table> {
 }
 snap = <table> {
 }
 clickthrough_incombatonly = true
 hide_in_combat_alpha = 0
 firstIcon = DetailsClearSegmentsButton1 {
 }
 row_show_animation = <table> {
 }
 grab_on_top = false
 baseframe = DetailsBaseFrame1 {
 }
 hide_in_combat = false
 posicao = <table> {
 }
 row_height = 15
 __pos = <table> {
 }
 show_statusbar = false
 clickthrough_window = false
 menu_anchor = <table> {
 }
 total_buttons_shown = 5
 hide_out_of_combat = false
 rows_created = 10
 skin_custom = ""
 __was_opened = true
 switch_all_roles_in_combat = false
 clickthrough_toolbaricons = false
 clickthrough_rows = false
 barras = <table> {
 }
 switch_tank = false
 windowSwitchButton = Details_SwitchButtonFrame1 {
 }
 switch_all_roles_after_wipe = false
 rowframe = DetailsRowFrame1 {
 }
 switch_damager = false
 auto_hide_menu = <table> {
 }
 window_scale = 1
 h_direita = DetailsRightSideBarHighlight1 {
 }
 meu_id = 1
 bg_g = 0.094118
 top = 74.007065
 freeze_texto = <unnamed> {
 }
 do_not_snap = false
 mostrando = "normal"
 ativa = true
 break_snap_button = DetailsBreakSnapButton1 {
 }
 alturaAntiga = 158.000015
 hide_in_combat_type = 1
 last_modo = 2
 last_interaction = 1565457040
 skin = "Minimalistic"
 segmento = 0
 following = <table> {
 }
 is_interacting = true
 oldwith = 269.111053
 cached_bar_width = 269.111053
 rows_showing = 1
 bars_sort_direction = 1
 libwindow = <table> {
 }
 iniciada = true
 micro_displays_locked = true
 StatusBarSaved = <table> {
 }
 LastModo = 2
 v_barras = false
 switch_tank_in_combat = false
 version = 3
 attribute_text = <table> {
 }
 row_info = <table> {
 }
 ignore_mass_showhide = false
 _version = <unnamed> {
 }
 plugins_grow_direction = 1
 desaturated_menu = false
 strata = "LOW"
 micro_displays_side = 2
 __snap = <table> {
 }
 rows_fit_in_window = 10
 `

**Comment by ajungg** [comment]
Should also mention that im on the latest version you uploaded 5 minutes ago on curse

**Comment by lucas-nelson** [comment]
I don't know this code, so apologies if this is not the right thing to do, but if you change `classes/classe_damage.lua` line 2974 from

```lua
if (petName) then
```

to 

```lua
if (petName and nome_magia) then
```

seems to avoid the error and not break anything obvious.

**Comment by ajungg** [comment]
The SpellId's for all my actions seems to be 0. 

If i nil check like you said, details is not putting out errors anymore, but my damage is not attributed anymore.  

For example i did 291 Damage in one fight, but only the spells of my pet are listed (71 damage). 

So the only thing working for me is the overall list, spell info is currently completly broken for me. Its not even showing Auto-Shot

**Comment by Tercioo** [comment]
Yeah, looks like is an issue in the client it self, I'm monitoring.

**Comment by Tercioo** [comment]
This issue has come problems with the combat log not showing the spellID anymore, also Details! now has a new version only for Classic WoW.
