### ISSUE TITLE
Oddly, halts the tutorial buttons for the Garrison Mission table

### ISSUE THREAD

**Issue by RobA2** [Tercioo/Details-Damage-Meter#802]
https://www.wowhead.com/quest=34692/delegating-on-draenor#comments:id=5915482

Narrowed issue down to "Details! Damage Meter" addon. At least in my case. I'm not sure what internal flag is being halted, but it appears to keep the tutorial buttons from showing when you first start your garrison missions. Disabled all other addons. Could consistently disable/reenable the addon & could see the the tutorial button just needing to be clicked, but with the addon running, no button. Thus the gray mission. Addon is up-to-date, but sent over a copy of this note for a possible fix. (should not even be a thing since the addon has nothing to do with garrison missions lol)

VCT 12829 RELEASE 11.0.0

Steps:
With only "Details!" running, have a character with a new Garrison, attempt to start running garrison missions with quest "Delegating on Draenor"

- Result (what happens when you follow the steps above):
Garrison Missions are not clickable

- Expected (what you think the expected behavior would be when following the steps):
Game should pop up tutorial buttons that illustrate how the missions work, then all missions become clickable

- When the bug started (a date, wow path release, details update, etc)?
Personally noticed as of Aug 9, 2024, but wowhead shows that it may have started around patch 10.2.0 (jan 7, 2024)
(horde version of quest: https://www.wowhead.com/quest=34775/mission-probable )

- Additional information:
I completely understand that it is likely a related lua library or some other software hiccup that I'm simply not well verse in. Just so happens that your addon appears to be involved, even though this issue has nothing to do with damage/combat tracking! (one silly flag that blizz changed?)

**Lua Error**
No errors pop up

**Screenshots**
Post images of the bug if necessary.

**Combat Log**
Ironically, not a combat related issue... which is so random, since the issue shouldn't even be related to your addon

**Other Information**
If necessary, add more info here.
![WoWScrnShot_080924_172716](https://github.com/user-attachments/assets/9be97a9a-4643-4541-b43d-0a72ddd0a796)
![WoWScrnShot_080924_172741](https://github.com/user-attachments/assets/d17e9cdc-b83a-4f13-a9a2-2134991500e6)

**Comment by Malivil** [comment]
It's not limited to just this window either, it happens for Void Storage as well. If you purchase Void Storage you'll see the exact same overlay with no tutorial messages until you disable Details.

**Comment by nashutal** [comment]
Came here to report this same bug. Because the tutorial popups are suppressed the mission table and void storage are unusable until you disable Details and click through all the tutorial popups.

**Comment by Malivil** [comment]
Looks like the garrison mission table issue was fixed here: https://github.com/Tercioo/Details-Damage-Meter/commit/6efca5bc826b08021d4033649dce84514f8b8319#diff-2e2042ca80614c656922a1f5f2c16ec997706012c4e3f846b6aa488fec0a146dR429

And that the same logic could probably be applied to the void storage tutorial problem

**Comment by RobA2** [comment]
Appears to work fine regarding the mission table. And though the Void storage is having the same tutorial problem, I think filing that as a separate issue would help with record keeping. Marking this one as closed
