### ISSUE TITLE
bug with 11.0.2

### ISSUE THREAD

**Issue by Addonman** [Tercioo/Details-Damage-Meter#815]
I was in a raid yesterday and details was showing odd behaviour. Didn't get any bug reports but i have window for like 8 names but mostly i got to see only 4 names on list. Also  person topping dmg was always called  unknown even do if he was like 2nd or 3rd i would see his name. Not sure but it was also strange that person that was topping list had like 2-3 mil dps.

**Comment by tomasmanhal** [comment]
Its fixed by the latest update, it seems.

**Comment by rodneycheung** [comment]
Can confirm it's fixed
