### ISSUE TITLE
Bug: Right-click interaction with hidden Details windows

### ISSUE THREAD

**Issue by Nukme** [Tercioo/Details-Damage-Meter#82]
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**

**Game and Details! version**
Details version: R7345
Game version: v8.3.0

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):

0. I have a keybind for showing/hiding all Details windows, say F1.
1. Update to latest version of Details!
2. Toggle F1 to HIDE all Details windows.
3. Right-click the area where Details windows hide.

- Result (what happens when you follow the steps above):

Details:Bookmarks show up, and prevent the area from working properly in-game, such as adjusting cameras, interacting with gateways, etc.

- Expected (what you think the expected behavior would be when following the steps):

Normally(in previous versions), right-click the area of hidden windows invokes nothing about Details.

- When the bug started (a date, wow path release, details update, etc)?

I believe it started with the versions after June 9, 2020.  

- Additional information:

Rolling back to R7336.

**Comment by Tercioo** [comment]
Thanks for reporting!

------ Original Message ------

**Comment by Taquito51** [comment]
Happens both on Retail and Classic versions.

**Comment by Tercioo** [comment]
Only happen with the details window is embed into the chat using the 
Chat Embed feature from Details!?

------ Original Message ------

**Comment by Taquito51** [comment]
> Only happen with the details window is embed into the chat using the Chat Embed feature from Details!?
> […](#)
> ------ Original Message ------ From: "Taquito51" <notifications@github.com> To: "Tercioo/Details-Damage-Meter" <Details-Damage-Meter@noreply.github.com> Cc: "Tercio Jose" <terciob19@hotmail.com>; "Comment" <comment@noreply.github.com> Sent: 29-Jun-20 1:23:16 PM Subject: Re: [Tercioo/Details-Damage-Meter] Bug: Right-click interaction with hidden Details windows (#82)
> Happens both on Retail and Classic versions. — You are receiving this because you commented. Reply to this email directly, view it on GitHub <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTercioo%2FDetails-Damage-Meter%2Fissues%2F82%23issuecomment-651224928&data=02%7C01%7C%7Ca9269f2a779f42b8ae6c08d81c48ba65%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637290445973829690&sdata=9cYtHX6CoisLwW4xphmTxY4DpfjGPeO7xgSPM9c1cZ8%3D&reserved=0>, or unsubscribe <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACEVKWEL6NCFGF2ESFEYGCTRZC5XJANCNFSM4OK35IRA&data=02%7C01%7C%7Ca9269f2a779f42b8ae6c08d81c48ba65%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637290445973829690&sdata=wgLu06Reoy1042bGKrZRhD7sQG1ssw3GIRDuWFr%2BG5Y%3D&reserved=0>.

No, I don't have the embed option enabled:
https://i.imgur.com/w2HXaNe.jpg

**Comment by isitLoVe** [comment]
This is /fstack for the frame:
![image](https://user-images.githubusercontent.com/20051956/86167068-2c972900-bb16-11ea-90cc-86c4eee2c7a7.png)

**Comment by Tercioo** [comment]
The latest release doesn't fix the issue for you?
DetailsRetail.8.3.0.7345a.141 
<https://www.curseforge.com/wow/addons/details/files/2993192>


------ Original Message ------

**Comment by Nukme** [comment]
It's fixed. Thx!

**Comment by Argentru** [comment]
It is still an issue for WoW Classic 1.13.4

**Comment by Tercioo** [comment]
Wow classic didn't received those fixes due to free time, an estimative 
to weekend.

------ Original Message ------
