### ISSUE TITLE
Devastation Bombardment Damage not attributed when trigger by other players

### ISSUE THREAD

**Issue by davemgelinas** [Tercioo/Details-Damage-Meter#830]
Devastation Evoker will be experiencing the same problems AUG initially had but possibly even worse since nobody thinks that Devstation is now pumping others damage. Looking at my log data from the raids this week, it looks like about 20% of the overall devastation evoker damage in details shows for other players via the bombardment triggers from other players.

The only way to see your real damage is using Warcraft Logs which correctly shows it. My concern will be when pugging in either Raids or M+; you'll be hearing folks whining about LOW DPS since and likely end up being kicked. Since Warcraft Logs was able to do it, I assume Details! can do it as well. I went through this same hassle when I was previously AUG before Details! accounted for the damage to be displayed.

**Comment by Flamanis** [comment]
Your assumption is incorrect. Blizzard gave the out of game logs the relevant _SUPPORT events. They did not do them for in game logs. We don't have access to them so we can't see who gave that damage

**Comment by davemgelinas** [comment]
OOF.. Not looking forward to the DPS complaints as DEV, but seems your hands are tied. THanks for the update!

**Comment by Jahfry** [comment]
If there's only 1 Dev evoker, Details could just re-attribute?
