### ISSUE TITLE
Make frame positions save on account level rather than characters

### ISSUE THREAD

**Issue by Daenarys** [Tercioo/Details-Damage-Meter#848]
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**

**Game and Details! version**
11.0.2

**Describe the bug**
I'd love to see the window positions saved on a account level rather than specific characters.

**Comment by Flamanis** [comment]
Like the toggle in the profiles section?

**Comment by Daenarys** [comment]
> Like the toggle in the profiles section?

Oh wow, didn't know that was possible. Thank you so much <3
