### ISSUE TITLE
Windows not grouping

### ISSUE THREAD

**Issue by Kwaky-GH** [Tercioo/Details-Damage-Meter#851]
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**

**Game and Details! version**
Use /details to grab these two.
VCT 13132 RELEASE 11.0.5

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
1. From window 1, Window Control > Create Window
2. Drag window 2 next to window 1, window 1 is highlighted and connecting dots are shown

- Result (what happens when you follow the steps above):
Windows are not grouped

- Expected (what you think the expected behavior would be when following the steps):
Window 2 will be attached to window 1, inheriting the same properties as window 1. When I drag either window, both windows should move. 

- When the bug started (a date, wow path release, details update, etc)?
Encountered it today, 10/26/24. 

- Additional information:

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*

**Screenshots**
Post images of the bug if necessary.

**Combat Log**
Include a link to a combatlog file if the error is about not detecting a skill, usable item or item proc.
The log can be as simple as hitting a mob with white damage and using the item/skill.

**Other Information**
If necessary, add more info here.

**Comment by Flamanis** [comment]
Are the dots turning green? And does window 1 have highlighting on all 4
sides when it starts to glow.

**Comment by Kwaky-GH** [comment]
Hello, window 1 had highlighting on all 4 sides but the dots were not green. Silly mistake on my part, thank you.
