### ISSUE TITLE
Wrong WoW version

### ISSUE THREAD

**Issue by Daenarys** [Tercioo/Details-Damage-Meter#855]
Update tocs for 11.0.5 please, thx.

**Comment by TheRealUncleFrank** [comment]
Came here for the same problem.
CurseForge shows Details was updated Nov 3 and version 11.0.5, but a file download, install, or CurseForge client install, all just give a old Oct 18 11.0.2 version.

**Comment by TheRealUncleFrank** [comment]
Thanks. I'll just wait for the official release.
It just gets a bit confusing when something gets changed and it shows as a new update on CurseForge and the curse client, but then it just installs the same older version.
