### ISSUE TITLE
DEBUG message keeps popping out in chat box

### ISSUE THREAD

**Issue by Toothache-xDD** [Tercioo/Details-Damage-Meter#857]
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**
Yes, I disabled all other plugins and addons, only Details is running. 

**Game and Details! version**
VCT 13166 RELSEASE 11.0.5

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
- I did nothing, just loaded into the game and the error message kept popping out.

- Result (what happens when you follow the steps above):
- The game kept showing "DEBUG: problema com <instance.thisLine> 1 26" in the chat window, sometimes the 26 was replaced by 10. 

- Expected (what you think the expected behavior would be when following the steps):
- N/A

- When the bug started (a date, wow path release, details update, etc)?
- 05/11/2024 1900 CEST, before last night everything worked just fine. 

- Additional information:

**Lua Error**

I tried this command "/console scriptErrors 1" but nothing showed up (even when the only running addon is Details). I re-enabled other addons but disabled Details, the lua error window showed. 
So I tried buggrabber+bugsack+Details only, with a complete stock UI (Modern UI preset by Blizz), still didnt even show error window.  

**Screenshots**

![image](https://github.com/user-attachments/assets/73fc6acb-978d-4ff0-9e7b-878340d88d4e)
This was taken right after a fresh reload. 
It was the same after multiple attempts of reloading/disabling addons. 

**Combat Log**
Include a link to a combatlog file if the error is about not detecting a skill, usable item or item proc.
The log can be as simple as hitting a mob with white damage and using the item/skill.

**Other Information**
If necessary, add more info here.

**Comment by Flamanis** [comment]
When did you first notice this? What did you do previously?

**Comment by Toothache-xDD** [comment]
Just last night. I did nothing more than updating a few other addons via WOWup.io Curseforge. And before that just normal playing, no tinkering around.
Could it be other addons issues?

**Comment by Flamanis** [comment]
Not likely. That error iirc comes from one of the bars not existing when it
should. Try resizing the window, mousing over the last button on the title
bar and "clear all data", and if that don't work, nuke it from orbit with
`/details reinstall`

**Comment by Toothache-xDD** [comment]
I completely reinstalled it and it worked. 

Thx for replying man, have a good day
