### ISSUE TITLE
Bracket Seperator Missing

### ISSUE THREAD

**Issue by Daenarys** [Tercioo/Details-Damage-Meter#867]
I have brackets for right text turned on in the settings but they're not working
![Annotation 2024-11-20 154159](https://github.com/user-attachments/assets/b3aa0dec-8ad2-4348-a1d6-63978500e4fd)
![Annotation 2024-11-20 154528](https://github.com/user-attachments/assets/5cd192f6-a130-4af1-bdc6-b88eadc264c8)
I tried turning of auto-alignment which someone suggested would fix it but its just not working.
Any ideas?

**Comment by Flamanis** [comment]
Aligned text columns will not show brackets or separators. As will custom
right texts
