### ISSUE TITLE
What is the right Classic version ?

### ISSUE THREAD

**Issue by DavidBabel** [Tercioo/Details-Damage-Meter#9]
Hey, thanks for you amazing addon, i just checked on this 

> The classic message should now print a message that this is the wrong version of Details! when the user uses the retail version on Classic WoW.

I wonder what is the good one ? Cannot find any Github

**Comment by chrisblossom** [comment]
Classic: https://www.curseforge.com/wow/addons/details-damage-meter-classic-wow
Retail: https://www.curseforge.com/wow/addons/details

Although I think the retail version also has a version for classic if you [look at the files tab](https://www.curseforge.com/wow/addons/details/files). Would like some clarification on this as well.

**Comment by deadmeu** [comment]
It would be good if the classic version was made available on GitHub.

**Comment by Tercioo** [comment]
not a bug
